# Generated by Django 6.0.5 on 2026-08-04 13:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firm', '0003_firmsetting_allow_engagement_waiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, default='', max_length=60)),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('object_type', models.CharField(db_index=True, max_length=160)),
                ('object_identifier', models.CharField(db_index=True, max_length=160)),
                ('previous_values', models.JSONField(default=dict)),
                ('new_values', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('correlation_identifier', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='firm.lawfirm')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_events',
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['firm', 'object_type', 'object_identifier'], name='audit_event_firm_id_58c9b4_idx')],
            },
        ),
    ]
