# Generated by Django 6.0.5 on 2026-09-28 06:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firm', '0004_firm_registration_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmOnboardingRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firm_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('county', models.CharField(blank=True, max_length=60)),
                ('advocates_count', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred_plan', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('REGISTERED', 'Registered'), ('DECLINED', 'Declined')], default='NEW', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('registered_firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_requests', to='firm.lawfirm')),
            ],
            options={
                'db_table': 'platform_firm_onboarding_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('FIRM_REGISTERED', 'Firm registered'), ('FIRM_UPDATED', 'Firm details updated'), ('FIRM_SUSPENDED', 'Firm suspended'), ('FIRM_REACTIVATED', 'Firm reactivated'), ('SUBSCRIPTION_UPDATED', 'Subscription updated'), ('OWNER_INVITED', 'Owner invitation sent'), ('PAYMENT_CONFIRMED', 'Payment confirmed'), ('INVOICE_VOIDED', 'Invoice voided'), ('PLAN_CREATED', 'Plan created'), ('PLAN_UPDATED', 'Plan updated'), ('PLAN_DELETED', 'Plan deleted'), ('USER_ACTIVATED', 'User activated'), ('USER_DEACTIVATED', 'User deactivated'), ('REQUEST_UPDATED', 'Onboarding request updated')], db_index=True, max_length=40)),
                ('summary', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_activities', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_activities', to='firm.lawfirm')),
            ],
            options={
                'db_table': 'platform_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
