export const CLIENT_CATEGORY_TABS = [
  { key: 'ALL', label: 'All Clients' },
  { key: 'INDIVIDUAL', label: 'Individuals' },
  { key: 'COMPANY', label: 'Companies' },
  { key: 'SOLE_PROPRIETORSHIP', label: 'Sole Proprietorships' },
  { key: 'PARTNERSHIP', label: 'Partnerships' },
  { key: 'LIMITED_LIABILITY_PARTNERSHIP', label: 'LLPs' },
  { key: 'TRUST', label: 'Trusts' },
  { key: 'ESTATE', label: 'Estates' },
  { key: 'NGO', label: 'NGOs' },
  { key: 'NON_PROFIT_ORGANIZATION', label: 'Non-Profits' },
  { key: 'SACCO', label: 'SACCOs' },
  { key: 'COOPERATIVE', label: 'Cooperatives' },
  { key: 'SOCIETY_OR_ASSOCIATION', label: 'Associations' },
  { key: 'PUBLIC_ENTITY', label: 'Government Entities' },
  { key: 'INTERNATIONAL_ORGANIZATION', label: 'International Organizations' },
  { key: 'EDUCATIONAL_INSTITUTION', label: 'Schools' },
  { key: 'RELIGIOUS_ORGANIZATION', label: 'Religious Organizations' },
];
