export const KENYA_COUNTY_TOWNS = {
  Baringo: ['Kabarnet', 'Eldama Ravine', 'Marigat', 'Mogotio'],
  Bomet: ['Bomet', 'Sotik', 'Longisa', 'Mulot'],
  Bungoma: ['Bungoma', 'Webuye', 'Kimilili', 'Chwele'],
  Busia: ['Busia', 'Malaba', 'Nambale', 'Port Victoria'],
  'Elgeyo-Marakwet': ['Iten', 'Kapsowar', 'Chepkorio', 'Tambach'],
  Embu: ['Embu', 'Runyenjes', 'Siakago', 'Kiritiri'],
  Garissa: ['Garissa', 'Dadaab', 'Hulugho', 'Modogashe'],
  'Homa Bay': ['Homa Bay', 'Mbita', 'Oyugis', 'Kendu Bay'],
  Isiolo: ['Isiolo', 'Merti', 'Garbatulla'],
  Kajiado: ['Kajiado', 'Kitengela', 'Ngong', 'Ongata Rongai', 'Namanga'],
  Kakamega: ['Kakamega', 'Mumias', 'Butere', 'Malava'],
  Kericho: ['Kericho', 'Litein', 'Londiani', 'Kipkelion'],
  Kiambu: ['Kiambu', 'Thika', 'Ruiru', 'Limuru', 'Kikuyu', 'Githunguri'],
  Kilifi: ['Kilifi', 'Malindi', 'Mtwapa', 'Mariakani', 'Watamu'],
  Kirinyaga: ['Kerugoya', 'Kutus', 'Sagana', 'Wanguru'],
  Kisii: ['Kisii', 'Ogembo', 'Keroka', 'Suneka'],
  Kisumu: ['Kisumu', 'Ahero', 'Muhoroni', 'Maseno'],
  Kitui: ['Kitui', 'Mwingi', 'Mutomo', 'Kwa Vonza'],
  Kwale: ['Kwale', 'Ukunda', 'Diani', 'Kinango', 'Lunga Lunga'],
  Laikipia: ['Nanyuki', 'Nyahururu', 'Rumuruti', 'Doldol'],
  Lamu: ['Lamu', 'Mpeketoni', 'Witu', 'Faza'],
  Machakos: ['Machakos', 'Athi River', 'Mlolongo', 'Kangundo', 'Tala'],
  Makueni: ['Wote', 'Makindu', 'Sultan Hamud', 'Emali', 'Kibwezi'],
  Mandera: ['Mandera', 'El Wak', 'Rhamu', 'Takaba'],
  Marsabit: ['Marsabit', 'Moyale', 'Laisamis', 'Sololo'],
  Meru: ['Meru', 'Maua', 'Nkubu', 'Timau', 'Laare'],
  Migori: ['Migori', 'Rongo', 'Awendo', 'Kehancha', 'Isebania'],
  Mombasa: ['Mombasa', 'Likoni', 'Changamwe', 'Kisauni'],
  "Murang'a": ["Murang'a", 'Kangema', 'Kenol', 'Maragua', 'Kandara'],
  Nairobi: ['Nairobi', 'Westlands', 'Kasarani', 'Embakasi', 'Langata'],
  Nakuru: ['Nakuru', 'Naivasha', 'Gilgil', 'Molo', 'Njoro'],
  Nandi: ['Kapsabet', 'Nandi Hills', 'Mosoriot', 'Kabiyet'],
  Narok: ['Narok', 'Kilgoris', 'Suswa', 'Ololulunga'],
  Nyamira: ['Nyamira', 'Keroka', 'Nyansiongo', 'Ekerenyo'],
  Nyandarua: ['Ol Kalou', 'Engineer', 'Njabini', 'Ndaragwa'],
  Nyeri: ['Nyeri', 'Karatina', 'Othaya', 'Mukurwe-ini'],
  Samburu: ['Maralal', 'Baragoi', 'Wamba', 'Archer’s Post'],
  Siaya: ['Siaya', 'Bondo', 'Ugunja', 'Yala', 'Usenge'],
  'Taita-Taveta': ['Voi', 'Wundanyi', 'Mwatate', 'Taveta'],
  'Tana River': ['Hola', 'Garsen', 'Bura', 'Madogo'],
  'Tharaka-Nithi': ['Kathwana', 'Chuka', 'Marimanti', 'Chogoria'],
  'Trans Nzoia': ['Kitale', 'Kiminini', 'Endebess', 'Kwanza'],
  Turkana: ['Lodwar', 'Kakuma', 'Lokichogio', 'Lokichar'],
  'Uasin Gishu': ['Eldoret', 'Burnt Forest', 'Moi’s Bridge', 'Turbo'],
  Vihiga: ['Mbale', 'Luanda', 'Majengo', 'Chavakali'],
  Wajir: ['Wajir', 'Habaswein', 'Bute', 'Griftu'],
  'West Pokot': ['Kapenguria', 'Makutano', 'Chepareria', 'Ortum'],
};

export const KENYA_COUNTIES = Object.keys(KENYA_COUNTY_TOWNS);

export const KENYA_TOWN_LOCALITIES = {
  Nairobi: ['CBD', 'Westlands', 'Kilimani', 'Kileleshwa', 'Lavington', 'Karen', 'Langata', 'Kasarani', 'Embakasi', 'South B', 'South C', 'Eastleigh'],
  Mombasa: ['Mombasa Island', 'Nyali', 'Bamburi', 'Kisauni', 'Likoni', 'Changamwe', 'Mikindani'],
  Kisumu: ['CBD', 'Milimani', 'Mamboleo', 'Kondele', 'Nyalenda', 'Manyatta'],
  Nakuru: ['CBD', 'Milimani', 'Lanet', 'Section 58', 'Free Area', 'London', 'Pipeline'],
  Eldoret: ['CBD', 'Elgon View', 'Pioneer', 'Kapsoya', 'Langas', 'Huruma', 'Annex'],
  Thika: ['CBD', 'Makongeni', 'Section 9', 'Landless', 'Kiganjo'],
  Ruiru: ['Ruiru Town', 'Kamakis', 'Membley', 'Githurai', 'Kahawa Sukari'],
  Kiambu: ['Kiambu Town', 'Riabai', 'Ndumberi', 'Kirigiti'],
  Machakos: ['Machakos Town', 'Mua Hills', 'Katoloni', 'Mumbuni'],
  Kitengela: ['Kitengela Town', 'Milimani', 'New Valley', 'Yukos'],
  Garissa: ['Garissa Town', 'Bulla Iftin', 'Bulla Mzuri', 'Madogo'],
  Kakamega: ['Kakamega Town', 'Milimani', 'Amalemba', 'Lurambi'],
  Nyeri: ['Nyeri Town', 'Kamakwa', 'Ruring’u', 'King’ong’o'],
  Meru: ['Meru Town', 'Makutano', 'Milimani', 'Kaaga'],
};

export const localitiesForTown = (town) =>
  KENYA_TOWN_LOCALITIES[town] || (town ? [`${town} Town Centre`] : []);
