# Generated by Django 6.0.5 on 2026-07-16 18:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_add_specific_organization_client_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyclient',
            options={'ordering': ['company_name'], 'verbose_name': 'Company Client', 'verbose_name_plural': 'Company Clients'},
        ),
        migrations.RemoveIndex(
            model_name='companyclient',
            name='company_cli_registr_04460b_idx',
        ),
        migrations.RenameIndex(
            model_name='companyclient',
            new_name='company_status_idx',
            old_name='company_cli_company_599c6e_idx',
        ),
        migrations.RenameIndex(
            model_name='companyclient',
            new_name='company_industry_idx',
            old_name='company_cli_industr_9cb0cf_idx',
        ),
        migrations.AddField(
            model_name='companyclient',
            name='annual_returns_up_to_date',
            field=models.BooleanField(default=False, help_text='Whether the company confirms that annual returns are current.'),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='beneficial_ownership_declared',
            field=models.BooleanField(default=False, help_text='Whether beneficial ownership information has been provided.'),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='company_type',
            field=models.CharField(choices=[('PRIVATE_LIMITED', 'Private Company Limited by Shares'), ('PUBLIC_LIMITED', 'Public Limited Company'), ('COMPANY_LIMITED_BY_GUARANTEE', 'Company Limited by Guarantee'), ('FOREIGN_COMPANY', 'Foreign Company'), ('UNLIMITED_COMPANY', 'Unlimited Company'), ('OTHER', 'Other')], default='PRIVATE_LIMITED', max_length=50),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='compliance_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyclient',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='nature_of_business',
            field=models.TextField(blank=True, default='', help_text="Brief description of the company's principal activities."),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='registration_verified',
            field=models.BooleanField(default=False, help_text='Whether registration details have been verified by the firm.'),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='registration_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='registration_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_company_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='trading_name',
            field=models.CharField(blank=True, default='', help_text='Business or trading name, where different from legal name.', max_length=255),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='companyclient',
            name='company_name',
            field=models.CharField(help_text='Company name as shown on the certificate of incorporation.', max_length=255),
        ),
        migrations.AlterField(
            model_name='companyclient',
            name='company_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DORMANT', 'Dormant'), ('UNDER_ADMINISTRATION', 'Under Administration'), ('IN_RECEIVERSHIP', 'In Receivership'), ('INSOLVENT', 'Insolvent'), ('LIQUIDATION', 'In Liquidation'), ('DISSOLVED', 'Dissolved'), ('STRUCK_OFF', 'Struck Off'), ('OTHER', 'Other')], db_index=True, default='ACTIVE', max_length=50),
        ),
        migrations.AlterField(
            model_name='companyclient',
            name='country_of_incorporation',
            field=models.CharField(default='Kenya', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyclient',
            name='industry',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='companyclient',
            name='registration_number',
            field=models.CharField(db_index=True, help_text='Registration number shown on the incorporation certificate.', max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='companyclient',
            index=models.Index(fields=['company_type'], name='company_type_idx'),
        ),
        migrations.AddIndex(
            model_name='companyclient',
            index=models.Index(fields=['country_of_incorporation'], name='company_country_idx'),
        ),
        migrations.RemoveField(
            model_name='companyclient',
            name='user',
        ),
    ]
