# Generated by Django 6.0.5 on 2026-07-19 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_companyclient_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='individualclient',
            name='citizenship',
            field=models.CharField(blank=True, default='Kenya', max_length=100),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='county_of_residence',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='disability_or_accessibility_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='employer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='identification_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='identification_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='identification_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_individual_client_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='nationality',
            field=models.CharField(blank=True, default='Kenyan', max_length=100),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='next_of_kin_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='next_of_kin_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='next_of_kin_national_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='next_of_kin_physical_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='physical_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='postal_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='preferred_contact_channel',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='preferred_language',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='preferred_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
