# Generated by Django 6.0.5 on 2026-07-20 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_client_types(apps, schema_editor):
    Client = apps.get_model("clients", "Client")
    mappings = {
        "SACCO": ("COOPERATIVE", "NOT_REQUIRED"),
        "NGO": ("NON_PROFIT_ORGANIZATION", "NOT_REQUIRED"),
        "RELIGIOUS_ORGANIZATION": ("NON_PROFIT_ORGANIZATION", "NOT_REQUIRED"),
        "NGO_ASSOCIATION": ("SOCIETY_OR_ASSOCIATION", "REQUIRES_REVIEW"),
        "GOVERNMENT": ("PUBLIC_ENTITY", "NOT_REQUIRED"),
        "GOVERNMENT_BODY": ("PUBLIC_ENTITY", "NOT_REQUIRED"),
        "EDUCATIONAL_INSTITUTION": ("PUBLIC_ENTITY", "REQUIRES_REVIEW"),
        "INTERNATIONAL_ENTITY": ("INTERNATIONAL_ORGANIZATION", "REQUIRES_REVIEW"),
        "FINANCIAL_INSTITUTION": ("COMPANY", "REQUIRES_REVIEW"),
        "BUSINESS_ENTITY": ("COMPANY", "REQUIRES_REVIEW"),
        "REPRESENTATIVE": ("INDIVIDUAL", "REQUIRES_REVIEW"),
    }
    for legacy_type, (canonical_type, review_status) in mappings.items():
        Client.objects.filter(client_type=legacy_type).update(
            legacy_client_type=legacy_type,
            client_type=canonical_type,
            classification_review_status=review_status,
        )


def reverse_legacy_client_types(apps, schema_editor):
    Client = apps.get_model("clients", "Client")
    for client in Client.objects.exclude(legacy_client_type__isnull=True).exclude(legacy_client_type=""):
        client.client_type = client.legacy_client_type
        client.classification_review_status = "NOT_REQUIRED"
        client.save(update_fields=["client_type", "classification_review_status"])


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_individualclient_citizenship_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='classification_review_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('REQUIRES_REVIEW', 'Requires Review'), ('REVIEWED', 'Reviewed')], default='NOT_REQUIRED', max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='legacy_client_type',
            field=models.CharField(blank=True, help_text='Original client_type preserved during legal-capacity classification migration.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estateclient',
            name='deceased_last_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='estateclient',
            name='grant_confirmation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estateclient',
            name='grant_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estateclient',
            name='grant_status',
            field=models.CharField(choices=[('NOT_APPLIED', 'Not Applied'), ('APPLIED', 'Applied'), ('ISSUED', 'Issued'), ('CONFIRMED', 'Confirmed'), ('REVOKED', 'Revoked'), ('DISPUTED', 'Disputed'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='estateclient',
            name='grant_type',
            field=models.CharField(blank=True, choices=[('PROBATE', 'Grant of Probate'), ('LETTERS_OF_ADMINISTRATION', 'Letters of Administration'), ('LIMITED_GRANT', 'Limited Grant'), ('PUBLIC_TRUSTEE', 'Public Trustee'), ('PRE_GRANT_ADVISORY', 'Pre-grant Advisory'), ('OTHER', 'Other')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='estateclient',
            name='verification_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='partnershipclient',
            name='business_sector',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='partnershipclient',
            name='compliance_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='partnershipclient',
            name='country_of_registration',
            field=models.CharField(default='Kenya', max_length=100),
        ),
        migrations.AddField(
            model_name='partnershipclient',
            name='partnership_agreement_reference',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='partnershipclient',
            name='principal_place_of_business',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='partnershipclient',
            name='registration_authority',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='partnershipclient',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnershipclient',
            name='registration_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnershipclient',
            name='status',
            field=models.CharField(blank=True, default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='partnershipclient',
            name='subtype',
            field=models.CharField(choices=[('GENERAL_PARTNERSHIP', 'General Partnership'), ('LIMITED_PARTNERSHIP', 'Limited Partnership'), ('FOREIGN_PARTNERSHIP', 'Foreign Partnership')], default='GENERAL_PARTNERSHIP', max_length=50),
        ),
        migrations.AddField(
            model_name='trustclient',
            name='incorporation_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trustclient',
            name='principal_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trustclient',
            name='purpose',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trustclient',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trustclient',
            name='settlor_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trustclient',
            name='status',
            field=models.CharField(blank=True, default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='trustclient',
            name='trust_deed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trustclient',
            name='verification_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('SOLE_PROPRIETORSHIP', 'Sole Proprietorship'), ('COMPANY', 'Company'), ('PARTNERSHIP', 'Partnership'), ('LIMITED_LIABILITY_PARTNERSHIP', 'Limited Liability Partnership'), ('COOPERATIVE', 'Cooperative'), ('SOCIETY_OR_ASSOCIATION', 'Society or Association'), ('NON_PROFIT_ORGANIZATION', 'Non-Profit Organization'), ('TRUST', 'Trust'), ('ESTATE', 'Estate'), ('PUBLIC_ENTITY', 'Public Entity'), ('INTERNATIONAL_ORGANIZATION', 'International Organization'), ('NGO', 'NGO'), ('GOVERNMENT', 'Government'), ('BUSINESS_ENTITY', 'Business Entity'), ('GOVERNMENT_BODY', 'Government Body'), ('FINANCIAL_INSTITUTION', 'Financial Institution'), ('NGO_ASSOCIATION', 'NGO / Association'), ('RELIGIOUS_ORGANIZATION', 'Religious Organization'), ('EDUCATIONAL_INSTITUTION', 'Educational Institution'), ('REPRESENTATIVE', 'Representative'), ('SACCO', 'SACCO'), ('INTERNATIONAL_ENTITY', 'International Entity')], max_length=50),
        ),
        migrations.AlterField(
            model_name='partnershipclient',
            name='agreement_type',
            field=models.CharField(blank=True, choices=[('GENERAL_PARTNERSHIP', 'General Partnership Agreement'), ('LIMITED_PARTNERSHIP', 'Limited Partnership Agreement'), ('FOREIGN_PARTNERSHIP', 'Foreign Partnership Agreement')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trustclient',
            name='trust_type',
            field=models.CharField(blank=True, choices=[('PRIVATE_TRUST', 'Private Trust'), ('CHARITABLE_TRUST', 'Charitable Trust'), ('INCORPORATED_TRUSTEES', 'Incorporated Trustees'), ('PUBLIC_TRUST', 'Public Trust'), ('OTHER', 'Other')], max_length=100, null=True),
        ),
        migrations.RunPython(migrate_legacy_client_types, reverse_legacy_client_types),
        migrations.CreateModel(
            name='LimitedLiabilityPartnershipClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_name', models.CharField(max_length=255)),
                ('llp_registration_number', models.CharField(db_index=True, max_length=100)),
                ('kra_pin', models.CharField(blank=True, default='', max_length=50)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('country_of_registration', models.CharField(default='Kenya', max_length=100)),
                ('registered_office', models.TextField(blank=True, default='')),
                ('principal_business_address', models.TextField(blank=True, default='')),
                ('sector', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DORMANT', 'Dormant'), ('UNDER_RECEIVERSHIP', 'Under Receivership'), ('DISSOLVED', 'Dissolved'), ('FOREIGN', 'Foreign'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('compliance_notes', models.TextField(blank=True, default='')),
                ('registration_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llp_profile', to='clients.client')),
            ],
            options={
                'db_table': 'llp_clients',
            },
        ),
        migrations.CreateModel(
            name='LLPPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_kind', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ENTITY', 'Entity')], max_length=20)),
                ('legal_name', models.CharField(max_length=255)),
                ('identifier', models.CharField(blank=True, default='', max_length=100)),
                ('kra_pin', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('is_designated_partner', models.BooleanField(default=False)),
                ('authority_to_instruct', models.BooleanField(default=False)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('date_ceased', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llp_partner_roles', to='clients.client')),
                ('llp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='clients.limitedliabilitypartnershipclient')),
            ],
            options={
                'db_table': 'llp_partners',
            },
        ),
        migrations.CreateModel(
            name='NonProfitOrganizationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, default='', max_length=100)),
                ('registration_authority', models.CharField(blank=True, default='', max_length=255)),
                ('nonprofit_form', models.CharField(choices=[('PUBLIC_BENEFIT_ORGANIZATION', 'Public Benefit Organization'), ('LEGACY_NGO_OR_TRANSITIONAL', 'Legacy NGO or Transitional'), ('COMPANY_LIMITED_BY_GUARANTEE', 'Company Limited by Guarantee'), ('CHARITABLE_TRUST', 'Charitable Trust'), ('SOCIETY', 'Society'), ('FAITH_BASED_ORGANIZATION', 'Faith Based Organization'), ('OTHER_NON_PROFIT', 'Other Non-Profit')], max_length=80)),
                ('canonical_legal_form', models.CharField(blank=True, default='', max_length=80)),
                ('pbo_or_ngo_status', models.CharField(blank=True, default='', max_length=100)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('objectives', models.TextField(blank=True, default='')),
                ('sector', models.CharField(blank=True, default='', max_length=150)),
                ('operational_scope', models.TextField(blank=True, default='')),
                ('funding_compliance_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DORMANT', 'Dormant'), ('SUSPENDED', 'Suspended'), ('DISSOLVED', 'Dissolved'), ('LEGACY_REQUIRES_REVIEW', 'Legacy - requires review'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('registration_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nonprofit_profile', to='clients.client')),
            ],
            options={
                'db_table': 'nonprofit_clients',
            },
        ),
        migrations.CreateModel(
            name='PartnershipPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ENTITY', 'Entity')], max_length=20)),
                ('legal_name', models.CharField(max_length=255)),
                ('identifier', models.CharField(blank=True, default='', max_length=100)),
                ('kra_pin', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('designation', models.CharField(choices=[('GENERAL_PARTNER', 'General Partner'), ('LIMITED_PARTNER', 'Limited Partner')], default='GENERAL_PARTNER', max_length=50)),
                ('profit_share', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('authority_to_instruct', models.BooleanField(default=False)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('date_ceased', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnership_partner_roles', to='clients.client')),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='clients.partnershipclient')),
            ],
            options={
                'db_table': 'partnership_partners',
            },
        ),
        migrations.CreateModel(
            name='PublicEntityClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_name', models.CharField(max_length=255)),
                ('subtype', models.CharField(choices=[('NATIONAL_GOVERNMENT', 'National Government'), ('COUNTY_GOVERNMENT', 'County Government'), ('MINISTRY_OR_DEPARTMENT', 'Ministry or Department'), ('CONSTITUTIONAL_COMMISSION', 'Constitutional Commission'), ('INDEPENDENT_OFFICE', 'Independent Office'), ('STATE_CORPORATION', 'State Corporation'), ('COUNTY_ENTITY', 'County Entity'), ('PUBLIC_UNIVERSITY', 'Public University'), ('OTHER_STATUTORY_BODY', 'Other Statutory Body')], max_length=80)),
                ('enabling_instrument', models.CharField(blank=True, default='', max_length=255)),
                ('parent_ministry_or_county', models.CharField(blank=True, default='', max_length=255)),
                ('legal_capacity_notes', models.TextField(blank=True, default='')),
                ('official_address', models.TextField(blank=True, default='')),
                ('legal_department_contact', models.CharField(blank=True, default='', max_length=255)),
                ('statutory_representative', models.CharField(blank=True, default='', max_length=255)),
                ('jurisdiction_level', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DORMANT', 'Dormant'), ('SUSPENDED', 'Suspended'), ('DISSOLVED', 'Dissolved'), ('LEGACY_REQUIRES_REVIEW', 'Legacy - requires review'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('verification_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_entity_profile', to='clients.client')),
            ],
            options={
                'db_table': 'public_entity_clients',
            },
        ),
        migrations.CreateModel(
            name='SocietyAssociationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255)),
                ('common_name', models.CharField(blank=True, default='', max_length=255)),
                ('registration_status', models.CharField(choices=[('REGISTERED', 'Registered'), ('UNREGISTERED', 'Unregistered'), ('EXEMPTED', 'Exempted'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('registration_number', models.CharField(blank=True, default='', max_length=100)),
                ('registration_authority', models.CharField(blank=True, default='', max_length=255)),
                ('constitution_reference', models.CharField(blank=True, default='', max_length=150)),
                ('formation_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('objectives', models.TextField(blank=True, default='')),
                ('sector', models.CharField(blank=True, default='', max_length=150)),
                ('principal_office', models.TextField(blank=True, default='')),
                ('litigation_authority_reference', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DORMANT', 'Dormant'), ('SUSPENDED', 'Suspended'), ('DISSOLVED', 'Dissolved'), ('LEGACY_REQUIRES_REVIEW', 'Legacy - requires review'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('registration_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='society_association_profile', to='clients.client')),
            ],
            options={
                'db_table': 'society_association_clients',
            },
        ),
        migrations.CreateModel(
            name='SoleProprietorshipClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_business_name', models.CharField(max_length=255)),
                ('business_registration_number', models.CharField(blank=True, default='', max_length=100)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('proprietor_name', models.CharField(max_length=255)),
                ('proprietor_identifier', models.CharField(blank=True, default='', max_length=100)),
                ('proprietor_kra_pin', models.CharField(blank=True, default='', max_length=50)),
                ('business_kra_pin', models.CharField(blank=True, default='', max_length=50)),
                ('trading_name', models.CharField(blank=True, default='', max_length=255)),
                ('business_sector', models.CharField(blank=True, default='', max_length=150)),
                ('registered_address', models.TextField(blank=True, default='')),
                ('operational_address', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DORMANT', 'Dormant'), ('SUSPENDED', 'Suspended'), ('DISSOLVED', 'Dissolved'), ('LEGACY_REQUIRES_REVIEW', 'Legacy - requires review'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('registration_verified', models.BooleanField(default=False)),
                ('registration_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sole_proprietorship_profile', to='clients.client')),
                ('registration_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sole_proprietorship_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sole_proprietorship_clients',
            },
        ),
        migrations.CreateModel(
            name='TrustTrustee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trustee_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CORPORATE', 'Corporate Trustee')], max_length=20)),
                ('legal_name', models.CharField(max_length=255)),
                ('identifier', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('cessation_date', models.DateField(blank=True, null=True)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('authority_to_instruct', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trustee_roles', to='clients.client')),
                ('trust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trustees', to='clients.trustclient')),
            ],
            options={
                'db_table': 'trust_trustees',
            },
        ),
        migrations.CreateModel(
            name='ClientRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_legal_name', models.CharField(max_length=255)),
                ('representative_category', models.CharField(choices=[('PROPRIETOR', 'Proprietor'), ('PARTNER', 'Partner'), ('DESIGNATED_PARTNER', 'Designated Partner'), ('DIRECTOR', 'Director'), ('COMPANY_SECRETARY', 'Company Secretary'), ('TRUSTEE', 'Trustee'), ('EXECUTOR', 'Executor'), ('ADMINISTRATOR', 'Administrator'), ('SOCIETY_OFFICIAL', 'Society Official'), ('PBO_OFFICIAL', 'PBO Official'), ('COOPERATIVE_OFFICER', 'Co-operative Officer'), ('ACCOUNTING_OFFICER', 'Accounting Officer'), ('ATTORNEY_GENERAL_REPRESENTATIVE', 'Attorney-General Representative'), ('COUNTY_ATTORNEY', 'County Attorney'), ('AUTHORIZED_PUBLIC_OFFICER', 'Authorized Public Officer'), ('AUTHORIZED_AGENT', 'Authorized Agent'), ('OTHER', 'Other')], default='AUTHORIZED_AGENT', max_length=80)),
                ('role_title', models.CharField(blank=True, default='', max_length=255)),
                ('national_id_or_passport', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('postal_address', models.TextField(blank=True, default='')),
                ('physical_address', models.TextField(blank=True, default='')),
                ('authority_type', models.CharField(blank=True, default='', max_length=100)),
                ('authority_document_reference', models.CharField(blank=True, default='', max_length=150)),
                ('authority_start_date', models.DateField(blank=True, null=True)),
                ('authority_end_date', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_portal_contact', models.BooleanField(default=False)),
                ('is_litigation_representative', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='clients.client')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_client_representatives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_representatives',
                'indexes': [models.Index(fields=['client', 'representative_category'], name='client_repr_client__21b849_idx'), models.Index(fields=['client', 'is_primary'], name='client_repr_client__41c4b8_idx'), models.Index(fields=['client', 'is_litigation_representative'], name='client_repr_client__40482b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CooperativeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(db_index=True, max_length=100)),
                ('subtype', models.CharField(choices=[('PRIMARY_COOPERATIVE', 'Primary Co-operative'), ('COOPERATIVE_UNION', 'Co-operative Union'), ('APEX_COOPERATIVE', 'Apex Co-operative'), ('SACCO', 'SACCO'), ('OTHER_COOPERATIVE', 'Other Co-operative')], max_length=50)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('kra_pin', models.CharField(blank=True, default='', max_length=50)),
                ('registered_office', models.TextField(blank=True, default='')),
                ('area_of_operation', models.CharField(blank=True, default='', max_length=255)),
                ('activity_sector', models.CharField(blank=True, default='', max_length=150)),
                ('regulator_name', models.CharField(blank=True, default='', max_length=255)),
                ('license_number', models.CharField(blank=True, default='', max_length=100)),
                ('license_status', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DORMANT', 'Dormant'), ('SUSPENDED', 'Suspended'), ('DISSOLVED', 'Dissolved'), ('LEGACY_REQUIRES_REVIEW', 'Legacy - requires review'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('compliance_notes', models.TextField(blank=True, default='')),
                ('registration_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_profile', to='clients.client')),
            ],
            options={
                'db_table': 'cooperative_clients',
                'indexes': [models.Index(fields=['registration_number'], name='cooperative_registr_e479c5_idx'), models.Index(fields=['subtype'], name='cooperative_subtype_5a929b_idx')],
            },
        ),
        migrations.CreateModel(
            name='EstatePersonalRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_type', models.CharField(choices=[('EXECUTOR', 'Executor'), ('ADMINISTRATOR', 'Administrator'), ('PUBLIC_TRUSTEE', 'Public Trustee'), ('OTHER_LAWFUL_REPRESENTATIVE', 'Other Lawful Representative')], max_length=50)),
                ('full_legal_name', models.CharField(max_length=255)),
                ('identifier', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('grant_reference', models.CharField(blank=True, default='', max_length=150)),
                ('authority_start_date', models.DateField(blank=True, null=True)),
                ('authority_end_date', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_representatives', to='clients.estateclient')),
            ],
            options={
                'db_table': 'estate_personal_representatives',
                'indexes': [models.Index(fields=['estate', 'representative_type'], name='estate_pers_estate__4fc226_idx'), models.Index(fields=['estate', 'is_primary'], name='estate_pers_estate__39c247_idx')],
            },
        ),
        migrations.CreateModel(
            name='InternationalOrganizationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(choices=[('INTERGOVERNMENTAL', 'Intergovernmental Organization'), ('TREATY_BODY', 'Treaty Body'), ('DIPLOMATIC_OR_MISSION_ENTITY', 'Diplomatic or Mission Entity'), ('OTHER', 'Other')], max_length=80)),
                ('founding_instrument', models.CharField(blank=True, default='', max_length=255)),
                ('headquarters_country', models.CharField(blank=True, default='', max_length=100)),
                ('kenya_recognition_details', models.TextField(blank=True, default='')),
                ('privileges_immunities_status', models.TextField(blank=True, default='')),
                ('kenya_office_address', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DORMANT', 'Dormant'), ('SUSPENDED', 'Suspended'), ('DISSOLVED', 'Dissolved'), ('LEGACY_REQUIRES_REVIEW', 'Legacy - requires review'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('verification_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='international_organization_profile', to='clients.client')),
            ],
            options={
                'db_table': 'international_organization_clients',
                'indexes': [models.Index(fields=['organization_type'], name='internation_organiz_d82c0c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='limitedliabilitypartnershipclient',
            index=models.Index(fields=['llp_registration_number'], name='llp_clients_llp_reg_a6251a_idx'),
        ),
        migrations.AddIndex(
            model_name='limitedliabilitypartnershipclient',
            index=models.Index(fields=['status'], name='llp_clients_status_dd5c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='llppartner',
            index=models.Index(fields=['llp', 'is_active'], name='llp_partner_llp_id_e25195_idx'),
        ),
        migrations.AddIndex(
            model_name='llppartner',
            index=models.Index(fields=['llp', 'is_designated_partner'], name='llp_partner_llp_id_848c24_idx'),
        ),
        migrations.AddIndex(
            model_name='nonprofitorganizationclient',
            index=models.Index(fields=['registration_number'], name='nonprofit_c_registr_a2505c_idx'),
        ),
        migrations.AddIndex(
            model_name='nonprofitorganizationclient',
            index=models.Index(fields=['nonprofit_form'], name='nonprofit_c_nonprof_10667e_idx'),
        ),
        migrations.AddIndex(
            model_name='partnershippartner',
            index=models.Index(fields=['partnership', 'is_active'], name='partnership_partner_ffb54f_idx'),
        ),
        migrations.AddIndex(
            model_name='partnershippartner',
            index=models.Index(fields=['partnership', 'designation'], name='partnership_partner_21ab99_idx'),
        ),
        migrations.AddIndex(
            model_name='publicentityclient',
            index=models.Index(fields=['subtype'], name='public_enti_subtype_689b12_idx'),
        ),
        migrations.AddIndex(
            model_name='publicentityclient',
            index=models.Index(fields=['jurisdiction_level'], name='public_enti_jurisdi_21dc36_idx'),
        ),
        migrations.AddIndex(
            model_name='societyassociationclient',
            index=models.Index(fields=['registration_number'], name='society_ass_registr_3ae5cc_idx'),
        ),
        migrations.AddIndex(
            model_name='societyassociationclient',
            index=models.Index(fields=['registration_status'], name='society_ass_registr_1c7f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='soleproprietorshipclient',
            index=models.Index(fields=['business_registration_number'], name='sole_propri_busines_2132b1_idx'),
        ),
        migrations.AddIndex(
            model_name='soleproprietorshipclient',
            index=models.Index(fields=['business_sector'], name='sole_propri_busines_ee0ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='trusttrustee',
            index=models.Index(fields=['trust', 'is_primary_contact'], name='trust_trust_trust_i_a9cc82_idx'),
        ),
        migrations.AddIndex(
            model_name='trusttrustee',
            index=models.Index(fields=['trust', 'authority_to_instruct'], name='trust_trust_trust_i_760728_idx'),
        ),
    ]
