# Generated by Django 6.0.5 on 2026-07-23 06:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_case_conflict_status_case_date_instructions_received_and_more'),
        ('clients', '0006_client_classification_review_status_and_more'),
        ('firm', '0002_initial'),
        ('staff', '0003_alter_lawyerpermissiongrant_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMatterConflictCheck',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(max_length=40)),
                ('proposed_matter_title', models.CharField(max_length=255)),
                ('proposed_instructions', models.TextField()),
                ('factual_summary', models.TextField(blank=True, default='')),
                ('desired_outcome', models.TextField(blank=True, default='')),
                ('urgency_level', models.CharField(blank=True, default='', max_length=30)),
                ('urgency_details', models.TextField(blank=True, default='')),
                ('limitation_or_deadline_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('AWAITING_INFORMATION', 'Awaiting information'), ('POTENTIAL_CONFLICT', 'Potential conflict'), ('ESCALATED_FOR_REVIEW', 'Escalated for review'), ('CLEARED', 'Cleared for proposed instructions'), ('CONFLICT_CONFIRMED', 'Conflict confirmed'), ('CLOSED_WITHOUT_DECISION', 'Closed without decision')], default='NOT_STARTED', max_length=40)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('names_checked', models.JSONField(blank=True, default=list)),
                ('source_categories_checked', models.JSONField(blank=True, default=list)),
                ('other_source_description', models.TextField(blank=True, default='')),
                ('information_missing', models.TextField(blank=True, default='')),
                ('first_reviewer_findings', models.TextField(blank=True, default='')),
                ('result_summary', models.TextField(blank=True, default='')),
                ('internal_reason', models.TextField(blank=True, default='')),
                ('restricted_note', models.TextField(blank=True, default='')),
                ('decision_confirmation', models.BooleanField(default=False)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('no_adverse_party_currently_known', models.BooleanField(default=False)),
                ('no_adverse_party_explanation', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matter_conflict_checks', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_matter_conflict_checks', to=settings.AUTH_USER_MODEL)),
                ('created_case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='originating_conflict_check', to='cases.case')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_conflict_checks', to='staff.lawyer')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_matter_conflict_checks', to='firm.lawfirm')),
                ('responsible_lawyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_conflict_checks', to='staff.lawyer')),
                ('review_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_conflict_checks', to='staff.lawyer')),
            ],
            options={
                'db_table': 'client_matter_conflict_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientMatterConflictReferenceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_matter_conflict_reference_sequence', to='firm.lawfirm')),
            ],
            options={
                'db_table': 'client_matter_conflict_reference_sequences',
            },
        ),
        migrations.CreateModel(
            name='ConflictCheckHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, default='', max_length=40)),
                ('to_status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('AWAITING_INFORMATION', 'Awaiting information'), ('POTENTIAL_CONFLICT', 'Potential conflict'), ('ESCALATED_FOR_REVIEW', 'Escalated for review'), ('CLEARED', 'Cleared for proposed instructions'), ('CONFLICT_CONFIRMED', 'Conflict confirmed'), ('CLOSED_WITHOUT_DECISION', 'Closed without decision')], max_length=40)),
                ('action', models.CharField(max_length=60)),
                ('summary', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_matter_conflict_history_entries', to=settings.AUTH_USER_MODEL)),
                ('conflict_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='clients.clientmatterconflictcheck')),
            ],
            options={
                'db_table': 'client_matter_conflict_check_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConflictCheckParty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('party_type', models.CharField(choices=[('PERSON', 'Person'), ('ORGANISATION', 'Organisation')], max_length=20)),
                ('role', models.CharField(choices=[('PROSPECTIVE_CLIENT', 'Prospective client'), ('PROPOSED_ADVERSE_PARTY', 'Proposed adverse party'), ('CO_CLAIMANT', 'Co-claimant'), ('CO_RESPONDENT', 'Co-respondent'), ('INTERESTED_PARTY', 'Interested party'), ('DIRECTOR', 'Director'), ('SHAREHOLDER', 'Shareholder'), ('BENEFICIAL_OWNER', 'Beneficial owner'), ('GUARANTOR', 'Guarantor'), ('WITNESS', 'Witness'), ('RELATED_ENTITY', 'Related entity'), ('OTHER', 'Other')], max_length=40)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('identification_reference', models.CharField(blank=True, default='', max_length=120)),
                ('relationship_to_party', models.CharField(blank=True, default='', max_length=120)),
                ('contact_information', models.TextField(blank=True, default='')),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('conflict_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='clients.clientmatterconflictcheck')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conflict_check_parties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_matter_conflict_check_parties',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientmatterconflictcheck',
            index=models.Index(fields=['firm', 'client', 'status'], name='client_matt_firm_id_5342d0_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmatterconflictcheck',
            index=models.Index(fields=['reference_number'], name='client_matt_referen_666d42_idx'),
        ),
        migrations.AddIndex(
            model_name='clientmatterconflictcheck',
            index=models.Index(fields=['status'], name='client_matt_status_69146b_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientmatterconflictcheck',
            constraint=models.UniqueConstraint(fields=('firm', 'reference_number'), name='unique_client_conflict_reference_per_firm'),
        ),
        migrations.AddIndex(
            model_name='conflictcheckhistory',
            index=models.Index(fields=['to_status'], name='client_matt_to_stat_c53bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictcheckhistory',
            index=models.Index(fields=['action'], name='client_matt_action_dd3d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictcheckparty',
            index=models.Index(fields=['role'], name='client_matt_role_e15914_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictcheckparty',
            index=models.Index(fields=['name'], name='client_matt_name_d5affd_idx'),
        ),
    ]
