# Generated by Django 6.0.5 on 2026-07-23 22:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def forwards_access_lifecycle(apps, schema_editor):
    Client = apps.get_model('clients', 'Client')
    Client.objects.filter(access_type='PROSPECT').update(access_type='PORTAL_ENABLED')
    Client.objects.filter(access_type='ASSISTED_CLIENT').update(access_type='ASSISTED')
    Client.objects.filter(previous_access_type='PROSPECT').update(previous_access_type='PORTAL_ENABLED')
    Client.objects.filter(previous_access_type='ASSISTED_CLIENT').update(previous_access_type='ASSISTED')
    Client.objects.filter(lifecycle_status='PROSPECT').update(lifecycle_status='PROSPECTIVE')
    Client.objects.filter(lifecycle_status='OFFICIAL_CLIENT').update(lifecycle_status='OFFICIAL')
    Client.objects.filter(previous_lifecycle_status='PROSPECT').update(previous_lifecycle_status='PROSPECTIVE')
    Client.objects.filter(previous_lifecycle_status='OFFICIAL_CLIENT').update(previous_lifecycle_status='OFFICIAL')


def backwards_access_lifecycle(apps, schema_editor):
    Client = apps.get_model('clients', 'Client')
    Client.objects.filter(access_type='PORTAL_ENABLED').update(access_type='PROSPECT')
    Client.objects.filter(access_type='ASSISTED').update(access_type='ASSISTED_CLIENT')
    Client.objects.filter(previous_access_type='PORTAL_ENABLED').update(previous_access_type='PROSPECT')
    Client.objects.filter(previous_access_type='ASSISTED').update(previous_access_type='ASSISTED_CLIENT')
    Client.objects.filter(lifecycle_status='PROSPECTIVE').update(lifecycle_status='PROSPECT')
    Client.objects.filter(lifecycle_status='OFFICIAL').update(lifecycle_status='OFFICIAL_CLIENT')
    Client.objects.filter(previous_lifecycle_status='PROSPECTIVE').update(previous_lifecycle_status='PROSPECT')
    Client.objects.filter(previous_lifecycle_status='OFFICIAL').update(previous_lifecycle_status='OFFICIAL_CLIENT')


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_clientmatterconflictcheck_and_more'),
        ('staff', '0003_alter_lawyerpermissiongrant_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmatterconflictcheck',
            name='acceptance_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientmatterconflictcheck',
            name='acceptance_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acceptance_decided_client_matter_conflict_checks', to='staff.lawyer'),
        ),
        migrations.AddField(
            model_name='clientmatterconflictcheck',
            name='acceptance_decision',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CLIENT_WITHDREW', 'Client withdrew')], db_index=True, default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='clientmatterconflictcheck',
            name='acceptance_internal_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clientmatterconflictcheck',
            name='acceptance_reason_category',
            field=models.CharField(blank=True, choices=[('CONFLICT_CONFIRMED', 'Conflict confirmed'), ('OUTSIDE_EXPERTISE', 'Outside firm expertise'), ('CAPACITY_CONSTRAINT', 'Capacity constraint'), ('COMMERCIAL_TERMS', 'Commercial terms not agreed'), ('CLIENT_WITHDREW', 'Client withdrew'), ('CDD_RESTRICTED', 'CDD restricted'), ('OTHER', 'Other')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='clientmatterconflictcheck',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientmatterconflictcheck',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_client_matter_conflict_checks', to='staff.lawyer'),
        ),
        migrations.AddField(
            model_name='clientmatterconflictcheck',
            name='engagement_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('DRAFTING', 'Drafting'), ('SENT_TO_CLIENT', 'Sent to client'), ('SIGNED', 'Signed'), ('FEE_ARRANGEMENT_CONFIRMED', 'Fee arrangement confirmed'), ('WAIVED_OR_NOT_REQUIRED', 'Waived or not required')], default='NOT_STARTED', max_length=40),
        ),
        migrations.AddField(
            model_name='clientmatterconflictcheck',
            name='scope_confirmation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='access_type',
            field=models.CharField(choices=[('PORTAL_ENABLED', 'Portal enabled'), ('ASSISTED', 'Assisted'), ('PROSPECT', 'Prospect'), ('ASSISTED_CLIENT', 'Assisted Client')], default='ASSISTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='lifecycle_status',
            field=models.CharField(choices=[('PROSPECTIVE', 'Prospective'), ('OFFICIAL', 'Official'), ('ARCHIVED', 'Archived'), ('PROSPECT', 'Prospect'), ('OFFICIAL_CLIENT', 'Official Client')], default='PROSPECTIVE', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='previous_access_type',
            field=models.CharField(blank=True, choices=[('PORTAL_ENABLED', 'Portal enabled'), ('ASSISTED', 'Assisted'), ('PROSPECT', 'Prospect'), ('ASSISTED_CLIENT', 'Assisted Client')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='previous_lifecycle_status',
            field=models.CharField(blank=True, choices=[('PROSPECTIVE', 'Prospective'), ('OFFICIAL', 'Official'), ('ARCHIVED', 'Archived'), ('PROSPECT', 'Prospect'), ('OFFICIAL_CLIENT', 'Official Client')], max_length=30, null=True),
        ),
        migrations.RunPython(forwards_access_lifecycle, backwards_access_lifecycle),
        migrations.CreateModel(
            name='FirmAcceptanceHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_decision', models.CharField(blank=True, default='', max_length=30)),
                ('to_decision', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CLIENT_WITHDREW', 'Client withdrew')], max_length=30)),
                ('reason_category', models.CharField(blank=True, default='', max_length=40)),
                ('internal_reason', models.TextField(blank=True, default='')),
                ('scope_confirmation', models.TextField(blank=True, default='')),
                ('engagement_status', models.CharField(blank=True, default='', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_matter_acceptance_history_entries', to=settings.AUTH_USER_MODEL)),
                ('conflict_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_history', to='clients.clientmatterconflictcheck')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_matter_acceptance_history_decisions', to='staff.lawyer')),
            ],
            options={
                'db_table': 'client_matter_firm_acceptance_history',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['to_decision'], name='client_matt_to_deci_b48b2f_idx'), models.Index(fields=['reason_category'], name='client_matt_reason__1a9864_idx')],
            },
        ),
    ]
