# Generated by Django 6.0.5 on 2026-07-26 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_individual_identity(apps, schema_editor):
    IndividualClient = apps.get_model('clients', 'IndividualClient')
    ClientDueDiligence = apps.get_model('clients', 'ClientDueDiligence')
    for profile in IndividualClient.objects.select_related('client').all():
        client = profile.client
        updates = []
        if not profile.identification_type and client.national_id:
            profile.identification_type = 'NATIONAL_ID'
            profile.identification_number = client.national_id
            profile.identification_country = profile.identification_country or 'Kenya'
            updates.extend(['identification_type', 'identification_number', 'identification_country'])
        elif not profile.identification_type and client.passport_number:
            profile.identification_type = 'PASSPORT'
            profile.identification_number = client.passport_number
            updates.extend(['identification_type', 'identification_number'])
        if updates:
            profile.save(update_fields=updates)
        ClientDueDiligence.objects.get_or_create(client=client)


def reverse_backfill_individual_identity(apps, schema_editor):
    ClientDueDiligence = apps.get_model('clients', 'ClientDueDiligence')
    ClientDueDiligence.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_migrate_individual_access_type_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='individualclient',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='guardian_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='guardian_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='guardian_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='guardian_relationship',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='identification_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='identification_document_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='identification_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='identification_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='identification_type',
            field=models.CharField(blank=True, choices=[('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport'), ('ALIEN_ID', 'Alien ID'), ('REFUGEE_ID', 'Refugee ID'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('OTHER_GOVERNMENT_ID', 'Other Government ID')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='is_minor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='next_of_kin_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='next_of_kin_identification_number',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='occupation_status',
            field=models.CharField(blank=True, choices=[('EMPLOYED', 'Employed'), ('SELF_EMPLOYED', 'Self-employed'), ('BUSINESS_OWNER', 'Business owner'), ('STUDENT', 'Student'), ('UNEMPLOYED', 'Unemployed'), ('RETIRED', 'Retired'), ('HOMEMAKER', 'Homemaker'), ('OTHER', 'Other'), ('NOT_DISCLOSED', 'Not disclosed')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='personal_data_source',
            field=models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('AUTHORIZED_REPRESENTATIVE', 'Authorized representative'), ('OTHER', 'Other')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='privacy_notice_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='privacy_notice_given_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_privacy_notices_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='privacy_notice_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='verification_method',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='verification_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ClientDueDiligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acting_for_self', models.BooleanField(blank=True, null=True)),
                ('represented_person', models.CharField(blank=True, default='', max_length=255)),
                ('authority_document_reference', models.CharField(blank=True, default='', max_length=255)),
                ('purpose_and_nature_of_relationship', models.TextField(blank=True, default='')),
                ('pep_status', models.CharField(choices=[('NOT_CHECKED', 'Not checked'), ('PENDING', 'Pending'), ('NO_MATCH', 'No match'), ('POTENTIAL_MATCH', 'Potential match'), ('CONFIRMED_MATCH', 'Confirmed match')], default='NOT_CHECKED', max_length=30)),
                ('pep_details', models.TextField(blank=True, default='')),
                ('sanctions_screening_status', models.CharField(choices=[('NOT_CHECKED', 'Not checked'), ('PENDING', 'Pending'), ('NO_MATCH', 'No match'), ('POTENTIAL_MATCH', 'Potential match'), ('CONFIRMED_MATCH', 'Confirmed match')], default='NOT_CHECKED', max_length=30)),
                ('risk_rating', models.CharField(choices=[('NOT_ASSESSED', 'Not assessed'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='NOT_ASSESSED', max_length=30)),
                ('source_of_funds', models.TextField(blank=True, default='')),
                ('source_of_wealth', models.TextField(blank=True, default='')),
                ('enhanced_due_diligence_required', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='due_diligence', to='clients.client')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_client_due_diligence_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Due Diligence',
                'verbose_name_plural': 'Client Due Diligence Records',
                'db_table': 'client_due_diligence',
            },
        ),
        migrations.RunPython(backfill_individual_identity, reverse_backfill_individual_identity),
    ]
