# Generated by Django 6.0.5 on 2026-07-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_individualclient_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualclient',
            name='privacy_notice_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='privacy_notice_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='privacy_notice_delivery_method',
            field=models.CharField(blank=True, choices=[('PORTAL', 'Client portal'), ('PAPER', 'Paper copy'), ('VERBAL', 'Read and explained verbally')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='preferred_channel',
            field=models.CharField(choices=[('IN_PERSON', 'In person'), ('PHONE', 'Phone'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('OTHER', 'Other')], default='PHONE', max_length=20),
        ),
    ]
