# Generated by Django 6.0.5 on 2026-07-27 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_individualclient_privacy_notice_acknowledged_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientduediligence',
            name='authority_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientduediligence',
            name='authority_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientduediligence',
            name='authority_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_client_representative_authorities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientduediligence',
            name='enhanced_due_diligence_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clientduediligence',
            name='representation_capacity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clientduediligence',
            name='risk_assessment_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clientduediligence',
            name='screening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientduediligence',
            name='screening_method',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clientduediligence',
            name='screening_result',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='onboarding_method',
            field=models.CharField(blank=True, choices=[('IN_PERSON', 'In person'), ('PHONE', 'Phone'), ('STAFF_ASSISTED', 'Staff assisted')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='privacy_acknowledgement_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='privacy_data_sharing_explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='privacy_lawful_basis',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='privacy_retention_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
