# Generated by Django 6.0.5 on 2026-07-27 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_clientduediligence_authority_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyclient',
            name='beneficial_ownership_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='client_instructions_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='engagement_letter_status',
            field=models.CharField(blank=True, default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='fee_agreement_status',
            field=models.CharField(blank=True, default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='onboarding_method',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='personal_data_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='preferred_contact_channel',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='privacy_lawful_basis',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='privacy_notice_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='privacy_notice_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='privacy_notice_delivery_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='privacy_notice_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='registration_authority',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='registration_document_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='registration_verification_source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyclient',
            name='company_type',
            field=models.CharField(choices=[('PRIVATE_LIMITED_COMPANY', 'Private Company Limited by Shares'), ('PUBLIC_LIMITED_COMPANY', 'Public Limited Company'), ('PRIVATE_LIMITED', 'Private Company Limited by Shares'), ('PUBLIC_LIMITED', 'Public Limited Company'), ('COMPANY_LIMITED_BY_GUARANTEE', 'Company Limited by Guarantee'), ('FOREIGN_COMPANY', 'Foreign Company'), ('UNLIMITED_COMPANY', 'Unlimited Company'), ('OTHER', 'Other')], default='PRIVATE_LIMITED_COMPANY', max_length=50),
        ),
        migrations.CreateModel(
            name='CompanyBeneficialOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_legal_name', models.CharField(max_length=255)),
                ('person_type', models.CharField(default='INDIVIDUAL', max_length=20)),
                ('national_id_or_passport', models.CharField(blank=True, default='', max_length=100)),
                ('nationality', models.CharField(blank=True, default='', max_length=100)),
                ('residential_address', models.TextField(blank=True, default='')),
                ('ownership_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('voting_rights_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('control_method', models.CharField(max_length=100)),
                ('identity_verified', models.BooleanField(default=False)),
                ('ownership_evidence_reference', models.CharField(max_length=255)),
                ('pep_status', models.CharField(default='PENDING', max_length=30)),
                ('sanctions_screening_status', models.CharField(default='PENDING', max_length=30)),
                ('is_controlling_official', models.BooleanField(default=False)),
                ('control_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficial_owners', to='clients.companyclient')),
            ],
            options={
                'db_table': 'company_beneficial_owners',
            },
        ),
        migrations.CreateModel(
            name='CompanyDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_legal_name', models.CharField(max_length=255)),
                ('person_type', models.CharField(default='INDIVIDUAL', max_length=20)),
                ('national_id_or_passport', models.CharField(blank=True, default='', max_length=100)),
                ('nationality', models.CharField(blank=True, default='', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('residential_address', models.TextField(blank=True, default='')),
                ('role', models.CharField(default='DIRECTOR', max_length=100)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_beneficial_owner', models.BooleanField(default=False)),
                ('authority_to_instruct', models.BooleanField(default=False)),
                ('identity_verified', models.BooleanField(default=False)),
                ('verification_document_reference', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='clients.companyclient')),
            ],
            options={
                'db_table': 'company_directors',
            },
        ),
    ]
