# Generated by Django 6.0.5 on 2026-07-29 18:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_client_previous_user_is_active'),
        ('staff', '0003_alter_lawyerpermissiongrant_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmatterconflictcheck',
            name='jurisdiction_facts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ProposedMatterJurisdiction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOT_ASSESSED', 'Not assessed'), ('PRELIMINARY_SUGGESTION', 'Preliminary suggestion generated'), ('MORE_INFORMATION_REQUIRED', 'More information required'), ('ADVOCATE_REVIEW_REQUIRED', 'Advocate review required'), ('ACCEPTED', 'Accepted by advocate'), ('MODIFIED', 'Modified by advocate'), ('REJECTED', 'Rejected by advocate'), ('FINAL_CONFIRMED', 'Final jurisdiction confirmed'), ('DEFERRED', 'Decision deferred'), ('UNDER_RECONSIDERATION', 'Under reconsideration'), ('CARRIED_OVER', 'Carried over from existing filed case')], default='NOT_ASSESSED', max_length=40)),
                ('input_facts', models.JSONField(blank=True, default=dict)),
                ('suggestion', models.JSONField(blank=True, default=dict)),
                ('alternatives', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('missing_information', models.JSONField(blank=True, default=list)),
                ('authorities', models.JSONField(blank=True, default=list)),
                ('rule_version', models.CharField(blank=True, default='', max_length=40)),
                ('completeness', models.PositiveSmallIntegerField(default=0)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('advocate_action', models.CharField(blank=True, default='', max_length=30)),
                ('final_forum', models.CharField(blank=True, default='', max_length=80)),
                ('final_court_type', models.CharField(blank=True, default='', max_length=80)),
                ('final_court_level', models.CharField(blank=True, default='', max_length=80)),
                ('final_station', models.CharField(blank=True, default='', max_length=255)),
                ('subject_matter_basis', models.TextField(blank=True, default='')),
                ('pecuniary_basis', models.TextField(blank=True, default='')),
                ('territorial_basis', models.TextField(blank=True, default='')),
                ('legal_basis', models.TextField(blank=True, default='')),
                ('advocate_findings', models.TextField(blank=True, default='')),
                ('override_reason', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_proposed_matter_jurisdictions', to='staff.lawyer')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_jurisdiction_suggestions', to=settings.AUTH_USER_MODEL)),
                ('proposed_matter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jurisdiction', to='clients.clientmatterconflictcheck')),
            ],
            options={
                'db_table': 'proposed_matter_jurisdictions',
            },
        ),
        migrations.CreateModel(
            name='ProposedMatterJurisdictionHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('from_status', models.CharField(blank=True, default='', max_length=40)),
                ('to_status', models.CharField(max_length=40)),
                ('snapshot', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_matter_jurisdiction_history', to=settings.AUTH_USER_MODEL)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='clients.proposedmatterjurisdiction')),
            ],
            options={
                'db_table': 'proposed_matter_jurisdiction_history',
                'ordering': ['created_at'],
            },
        ),
    ]
