# Generated by Django 6.0.5 on 2026-07-31 11:39

import uuid

from django.db import migrations, models


def populate_document_references(apps, schema_editor):
    ClientDocument = apps.get_model('clients', 'ClientDocument')
    for document in ClientDocument.objects.filter(reference__isnull=True).iterator():
        document.reference = f"DOC-{uuid.uuid4().hex[:10].upper()}"
        document.save(update_fields=['reference'])


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_clientmatterconflictcheck_jurisdiction_facts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='reference',
            field=models.CharField(db_index=True, max_length=40, null=True, unique=True),
        ),
        migrations.RunPython(populate_document_references, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='clientdocument',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('ACCEPTED', 'Accepted'), ('NEEDS_REPLACEMENT', 'Replacement required')], default='PENDING', max_length=30),
        ),
    ]
