# Generated by Django 6.0.5 on 2026-07-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_clientdocument_reference_clientdocument_review_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='custody_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='physical_copy_retained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='physical_storage_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='source_copy_type',
            field=models.CharField(choices=[('ORIGINAL_INSPECTED', 'Original inspected and scanned'), ('CERTIFIED_COPY', 'Certified copy scanned'), ('CLIENT_COPY', 'Client-supplied copy'), ('OFFICIAL_ELECTRONIC', 'Official electronic record')], default='CLIENT_COPY', max_length=30),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='source_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
