# Generated by Django 5.2.16 on 2026-08-01 11:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_clientdocument_custody_notes_and_more'),
        ('firm', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='document_index',
            field=models.PositiveIntegerField(blank=True, help_text='Sequential index within the KYC folder (the /DN part).', null=True),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='document_type',
            field=models.CharField(choices=[('IDENTIFICATION', 'Identification Document'), ('REGISTRATION', 'Registration Document'), ('CONTRACT', 'Contract'), ('COURT_ORDER', 'Court Order'), ('EVIDENCE', 'Evidence'), ('TAX', 'Tax Document'), ('FINANCIAL', 'Financial Document'), ('LEGAL', 'Legal Document'), ('TITLE_DEED', 'Title Deed'), ('KRA_PIN', 'KRA PIN Certificate'), ('PASSPORT_PHOTO', 'Passport Photo'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='reference',
            field=models.CharField(blank=True, db_index=True, help_text='Full custody reference, e.g. KYC-2026-039/D2.', max_length=60, unique=True),
        ),
        migrations.CreateModel(
            name='ClientKycFolder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, help_text='e.g. KYC-2026-039', max_length=40, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('next_document_index', models.PositiveIntegerField(default=1, help_text='The next /DN index to assign when a document is added.')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_folders', to='clients.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_folders', to='firm.lawfirm')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_kyc_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_kyc_folders',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='kyc_folder',
            field=models.ForeignKey(blank=True, help_text='The KYC folder this document belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='clients.clientkycfolder'),
        ),
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['kyc_folder', 'document_index'], name='client_docu_kyc_fol_360dd2_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientdocument',
            constraint=models.UniqueConstraint(fields=('kyc_folder', 'document_index'), name='unique_document_index_per_kyc_folder'),
        ),
        migrations.AddIndex(
            model_name='clientkycfolder',
            index=models.Index(fields=['firm', 'status'], name='client_kyc__firm_id_56fd38_idx'),
        ),
        migrations.AddIndex(
            model_name='clientkycfolder',
            index=models.Index(fields=['client', 'status'], name='client_kyc__client__175e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='clientkycfolder',
            index=models.Index(fields=['reference'], name='client_kyc__referen_a44b3f_idx'),
        ),
    ]
