# Generated by Django 6.0.5 on 2026-08-01 12:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def preserve_existing_document_register(apps, schema_editor):
    Client = apps.get_model("clients", "Client")
    ClientDocument = apps.get_model("clients", "ClientDocument")
    Sequence = apps.get_model("clients", "ClientDocumentReferenceSequence")
    History = apps.get_model("clients", "ClientKYCReferenceHistory")
    now = django.utils.timezone.now()
    for client in Client.objects.all().iterator():
        if client.kyc_drawer_reference and client.created_by_id:
            Client.objects.filter(pk=client.pk).update(
                kyc_reference_assigned_by_id=client.created_by_id,
                kyc_reference_assigned_at=client.created_at or now,
            )
            History.objects.create(
                client_id=client.pk,
                previous_reference="",
                new_reference=client.kyc_drawer_reference,
                reason="Existing KYC file reference preserved during physical-register migration.",
                changed_by_id=client.created_by_id,
                changed_at=client.created_at or now,
            )
        highest = 0
        for document in ClientDocument.objects.filter(client_id=client.pk).iterator():
            updates = {
                "firm_id": client.firm_id,
                "digital_copy_available": bool(document.file),
                "verification_status": "VERIFIED" if document.is_verified else "NOT_VERIFIED",
                "created_by_id": document.received_by_id or document.uploaded_by_id,
            }
            ClientDocument.objects.filter(pk=document.pk).update(**updates)
            prefix = f"{client.kyc_drawer_reference}/D" if client.kyc_drawer_reference else ""
            if prefix and document.reference.startswith(prefix):
                suffix = document.reference[len(prefix):]
                if suffix.isdigit():
                    highest = max(highest, int(suffix))
        Sequence.objects.update_or_create(client_id=client.pk, defaults={"next_number": highest + 1})


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_physical_document_register'),
        ('firm', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocumentCustodyMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_location_or_custodian', models.CharField(blank=True, default='', max_length=255)),
                ('to_location_or_custodian', models.CharField(max_length=255)),
                ('movement_type', models.CharField(choices=[('RECEIVED', 'Received'), ('TRANSFER', 'Internal transfer'), ('CHECK_OUT', 'Checked out'), ('RETURN', 'Returned'), ('RELEASE', 'Released externally'), ('SECURE_STORAGE', 'Moved to secure storage')], max_length=30)),
                ('moved_at', models.DateTimeField()),
                ('purpose', models.TextField()),
                ('expected_return_at', models.DateTimeField(blank=True, null=True)),
                ('actual_return_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'client_document_custody_movements',
                'ordering': ['-moved_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocumentReferenceCorrection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_reference', models.CharField(max_length=80)),
                ('corrected_reference', models.CharField(max_length=80)),
                ('reason', models.TextField()),
            ],
            options={
                'db_table': 'client_document_reference_corrections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocumentReferenceSequence',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='document_reference_sequence', serialize=False, to='clients.client')),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_document_reference_sequences',
            },
        ),
        migrations.CreateModel(
            name='ClientKYCReferenceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_reference', models.CharField(blank=True, default='', max_length=40)),
                ('new_reference', models.CharField(max_length=40)),
                ('previous_cabinet_location', models.CharField(blank=True, default='', max_length=255)),
                ('new_cabinet_location', models.CharField(blank=True, default='', max_length=255)),
                ('reason', models.TextField()),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'client_kyc_reference_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='kyc_cabinet_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='kyc_reference_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='kyc_reference_assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_client_kyc_references', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='category',
            field=models.CharField(choices=[('KYC_IDENTITY', 'KYC / identity'), ('KYC_TAX', 'KYC / tax identification'), ('CIVIL_STATUS', 'Civil status'), ('ENTITY_RECORD', 'Entity / authority record'), ('PROPERTY', 'Property / land'), ('TRANSACTION', 'Transaction / commercial'), ('MATTER_EVIDENCE', 'Matter evidence'), ('CORRESPONDENCE', 'Correspondence'), ('MEDICAL', 'Medical'), ('POLICE', 'Police / incident'), ('OTHER', 'Other')], default='OTHER', max_length=40),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='condition_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='confidentiality_level',
            field=models.CharField(choices=[('STANDARD', 'Standard confidential'), ('RESTRICTED', 'Restricted'), ('HIGHLY_RESTRICTED', 'Highly restricted')], default='STANDARD', max_length=30),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_document_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='digital_copy_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='document_identifier',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='document_owner_subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='electronic_file_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='electronic_file_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_documents', to='firm.lawfirm'),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='issuing_authority',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='page_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='return_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='subtype',
            field=models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport'), ('ALIEN_ID', 'Alien ID / foreign national certificate'), ('KRA_PIN', 'KRA PIN Certificate'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('MARRIAGE_CERTIFICATE', 'Marriage Certificate'), ('DEATH_CERTIFICATE', 'Death Certificate'), ('PROOF_OF_ADDRESS', 'Proof of Address'), ('INCORPORATION', 'Certificate of Incorporation / Registration'), ('CR12', 'CR12 / Company Search'), ('BUSINESS_REGISTRATION', 'Partnership / Business Registration'), ('TRUST_DEED', 'Trust Deed'), ('AUTHORITY_TO_INSTRUCT', 'Authority / Resolution to Instruct Advocates'), ('TITLE_DEED', 'Title Deed'), ('OFFICIAL_SEARCH', 'Official Search'), ('SALE_AGREEMENT', 'Sale Agreement'), ('CONTRACT', 'Contract / Agreement'), ('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('DELIVERY_NOTE', 'Delivery Note'), ('CORRESPONDENCE', 'Correspondence'), ('MEDICAL_RECORD', 'Medical Record / Report'), ('POLICE_ABSTRACT', 'Police Abstract'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_client_document_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='verification_method',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='verification_status',
            field=models.CharField(choices=[('NOT_VERIFIED', 'Not verified'), ('VERIFIED', 'Verified'), ('FAILED', 'Verification failed'), ('EXPIRED', 'Expired')], default='NOT_VERIFIED', max_length=30),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_client_document_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='visible_damage_or_alteration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='kyc_drawer_reference',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['firm', 'reference'], name='client_docu_firm_id_c5d13c_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['client', 'subtype'], name='client_docu_client__1c6713_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('kyc_drawer_reference__isnull', False), models.Q(('kyc_drawer_reference', ''), _negated=True)), fields=('firm', 'kyc_drawer_reference'), name='unique_client_kyc_reference_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='clientdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('firm', 'reference'), name='unique_client_document_reference_per_firm'),
        ),
        migrations.AddField(
            model_name='clientdocumentcustodymovement',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_movements', to='clients.clientdocument'),
        ),
        migrations.AddField(
            model_name='clientdocumentcustodymovement',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_document_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientdocumentcustodymovement',
            name='released_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='released_document_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientdocumentreferencecorrection',
            name='corrected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_document_reference_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientdocumentreferencecorrection',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_corrections', to='clients.clientdocument'),
        ),
        migrations.AddField(
            model_name='clientkycreferencehistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_kyc_reference_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientkycreferencehistory',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kyc_reference_history', to='clients.client'),
        ),
        migrations.RunPython(preserve_existing_document_register, noop_reverse),
    ]
