# Generated by Django 6.0.5 on 2026-08-01 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_clientdocumentcustodymovement_and_more'),
        ('firm', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_documents', to='firm.lawfirm'),
        ),
    ]
