# Generated by Django 6.0.5 on 2026-08-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_alter_clientdocument_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='is_client_visible',
            field=models.BooleanField(default=False),
        ),
    ]
