# Generated by Django 6.0.5 on 2026-08-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_clientdocument_is_client_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='source_copy_type',
            field=models.CharField(choices=[('ORIGINAL', 'Original'), ('COPY', 'Copy'), ('ORIGINAL_INSPECTED', 'Original inspected and scanned'), ('CERTIFIED_COPY', 'Certified copy scanned'), ('CLIENT_COPY', 'Client-supplied copy'), ('OFFICIAL_ELECTRONIC', 'Official electronic record')], default='CLIENT_COPY', max_length=30),
        ),
    ]
