# Generated by Django 6.0.5 on 2026-08-01 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_alter_clientdocument_source_copy_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocumentRegisterRemoval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_removals', to='clients.clientdocument')),
                ('removed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_document_register_removals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_document_register_removals',
                'ordering': ['-created_at'],
            },
        ),
    ]
