# Generated by Django 6.0.5 on 2026-08-01 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_clientdocumentregisterremoval'),
        ('firm', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clientdocument',
            name='unique_client_document_reference_per_firm',
        ),
        migrations.AddConstraint(
            model_name='clientdocument',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('reference', ''), _negated=True), ('archived_at__isnull', True)), fields=('firm', 'reference'), name='unique_client_document_reference_per_firm'),
        ),
    ]
