# Generated by Django 6.0.5 on 2026-08-02 15:25

from django.db import migrations, models


def classify_existing_documents(apps, schema_editor):
    ClientDocument = apps.get_model("clients", "ClientDocument")
    kyc_subtypes = {
        "NATIONAL_ID", "PASSPORT", "ALIEN_ID", "KRA_PIN", "PROOF_OF_ADDRESS",
        "INCORPORATION", "CR12", "BUSINESS_REGISTRATION", "TRUST_DEED",
        "AUTHORITY_TO_INSTRUCT",
    }
    matter_subtypes = {
        "SALE_AGREEMENT", "CONTRACT", "INVOICE", "RECEIPT", "DELIVERY_NOTE",
        "CORRESPONDENCE", "MEDICAL_RECORD", "POLICE_ABSTRACT", "TITLE_DEED",
        "OFFICIAL_SEARCH",
    }
    ClientDocument.objects.filter(subtype__in=kyc_subtypes).update(classification="CLIENT_KYC")
    ClientDocument.objects.filter(subtype__in=matter_subtypes).update(classification="MATTER_SPECIFIC")
    ClientDocument.objects.filter(category__in=["MATTER_EVIDENCE", "TRANSACTION", "CORRESPONDENCE"]).update(classification="MATTER_SPECIFIC")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('clients', '0027_remove_clientdocument_unique_client_document_reference_per_firm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='classification',
            field=models.CharField(choices=[('CLIENT_KYC', 'Client KYC'), ('MATTER_SPECIFIC', 'Matter Specific'), ('CLIENT_GENERAL', 'Client General'), ('VALUABLE_ORIGINAL', 'Valuable Original'), ('UNCLASSIFIED_PENDING_REVIEW', 'Unclassified Pending Review')], default='CLIENT_KYC', max_length=40),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='temporary_intake_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.RunPython(classify_existing_documents, migrations.RunPython.noop),
    ]
