# Generated by Django 6.0.5 on 2026-08-04 12:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def classify_legacy_engagements(apps, schema_editor):
    Proposal = apps.get_model('clients', 'ClientMatterConflictCheck')
    Engagement = apps.get_model('clients', 'EngagementRecord')
    History = apps.get_model('clients', 'EngagementHistory')
    for proposal in Proposal.objects.exclude(created_by_id=None).exclude(responsible_lawyer_id=None).iterator():
        engagement = Engagement.objects.create(
            firm_id=proposal.firm_id,
            client_id=proposal.client_id,
            proposed_matter_id=proposal.id,
            matter_id=proposal.created_case_id,
            responsible_advocate_id=proposal.responsible_lawyer_id,
            created_by_id=proposal.created_by_id,
            status='LEGACY_REVIEW_REQUIRED',
            scope_of_work=proposal.scope_confirmation or proposal.proposed_instructions,
            fee_arrangement_type='OTHER',
            fee_arrangement_description='Legacy fee arrangement not formally recorded; review required.',
        )
        History.objects.create(
            engagement_id=engagement.id,
            actor_id=proposal.created_by_id,
            action='LEGACY_CLASSIFIED',
            previous_values={},
            new_values={'status': 'LEGACY_REVIEW_REQUIRED'},
            reason='Created from pre-engagement-module data without inferring approval or compliance.',
        )


def reverse_legacy_classification(apps, schema_editor):
    Engagement = apps.get_model('clients', 'EngagementRecord')
    History = apps.get_model('clients', 'EngagementHistory')
    ids = list(Engagement.objects.filter(status='LEGACY_REVIEW_REQUIRED').values_list('id', flat=True))
    History.objects.filter(engagement_id__in=ids, action='LEGACY_CLASSIFIED').delete()
    Engagement.objects.filter(id__in=ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_caseevent_compliance_obligations_and_more'),
        ('clients', '0029_correct_unclassified_document_default'),
        ('firm', '0003_firmsetting_allow_engagement_waiver_and_more'),
        ('staff', '0004_alter_lawyerpermissiongrant_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Drafting'), ('SENT', 'Sent to client'), ('SIGNED', 'Signed'), ('FEE_TERMS_CONFIRMED', 'Fee terms confirmed'), ('RETAINER_PENDING', 'Retainer required'), ('READY', 'Opening requirements satisfied'), ('WAIVED', 'Waived with approval'), ('NOT_REQUIRED', 'Not required under firm policy'), ('SUPERSEDED', 'Superseded'), ('CANCELLED', 'Cancelled'), ('LEGACY_REVIEW_REQUIRED', 'Legacy review required')], db_index=True, default='DRAFT', max_length=32)),
                ('scope_of_work', models.TextField()),
                ('excluded_work', models.TextField(blank=True, default='')),
                ('client_objectives', models.TextField(blank=True, default='')),
                ('communication_method', models.CharField(blank=True, default='', max_length=80)),
                ('reporting_expectations', models.TextField(blank=True, default='')),
                ('fee_arrangement_type', models.CharField(choices=[('CONSULTATION', 'Consultation fee'), ('FIXED', 'Fixed or agreed fee'), ('HOURLY', 'Hourly fee'), ('STAGE_BASED', 'Stage-based fee'), ('MONTHLY_RETAINER', 'Monthly retainer'), ('REMUNERATION_ORDER', 'Advocates Remuneration Order'), ('OTHER', 'Other approved arrangement')], max_length=32)),
                ('fee_arrangement_description', models.TextField()),
                ('estimated_professional_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estimated_disbursements', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('required_retainer', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('retainer_due_date', models.DateField(blank=True, null=True)),
                ('retainer_received', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_by', models.CharField(blank=True, default='', max_length=255)),
                ('internally_approved_at', models.DateTimeField(blank=True, null=True)),
                ('exception_reason', models.TextField(blank=True, default='')),
                ('exception_policy_basis', models.TextField(blank=True, default='')),
                ('exception_approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_engagements', to=settings.AUTH_USER_MODEL)),
                ('authority_to_act_documents', models.ManyToManyField(blank=True, related_name='authority_engagements', to='clients.clientdocument')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_engagements', to=settings.AUTH_USER_MODEL)),
                ('engagement_letter_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='engagement_letters', to='clients.clientdocument')),
                ('exception_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_engagement_exceptions', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='firm.lawfirm')),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='cases.case')),
                ('proposed_matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='clients.clientmatterconflictcheck')),
                ('responsible_advocate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_engagements', to='staff.lawyer')),
            ],
            options={
                'db_table': 'client_engagements',
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('previous_values', models.JSONField(default=dict)),
                ('new_values', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('correlation_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagement_history', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='clients.engagementrecord')),
            ],
            options={
                'db_table': 'client_engagement_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(classify_legacy_engagements, reverse_legacy_classification),
        migrations.AddConstraint(
            model_name='engagementrecord',
            constraint=models.UniqueConstraint(fields=('proposed_matter', 'version'), name='unique_engagement_version_per_proposal'),
        ),
        migrations.AddConstraint(
            model_name='engagementrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'SENT', 'SIGNED', 'FEE_TERMS_CONFIRMED', 'RETAINER_PENDING', 'READY', 'WAIVED', 'NOT_REQUIRED', 'LEGACY_REVIEW_REQUIRED'])), fields=('proposed_matter',), name='one_current_engagement_per_proposal'),
        ),
    ]
