# Generated by Django 6.0.5 on 2026-08-04 12:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def classify_legacy_clients(apps, schema_editor):
    Client = apps.get_model('clients', 'Client')
    Review = apps.get_model('clients', 'ClientComplianceReview')
    for client in Client.objects.iterator():
        Review.objects.get_or_create(
            firm_id=client.firm_id,
            client_id=client.id,
            defaults={
                'identity_status': 'LEGACY_REVIEW_REQUIRED',
                'authority_status': 'LEGACY_REVIEW_REQUIRED',
                'beneficial_ownership_status': 'LEGACY_REVIEW_REQUIRED',
                'due_diligence_status': 'LEGACY_REVIEW_REQUIRED',
                'source_of_funds_status': 'LEGACY_REVIEW_REQUIRED',
                'review_notes': 'Legacy client classification; no compliance completion was inferred.',
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0030_engagementrecord_engagementhistory_and_more'),
        ('firm', '0003_firmsetting_allow_engagement_waiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientComplianceReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_status', models.CharField(choices=[('UNKNOWN', 'Not recorded'), ('LEGACY_REVIEW_REQUIRED', 'Legacy review required'), ('IN_PROGRESS', 'In progress'), ('VERIFIED', 'Verified'), ('NOT_APPLICABLE', 'Not applicable'), ('BLOCKED', 'Blocked')], default='UNKNOWN', max_length=32)),
                ('authority_status', models.CharField(choices=[('UNKNOWN', 'Not recorded'), ('LEGACY_REVIEW_REQUIRED', 'Legacy review required'), ('IN_PROGRESS', 'In progress'), ('VERIFIED', 'Verified'), ('NOT_APPLICABLE', 'Not applicable'), ('BLOCKED', 'Blocked')], default='UNKNOWN', max_length=32)),
                ('beneficial_ownership_status', models.CharField(choices=[('UNKNOWN', 'Not recorded'), ('LEGACY_REVIEW_REQUIRED', 'Legacy review required'), ('IN_PROGRESS', 'In progress'), ('VERIFIED', 'Verified'), ('NOT_APPLICABLE', 'Not applicable'), ('BLOCKED', 'Blocked')], default='UNKNOWN', max_length=32)),
                ('due_diligence_status', models.CharField(choices=[('UNKNOWN', 'Not recorded'), ('LEGACY_REVIEW_REQUIRED', 'Legacy review required'), ('IN_PROGRESS', 'In progress'), ('CLEARED', 'Cleared'), ('ENHANCED_DUE_DILIGENCE', 'Enhanced due diligence required'), ('RESTRICTED', 'Opening restricted')], default='UNKNOWN', max_length=32)),
                ('source_of_funds_required', models.BooleanField(default=False)),
                ('source_of_funds_status', models.CharField(choices=[('UNKNOWN', 'Not recorded'), ('LEGACY_REVIEW_REQUIRED', 'Legacy review required'), ('IN_PROGRESS', 'In progress'), ('VERIFIED', 'Verified'), ('NOT_APPLICABLE', 'Not applicable'), ('BLOCKED', 'Blocked')], default='NOT_APPLICABLE', max_length=32)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('restriction_reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_review', to='clients.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_compliance_reviews', to='firm.lawfirm')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_client_compliance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_compliance_reviews',
            },
        ),
        migrations.CreateModel(
            name='ClientComplianceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(default='REVIEW_RECORDED', max_length=50)),
                ('previous_values', models.JSONField(default=dict)),
                ('new_values', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('correlation_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_compliance_history', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='clients.clientcompliancereview')),
            ],
            options={
                'db_table': 'client_compliance_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(classify_legacy_clients, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='clientcompliancereview',
            constraint=models.UniqueConstraint(fields=('firm', 'client'), name='unique_compliance_review_per_firm_client'),
        ),
    ]
