# Generated by Django 6.0.5 on 2026-08-04 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_generatedclosingdocument'),
        ('clients', '0031_clientcompliancereview_clientcompliancehistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='content_destroyed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='destruction_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destroyed_document_metadata', to='cases.destructionlog'),
        ),
    ]
