# Generated by Django 6.0.5 on 2026-08-04 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0026_deadlinestatushistory'),
        ('clients', '0032_clientdocument_content_destroyed_at_and_more'),
        ('firm', '0003_firmsetting_allow_engagement_waiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReleaseRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.TextField()),
                ('proposed_recipient', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_reason', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('released_to', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_identification', models.CharField(blank=True, default='', max_length=255)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_acknowledgement', models.TextField(blank=True, default='')),
                ('acknowledgement_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='release_acknowledgements', to='clients.clientdocument')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_document_releases', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_requests', to='clients.clientdocument')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_release_requests', to='firm.lawfirm')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_release_requests', to='cases.case')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_document_releases', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_document_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_release_requests',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['REQUESTED', 'APPROVED'])), fields=('document',), name='one_active_release_request_per_document')],
            },
        ),
    ]
