# Generated by Django 6.0.5 on 2026-08-04 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0033_documentreleaserequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmatterconflictcheck',
            name='pre_clearance_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientmatterconflictcheck',
            name='urgent_exception_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clientmatterconflictcheck',
            name='urgent_exception_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientmatterconflictcheck',
            name='urgent_exception_received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_confidential_intake_exceptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
