# Generated by Django 6.0.5 on 2026-08-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0035_onboarding_domain_redesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonprofitorganizationclient',
            name='constitution_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nonprofitorganizationclient',
            name='former_registration_authority',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nonprofitorganizationclient',
            name='governance_structure',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nonprofitorganizationclient',
            name='governing_body_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nonprofitorganizationclient',
            name='headquarters_or_principal_office',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nonprofitorganizationclient',
            name='historical_registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonprofitorganizationclient',
            name='legacy_ngo_registration_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='publicentityclient',
            name='department_or_unit',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='publicentityclient',
            name='kra_pin',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='publicentityclient',
            name='official_contact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='publicentityclient',
            name='verification_source_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
