# Generated by Django 6.0.5 on 2026-09-12 13:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0036_complete_pbo_public_profiles'),
        ('firm', '0003_firmsetting_allow_engagement_waiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkInEnquiry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=32)),
                ('received_at', models.DateTimeField()),
                ('visitor_name', models.CharField(max_length=255)),
                ('safe_contact', models.CharField(max_length=255)),
                ('visitor_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANISATION_REPRESENTATIVE', 'Representative of an organisation')], max_length=40)),
                ('organisation_name', models.CharField(blank=True, max_length=255)),
                ('service_category', models.CharField(max_length=100)),
                ('related_party_names', models.JSONField(blank=True, default=list)),
                ('urgency_type', models.CharField(choices=[('NONE', 'No known urgency'), ('COURT_DATE', 'Court date'), ('LIMITATION_CONCERN', 'Limitation concern'), ('ARREST_OR_CUSTODY', 'Arrest or custody'), ('EVICTION', 'Eviction'), ('OTHER', 'Other urgent issue')], default='NONE', max_length=30)),
                ('urgency_note', models.CharField(blank=True, max_length=255)),
                ('critical_date', models.DateField(blank=True, null=True)),
                ('referral_source', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('privacy_acknowledged', models.BooleanField()),
                ('status', models.CharField(choices=[('RECEIVED_AWAITING_REVIEW', 'Received — awaiting preliminary review')], default='RECEIVED_AWAITING_REVIEW', editable=False, max_length=40)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='walk_in_enquiries', to='firm.lawfirm')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_walk_in_enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at', '-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('firm', 'reference'), name='unique_enquiry_firm_reference'), models.CheckConstraint(condition=models.Q(('status', 'RECEIVED_AWAITING_REVIEW')), name='enquiry_received_status_only'), models.CheckConstraint(condition=models.Q(('privacy_acknowledged', True)), name='enquiry_privacy_acknowledged')],
            },
        ),
        migrations.CreateModel(
            name='WalkInEnquirySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firm.lawfirm')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('firm', 'year'), name='unique_enquiry_firm_year')],
            },
        ),
    ]
