# Generated by Django 6.0.5 on 2026-09-13 19:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0037_walkinenquiry_walkinenquirysequence'),
        ('firm', '0003_firmsetting_allow_engagement_waiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='walkinenquiry',
            name='authority_status',
            field=models.CharField(blank=True, choices=[('NOT_REQUIRED', 'Not required'), ('CLAIMED', 'Claimed'), ('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending')], max_length=20),
        ),
        migrations.AddField(
            model_name='walkinenquiry',
            name='enquiry_for',
            field=models.CharField(blank=True, choices=[('SELF', 'Self'), ('OTHER', 'Another person'), ('ORGANISATION', 'Organisation')], max_length=20),
        ),
        migrations.AddField(
            model_name='walkinenquiry',
            name='notice_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkinenquiry',
            name='notice_delivery_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='walkinenquiry',
            name='notice_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='walkinenquiry',
            name='notice_version',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='walkinenquiry',
            name='prospective_person_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='walkinenquiry',
            name='received_at_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='walkinenquiry',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='walkinenquiry',
            name='visitor_capacity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='walkinenquiry',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='WalkInNoticeDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=120)),
                ('snapshot', models.JSONField()),
                ('method', models.CharField(choices=[('SCREEN', 'Displayed to visitor'), ('READ_ALOUD', 'Read and explained to visitor'), ('PAPER', 'Printed notice provided to visitor')], max_length=20)),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged', models.BooleanField(default=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firm.lawfirm')),
            ],
        ),
        migrations.AddField(
            model_name='walkinenquiry',
            name='notice_delivery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiry', to='clients.walkinnoticedelivery'),
        ),
        migrations.CreateModel(
            name='WalkInPrivacyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_version', models.CharField(max_length=80)),
                ('lawful_basis', models.CharField(choices=[('PRE_CONTRACT', 'Steps requested before a contract — section 30(1)(b)(i)'), ('LEGITIMATE_INTERESTS', 'Legitimate interests — section 30(1)(b)(vii)')], max_length=40)),
                ('lawful_basis_explanation', models.TextField()),
                ('mandatory_legal_requirement', models.TextField()),
                ('recipients', models.TextField()),
                ('retention', models.TextField()),
                ('privacy_contact', models.TextField()),
                ('transfers', models.TextField()),
                ('safeguards', models.TextField()),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('firm', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='intake_privacy', to='firm.lawfirm')),
            ],
        ),
        migrations.CreateModel(
            name='WalkInEnquiryCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(max_length=500)),
                ('previous_values', models.JSONField()),
                ('replacement_values', models.JSONField()),
                ('revision', models.PositiveIntegerField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='clients.walkinenquiry')),
            ],
            options={
                'ordering': ['-revision'],
                'constraints': [models.UniqueConstraint(fields=('enquiry', 'revision'), name='unique_enquiry_correction_revision')],
            },
        ),
    ]
