# Generated by Django 6.0.5 on 2026-09-15 12:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0038_walkinenquiry_authority_status_and_more'),
        ('staff', '0009_lawyer_practicing_certificate_expiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreliminaryReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('REVIEW', 'Awaiting preliminary review'), ('INFORMATION', 'Minimum information requested'), ('AUTHORISED', 'Authorised for prospect/proposal creation'), ('URGENT', 'Urgent review required'), ('CLOSED', 'Closed'), ('CONVERTED', 'Awaiting conflict screening')], default='REVIEW', max_length=20)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('prospective_name', models.CharField(max_length=255)),
                ('entity_kind', models.CharField(choices=[('PERSON', 'Person'), ('ORGANISATION', 'Organisation')], max_length=20)),
                ('visitor_capacity', models.CharField(blank=True, max_length=255)),
                ('service_category', models.CharField(max_length=100)),
                ('working_title', models.CharField(blank=True, max_length=255)),
                ('adverse_parties', models.JSONField(default=list)),
                ('related_parties', models.JSONField(default=list)),
                ('forum', models.CharField(blank=True, max_length=255)),
                ('urgency', models.CharField(default='NONE', max_length=30)),
                ('critical_date', models.DateField(blank=True, null=True)),
                ('preliminary_note', models.CharField(blank=True, max_length=500)),
                ('outcome', models.CharField(blank=True, choices=[('PROCEED_TO_CONFLICT_SCREENING', 'Proceed to conflict screening'), ('REQUEST_MINIMUM_INFORMATION', 'Request minimum information'), ('REFER_ELSEWHERE', 'Refer elsewhere'), ('DECLINE_AT_PRELIMINARY_STAGE', 'Decline at preliminary stage'), ('URGENT_REVIEW_REQUIRED', 'Urgent review required')], max_length=40)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('execution', models.CharField(blank=True, choices=[('CREATE_NOW_BY_LAWYER', 'Create now by lawyer'), ('ASSIGN_CREATION_TO_SECRETARY', 'Assign creation to secretary')], max_length=40)),
                ('missing_fields', models.JSONField(default=list)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='originating_preliminary_reviews', to='clients.client')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='staff.lawyer')),
                ('enquiry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='preliminary_review', to='clients.walkinenquiry')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preliminary_reviews', to='staff.lawyer')),
                ('proposed_matter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preliminary_review', to='clients.clientmatterconflictcheck')),
                ('secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preliminary_reviews', to='staff.secretary')),
            ],
        ),
        migrations.CreateModel(
            name='PreliminaryPhysicalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80)),
                ('opened_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('custody_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='physical_file', to='clients.preliminaryreview')),
            ],
        ),
        migrations.CreateModel(
            name='PreliminaryReviewHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('revision', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=40)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('snapshot', models.JSONField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='clients.preliminaryreview')),
            ],
            options={
                'ordering': ['revision'],
            },
        ),
        migrations.AddConstraint(
            model_name='preliminaryreview',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('client__isnull', True), ('proposed_matter__isnull', True)), models.Q(('client__isnull', False), ('proposed_matter__isnull', False)), _connector='OR'), name='preliminary_conversion_links_together'),
        ),
        migrations.AddConstraint(
            model_name='preliminaryreviewhistory',
            constraint=models.UniqueConstraint(fields=('review', 'revision'), name='unique_preliminary_history_revision'),
        ),
    ]
