# Generated by Django 6.0.5 on 2026-09-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0040_remove_walkin_preliminary'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='alternative_names',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='portal_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not requested'), ('PORTAL_ENABLED_PENDING', 'Portal invitation pending'), ('INVITED', 'Invited')], default='NOT_REQUESTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='companyclient',
            name='company_status',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('ACTIVE', 'Active'), ('DORMANT', 'Dormant'), ('UNDER_ADMINISTRATION', 'Under Administration'), ('IN_RECEIVERSHIP', 'In Receivership'), ('INSOLVENT', 'Insolvent'), ('LIQUIDATION', 'In Liquidation'), ('DISSOLVED', 'Dissolved'), ('STRUCK_OFF', 'Struck Off'), ('OTHER', 'Other')], db_index=True, default='ACTIVE', max_length=50),
        ),
        migrations.AlterField(
            model_name='companyclient',
            name='company_type',
            field=models.CharField(choices=[('UNKNOWN', 'Not yet classified'), ('PRIVATE_LIMITED_COMPANY', 'Private Company Limited by Shares'), ('PUBLIC_LIMITED_COMPANY', 'Public Limited Company'), ('PRIVATE_LIMITED', 'Private Company Limited by Shares'), ('PUBLIC_LIMITED', 'Public Limited Company'), ('COMPANY_LIMITED_BY_GUARANTEE', 'Company Limited by Guarantee'), ('FOREIGN_COMPANY', 'Foreign Company'), ('UNLIMITED_COMPANY', 'Unlimited Company'), ('OTHER', 'Other')], default='PRIVATE_LIMITED_COMPANY', max_length=50),
        ),
        migrations.AlterField(
            model_name='companyclient',
            name='registration_number',
            field=models.CharField(blank=True, db_index=True, help_text='Registration number shown on the incorporation certificate.', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cooperativeclient',
            name='registration_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cooperativeclient',
            name='subtype',
            field=models.CharField(blank=True, choices=[('PRIMARY_COOPERATIVE', 'Primary Co-operative'), ('COOPERATIVE_UNION', 'Co-operative Union'), ('APEX_COOPERATIVE', 'Apex Co-operative'), ('SACCO', 'SACCO'), ('OTHER_COOPERATIVE', 'Other Co-operative')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='internationalorganizationclient',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('INTERGOVERNMENTAL', 'Intergovernmental Organization'), ('TREATY_BODY', 'Treaty Body'), ('DIPLOMATIC_OR_MISSION_ENTITY', 'Diplomatic or Mission Entity'), ('OTHER', 'Other')], default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='limitedliabilitypartnershipclient',
            name='llp_registration_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='publicentityclient',
            name='subtype',
            field=models.CharField(blank=True, choices=[('NATIONAL_GOVERNMENT', 'National Government'), ('COUNTY_GOVERNMENT', 'County Government'), ('MINISTRY_OR_DEPARTMENT', 'Ministry or Department'), ('CONSTITUTIONAL_COMMISSION', 'Constitutional Commission'), ('INDEPENDENT_OFFICE', 'Independent Office'), ('STATE_CORPORATION', 'State Corporation'), ('COUNTY_ENTITY', 'County Entity'), ('PUBLIC_UNIVERSITY', 'Public University'), ('OTHER_STATUTORY_BODY', 'Other Statutory Body')], default='', max_length=80),
        ),
    ]
