# Generated by Django 6.0.5 on 2026-09-16 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0041_client_alternative_names_client_portal_status_and_more'),
        ('firm', '0003_firmsetting_allow_engagement_waiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakePrivacyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_version', models.CharField(max_length=50)),
                ('lawful_basis', models.CharField(choices=[('CONSENT', 'Consent'), ('CONTRACTUAL_NECESSITY', 'Contractual necessity'), ('LEGAL_OBLIGATION', 'Legal obligation'), ('PUBLIC_INTEREST', 'Public interest'), ('LEGITIMATE_INTERESTS', 'Legitimate interests'), ('VITAL_INTERESTS', 'Vital interests'), ('MULTIPLE_APPLICABLE_BASES', 'Multiple applicable lawful bases')], max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('firm', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='intake_privacy', to='firm.lawfirm')),
            ],
        ),
    ]
