# Generated by Django 6.0.5 on 2026-09-16 04:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def preserve_existing_versions(apps, schema_editor):
    Config = apps.get_model('clients', 'IntakePrivacyConfig')
    for config in Config.objects.using(schema_editor.connection.alias).all():
        if config.is_active and config.approved_by_id and config.approved_at:
            config.status = 'ACTIVE'
            config.activated_by_id = config.approved_by_id
            config.activated_at = config.approved_at
            config.effective_date = config.approved_at.date()
            config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0042_intakeprivacyconfig'),
        ('firm', '0003_firmsetting_allow_engagement_waiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeprivacyconfig',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakeprivacyconfig',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intakeprivacyconfig',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='intakeprivacyconfig',
            name='notice_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intakeprivacyconfig',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakeprivacyconfig',
            name='retired_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intakeprivacyconfig',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='intakeprivacyconfig',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='intakeprivacyconfig',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intake_privacy_configs', to='firm.lawfirm'),
        ),
        migrations.RunPython(preserve_existing_versions, migrations.RunPython.noop),
        migrations.RemoveField(model_name='intakeprivacyconfig', name='is_active'),
        migrations.AddConstraint(
            model_name='intakeprivacyconfig',
            constraint=models.UniqueConstraint(fields=('firm', 'policy_version'), name='unique_firm_privacy_version'),
        ),
        migrations.AddConstraint(
            model_name='intakeprivacyconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('firm',), name='one_active_firm_privacy'),
        ),
        migrations.AddConstraint(
            model_name='intakeprivacyconfig',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ACTIVE'), _negated=True), models.Q(('activated_at__isnull', False), ('activated_by__isnull', False), ('approved_at__isnull', False), ('approved_by__isnull', False)), _connector='OR'), name='active_privacy_requires_approval'),
        ),
    ]
