# Generated by Django 6.0.5 on 2026-09-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0043_remove_intakeprivacyconfig_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='subtype',
            field=models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport'), ('ALIEN_ID', 'Alien ID / foreign national certificate'), ('KRA_PIN', 'KRA PIN Certificate'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('MARRIAGE_CERTIFICATE', 'Marriage Certificate'), ('DEATH_CERTIFICATE', 'Death Certificate'), ('PROOF_OF_ADDRESS', 'Proof of Address'), ('INCORPORATION', 'Certificate of Incorporation / Registration'), ('CR12', 'CR12 / Company Search'), ('BUSINESS_REGISTRATION', 'Partnership / Business Registration'), ('TRUST_DEED', 'Trust Deed'), ('AUTHORITY_TO_INSTRUCT', 'Authority / Resolution to Instruct Advocates'), ('ENGAGEMENT_LETTER', 'Engagement letter / retainer agreement'), ('TITLE_DEED', 'Title Deed'), ('OFFICIAL_SEARCH', 'Official Search'), ('SALE_AGREEMENT', 'Sale Agreement'), ('CONTRACT', 'Contract / Agreement'), ('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('DELIVERY_NOTE', 'Delivery Note'), ('CORRESPONDENCE', 'Correspondence'), ('MEDICAL_RECORD', 'Medical Record / Report'), ('POLICE_ABSTRACT', 'Police Abstract'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
