# Generated by Django 6.0.5 on 2026-07-16 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firm', '0002_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountantpermissiongrant',
            name='accountant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='staff.accountant'),
        ),
        migrations.AddField(
            model_name='accountantpermissiongrant',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accountant_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hr',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_staff', to='firm.branch'),
        ),
        migrations.AddField(
            model_name='hr',
            name='department_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_staff', to='firm.department'),
        ),
        migrations.AddField(
            model_name='hr',
            name='law_firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_staff', to='firm.lawfirm'),
        ),
        migrations.AddField(
            model_name='hr',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_subordinates', to='staff.hr'),
        ),
        migrations.AddField(
            model_name='hr',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountant',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountants', to='staff.hr'),
        ),
        migrations.AddField(
            model_name='hrpermissiongrant',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_hr_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hrpermissiongrant',
            name='hr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='staff.hr'),
        ),
        migrations.AddField(
            model_name='it',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_staff', to='firm.branch'),
        ),
        migrations.AddField(
            model_name='it',
            name='department_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_staff', to='firm.department'),
        ),
        migrations.AddField(
            model_name='it',
            name='law_firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_staff', to='firm.lawfirm'),
        ),
        migrations.AddField(
            model_name='it',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_staff_members', to='staff.hr'),
        ),
        migrations.AddField(
            model_name='it',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='it_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itpermissiongrant',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_it_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itpermissiongrant',
            name='it',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='staff.it'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawyers', to='firm.branch'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='department_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawyers', to='firm.department'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='law_firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyers', to='firm.lawfirm'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='practice_areas',
            field=models.ManyToManyField(blank=True, related_name='lawyers', to='firm.practicearea'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='junior_lawyers', to='staff.lawyer'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lawyerpermissiongrant',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_lawyer_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lawyerpermissiongrant',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='staff.lawyer'),
        ),
        migrations.AddField(
            model_name='secretary',
            name='assigned_lawyers',
            field=models.ManyToManyField(blank=True, related_name='assigned_secretaries', to='staff.lawyer'),
        ),
        migrations.AddField(
            model_name='secretary',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretaries', to='firm.branch'),
        ),
        migrations.AddField(
            model_name='secretary',
            name='department_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretaries', to='firm.department'),
        ),
        migrations.AddField(
            model_name='secretary',
            name='law_firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretaries', to='firm.lawfirm'),
        ),
        migrations.AddField(
            model_name='secretary',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretaries', to='staff.lawyer'),
        ),
        migrations.AddField(
            model_name='secretary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secretary_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secretarypermissiongrant',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_secretary_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secretarypermissiongrant',
            name='secretary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='staff.secretary'),
        ),
        migrations.AddConstraint(
            model_name='accountantpermissiongrant',
            constraint=models.UniqueConstraint(fields=('accountant', 'code'), name='unique_accountant_permission'),
        ),
        migrations.AddConstraint(
            model_name='hr',
            constraint=models.UniqueConstraint(fields=('law_firm', 'staff_number'), name='unique_hr_staff_number_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='hr',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_number__isnull', False)), fields=('law_firm', 'employee_number'), name='unique_hr_employee_number_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='accountant',
            constraint=models.UniqueConstraint(fields=('law_firm', 'staff_number'), name='unique_accountant_staff_number_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='accountant',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_number__isnull', False)), fields=('law_firm', 'employee_number'), name='unique_accountant_employee_number_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='hrpermissiongrant',
            constraint=models.UniqueConstraint(fields=('hr', 'code'), name='unique_hr_permission'),
        ),
        migrations.AddConstraint(
            model_name='it',
            constraint=models.UniqueConstraint(fields=('law_firm', 'staff_number'), name='unique_it_staff_number_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='it',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_number__isnull', False)), fields=('law_firm', 'employee_number'), name='unique_it_employee_number_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='itpermissiongrant',
            constraint=models.UniqueConstraint(fields=('it', 'code'), name='unique_it_permission'),
        ),
        migrations.AddConstraint(
            model_name='lawyer',
            constraint=models.UniqueConstraint(fields=('law_firm', 'staff_number'), name='unique_lawyer_staff_number_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='lawyer',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_number__isnull', False)), fields=('law_firm', 'employee_number'), name='unique_lawyer_employee_number_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='lawyerpermissiongrant',
            constraint=models.UniqueConstraint(fields=('lawyer', 'code'), name='unique_lawyer_permission'),
        ),
        migrations.AddConstraint(
            model_name='secretary',
            constraint=models.UniqueConstraint(fields=('law_firm', 'staff_number'), name='unique_secretary_staff_number_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='secretary',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_number__isnull', False)), fields=('law_firm', 'employee_number'), name='unique_secretary_employee_number_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='secretarypermissiongrant',
            constraint=models.UniqueConstraint(fields=('secretary', 'code'), name='unique_secretary_permission'),
        ),
    ]
