# Generated by Django 6.0.5 on 2026-07-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerpermissiongrant',
            name='code',
            field=models.CharField(choices=[('MANAGE_ASSIGNED_CASES', 'Manage Assigned Cases'), ('CREATE_CASES', 'Create legal matters'), ('ASSIGN_OTHER_LAWYER', 'Assign another responsible advocate'), ('MANAGE_CASE_DOCUMENTS', 'Manage Case Documents'), ('SCHEDULE_HEARINGS', 'Schedule Hearings'), ('MANAGE_CLIENT_COMMUNICATIONS', 'Manage Client Communications'), ('USE_LEGAL_RESEARCH', 'Use Legal Research'), ('USE_AI_TOOLS', 'Use AI Tools'), ('APPROVE_DOCUMENTS', 'Approve Documents'), ('VIEW_BILLING', 'View Billing')], max_length=50),
        ),
    ]
