# Generated by Django 6.0.5 on 2026-08-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_lawyerpermissiongrant_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountantpermissiongrant',
            name='code',
            field=models.CharField(choices=[('MANAGE_INVOICES', 'Manage Invoices'), ('MANAGE_PAYMENTS', 'Manage Payments'), ('MANAGE_EXPENSES', 'Manage Expenses'), ('VIEW_FINANCIAL_REPORTS', 'View Financial Reports'), ('MANAGE_CLIENT_BILLING', 'Manage Client Billing'), ('MANAGE_PAYROLL', 'Manage Payroll'), ('MANAGE_TAX_RECORDS', 'Manage Tax Records'), ('APPROVE_INVOICES', 'Approve invoices'), ('RECORD_RECEIPTS', 'Record receipts'), ('MANAGE_CLIENT_MONEY', 'Manage client money'), ('APPROVE_CLIENT_MONEY_PAYMENTS', 'Approve client-money payments'), ('RECONCILE_ACCOUNTS', 'Reconcile financial accounts')], max_length=50),
        ),
    ]
