# Generated by Django 6.0.5 on 2026-08-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_lawyerpermissiongrant_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerpermissiongrant',
            name='code',
            field=models.CharField(choices=[('CREATE_PROPOSED_MATTER', 'Create proposed matter'), ('PERFORM_CONFLICT_CHECK', 'Perform conflict check'), ('APPROVE_CONFLICT_RESULT', 'Approve conflict result'), ('ACCEPT_DECLINE_INSTRUCTIONS', 'Accept or decline instructions'), ('OPEN_MATTER', 'Open matter'), ('CONFIRM_JURISDICTION', 'Confirm jurisdiction'), ('RECORD_COURT_FILING', 'Record court filing'), ('MANAGE_ASSIGNED_CASES', 'Manage Assigned Cases'), ('CREATE_CASES', 'Create legal matters'), ('ASSIGN_OTHER_LAWYER', 'Assign another responsible advocate'), ('MANAGE_CASE_DOCUMENTS', 'Manage Case Documents'), ('SCHEDULE_HEARINGS', 'Schedule Hearings'), ('MANAGE_CLIENT_COMMUNICATIONS', 'Manage Client Communications'), ('USE_LEGAL_RESEARCH', 'Use Legal Research'), ('USE_AI_TOOLS', 'Use AI Tools'), ('APPROVE_DOCUMENTS', 'Approve Documents'), ('VIEW_BILLING', 'View Billing'), ('APPROVE_ENGAGEMENT', 'Approve engagement'), ('WAIVE_ENGAGEMENT', 'Waive engagement requirement'), ('REVIEW_CLIENT_COMPLIANCE', 'Review client identity and due diligence'), ('COMPLETE_LEGAL_ASSESSMENT', 'Complete legal assessment'), ('REQUEST_MATTER_CLOSURE', 'Request matter closure'), ('APPROVE_MATTER_CLOSURE', 'Approve matter closure'), ('REOPEN_MATTER', 'Reopen closed matter'), ('ARCHIVE_MATTER', 'Archive closed matter'), ('ACCESS_RESTRICTED_ARCHIVE', 'Access restricted archive'), ('PLACE_LEGAL_HOLD', 'Place legal hold'), ('APPROVE_DESTRUCTION', 'Approve destruction')], max_length=50),
        ),
    ]
