# Generated by Django 6.0.3 on 2026-08-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_lawyerpermissiongrant_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='practicing_certificate_expiry',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
