# Generated by Django 6.0.5 on 2026-07-16 11:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0005_rename_case_events_is_virt_3d4a2b_idx_case_events_is_virt_46cf81_idx'),
        ('firm', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtroomProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('provider_type', models.CharField(choices=[('JUDICIARY', 'Kenya Judiciary'), ('ZOOM', 'Zoom'), ('TEAMS', 'Microsoft Teams'), ('GOOGLE_MEET', 'Google Meet'), ('WEBEX', 'Webex'), ('OTHER', 'Other')], default='JUDICIARY', max_length=30)),
                ('base_url', models.URLField(blank=True, default='', max_length=1000)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courtroom_providers', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courtroom_providers', to='firm.lawfirm')),
            ],
            options={
                'db_table': 'courtroom_providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourtroomCauseListSync',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(blank=True, default='', max_length=160)),
                ('source_url', models.URLField(blank=True, default='', max_length=1000)),
                ('court_station', models.CharField(blank=True, default='', max_length=255)),
                ('cause_list_date', models.DateField()),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='QUEUED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('matched_events', models.PositiveIntegerField(default=0)),
                ('created_events', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courtroom_cause_list_syncs', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courtroom_cause_list_syncs', to='firm.lawfirm')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cause_list_syncs', to='courtroom.courtroomprovider')),
            ],
            options={
                'db_table': 'courtroom_cause_list_syncs',
                'ordering': ['-cause_list_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourtroomSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('WAITING', 'Waiting'), ('LIVE', 'Live'), ('PAUSED', 'Paused'), ('ENDED', 'Ended'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('join_url', models.URLField(max_length=1000)),
                ('host_url', models.URLField(blank=True, default='', max_length=1000)),
                ('provider_meeting_id', models.CharField(blank=True, default='', max_length=120)),
                ('passcode', models.CharField(blank=True, default='', max_length=120)),
                ('live_started_at', models.DateTimeField(blank=True, null=True)),
                ('live_ended_at', models.DateTimeField(blank=True, null=True)),
                ('allow_recording_downloads', models.BooleanField(default=False)),
                ('last_provider_sync_at', models.DateTimeField(blank=True, null=True)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courtroom_sessions', to=settings.AUTH_USER_MODEL)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courtroom_session', to='cases.caseevent')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='courtroom.courtroomprovider')),
            ],
            options={
                'db_table': 'courtroom_sessions',
                'ordering': ['event__starts_at'],
            },
        ),
        migrations.CreateModel(
            name='CourtroomRecording',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='READY', max_length=20)),
                ('recording_url', models.URLField(blank=True, default='', max_length=1000)),
                ('download_url', models.URLField(blank=True, default='', max_length=1000)),
                ('file', models.FileField(blank=True, null=True, upload_to='courtroom/recordings/')),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courtroom_recordings', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='courtroom.courtroomsession')),
            ],
            options={
                'db_table': 'courtroom_recordings',
                'ordering': ['-recorded_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourtroomAttendanceLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendee_name', models.CharField(max_length=255)),
                ('attendee_email', models.EmailField(blank=True, default='', max_length=254)),
                ('attendee_role', models.CharField(choices=[('ADMIN', 'Admin'), ('LAWYER', 'Lawyer'), ('SECRETARY', 'Secretary'), ('CLIENT', 'Client'), ('GUEST', 'Guest')], default='GUEST', max_length=20)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('CHECKED_IN', 'Checked In'), ('JOINED', 'Joined'), ('LEFT', 'Left'), ('MISSED', 'Missed')], default='INVITED', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courtroom_attendance_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='courtroom.courtroomsession')),
            ],
            options={
                'db_table': 'courtroom_attendance_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='courtroomprovider',
            index=models.Index(fields=['firm', 'is_active'], name='courtroom_p_firm_id_5930b2_idx'),
        ),
        migrations.AddIndex(
            model_name='courtroomprovider',
            index=models.Index(fields=['firm', 'is_default'], name='courtroom_p_firm_id_b30cf3_idx'),
        ),
        migrations.AddConstraint(
            model_name='courtroomprovider',
            constraint=models.UniqueConstraint(fields=('firm', 'name'), name='unique_courtroom_provider_per_firm'),
        ),
        migrations.AddIndex(
            model_name='courtroomcauselistsync',
            index=models.Index(fields=['firm', 'cause_list_date'], name='courtroom_c_firm_id_b06206_idx'),
        ),
        migrations.AddIndex(
            model_name='courtroomcauselistsync',
            index=models.Index(fields=['status'], name='courtroom_c_status_b5bbe6_idx'),
        ),
        migrations.AddIndex(
            model_name='courtroomsession',
            index=models.Index(fields=['status'], name='courtroom_s_status_4bdb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='courtroomsession',
            index=models.Index(fields=['provider'], name='courtroom_s_provide_670a03_idx'),
        ),
        migrations.AddIndex(
            model_name='courtroomrecording',
            index=models.Index(fields=['session', 'status'], name='courtroom_r_session_e08efd_idx'),
        ),
        migrations.AddIndex(
            model_name='courtroomrecording',
            index=models.Index(fields=['is_downloadable'], name='courtroom_r_is_down_59fc35_idx'),
        ),
        migrations.AddIndex(
            model_name='courtroomattendancelog',
            index=models.Index(fields=['session', 'status'], name='courtroom_a_session_a15546_idx'),
        ),
        migrations.AddIndex(
            model_name='courtroomattendancelog',
            index=models.Index(fields=['user'], name='courtroom_a_user_id_8bfabf_idx'),
        ),
        migrations.AddIndex(
            model_name='courtroomattendancelog',
            index=models.Index(fields=['attendee_role'], name='courtroom_a_attende_60d3f7_idx'),
        ),
    ]
