# Generated by Django 6.0.5 on 2026-08-02 22:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_existing_courtroom_data(apps, schema_editor):
    Session = apps.get_model('courtroom', 'CourtroomSession')
    Permission = apps.get_model('courtroom', 'CourtRecordingPermission')
    for session in Session.objects.select_related('event__case').iterator():
        url = (session.join_url or '').lower()
        if 'teams.microsoft.com' in url or 'teams.live.com' in url:
            detected = 'MICROSOFT_TEAMS'
        elif 'meet.google.com' in url:
            detected = 'GOOGLE_MEET'
        elif 'zoom.us' in url:
            detected = 'ZOOM'
        elif 'webex.com' in url:
            detected = 'WEBEX'
        elif 'youtube.com' in url or 'youtu.be' in url:
            detected = 'YOUTUBE_LIVE'
        elif 'judiciary.go.ke' in url or 'court.go.ke' in url:
            detected = 'JUDICIARY_PORTAL'
        else:
            detected = 'OTHER'
        event = session.event
        session.provider_detected = detected
        session.responsible_advocate_id = event.case.assigned_lawyer_id
        session.client_access_from = event.virtual_courtroom_available_from
        session.client_access_until = event.virtual_courtroom_available_until
        session.save(update_fields=['provider_detected', 'responsible_advocate', 'client_access_from', 'client_access_until'])
        Permission.objects.get_or_create(session=session, defaults={'permission_status': 'NOT_REQUESTED'})


def reverse_existing_courtroom_data(apps, schema_editor):
    apps.get_model('courtroom', 'CourtRecordingPermission').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_physical_matter_file_workflow'),
        ('courtroom', '0001_initial'),
        ('staff', '0003_alter_lawyerpermissiongrant_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courtroomprovider',
            name='allowed_hostnames',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='courtroomprovider',
            name='requires_mobile_app',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courtroomprovider',
            name='supports_desktop_web',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courtroomsession',
            name='backup_advocate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_courtroom_sessions', to='staff.lawyer'),
        ),
        migrations.AddField(
            model_name='courtroomsession',
            name='client_access_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courtroomsession',
            name='client_access_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courtroomsession',
            name='client_access_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courtroomsession',
            name='client_attendance_requirement',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('OPTIONAL', 'Optional'), ('REQUIRED', 'Required'), ('RESTRICTED', 'Restricted'), ('TO_BE_CONFIRMED', 'To be confirmed')], default='TO_BE_CONFIRMED', max_length=30),
        ),
        migrations.AddField(
            model_name='courtroomsession',
            name='join_window_minutes_after',
            field=models.PositiveSmallIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='courtroomsession',
            name='join_window_minutes_before',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='courtroomsession',
            name='link_source',
            field=models.CharField(blank=True, choices=[('CAUSE_LIST', 'Cause list'), ('REGISTRY_EMAIL', 'Registry email'), ('JUDICIARY_WEBSITE', 'Judiciary website'), ('OFFICIAL_COMMUNICATION', 'Other official communication')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='courtroomsession',
            name='link_source_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='courtroomsession',
            name='link_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courtroomsession',
            name='link_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courtroomsession',
            name='link_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_courtroom_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courtroomsession',
            name='matter_called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courtroomsession',
            name='matter_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courtroomsession',
            name='provider_detected',
            field=models.CharField(blank=True, choices=[('JUDICIARY_PORTAL', 'Judiciary Portal'), ('MICROSOFT_TEAMS', 'Microsoft Teams'), ('ZOOM', 'Zoom'), ('GOOGLE_MEET', 'Google Meet'), ('WEBEX', 'Webex'), ('YOUTUBE_LIVE', 'YouTube Live'), ('OTHER', 'Other'), ('JUDICIARY', 'Kenya Judiciary (legacy)'), ('TEAMS', 'Microsoft Teams (legacy)')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='courtroomsession',
            name='responsible_advocate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_courtroom_sessions', to='staff.lawyer'),
        ),
        migrations.AddField(
            model_name='courtroomsession',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courtroomsession',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_courtroom_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courtroomattendancelog',
            name='status',
            field=models.CharField(choices=[('INVITED', 'Invited'), ('READY_CHECK_COMPLETED', 'Ready check completed'), ('JOIN_REQUESTED', 'Join requested'), ('PROVIDER_OPENED', 'Provider opened'), ('JOIN_CONFIRMED', 'Join confirmed'), ('LEFT', 'Left'), ('TECHNICAL_DIFFICULTY', 'Technical difficulty'), ('MISSED', 'Missed'), ('CHECKED_IN', 'Checked in (legacy)'), ('JOINED', 'Joined (legacy)')], default='INVITED', max_length=30),
        ),
        migrations.AlterField(
            model_name='courtroomprovider',
            name='provider_type',
            field=models.CharField(choices=[('JUDICIARY_PORTAL', 'Judiciary Portal'), ('MICROSOFT_TEAMS', 'Microsoft Teams'), ('ZOOM', 'Zoom'), ('GOOGLE_MEET', 'Google Meet'), ('WEBEX', 'Webex'), ('YOUTUBE_LIVE', 'YouTube Live'), ('OTHER', 'Other'), ('JUDICIARY', 'Kenya Judiciary (legacy)'), ('TEAMS', 'Microsoft Teams (legacy)')], default='OTHER', max_length=30),
        ),
        migrations.AlterField(
            model_name='courtroomsession',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PREPARING', 'Preparing'), ('READY_TO_JOIN', 'Ready to join'), ('WAITING_ROOM', 'Waiting room'), ('COURT_IN_SESSION', 'Court in session'), ('MATTER_NOT_CALLED', 'Matter not called'), ('POSSIBLE_MATTER_CALL', 'Possible matter call'), ('MATTER_CALLED', 'Matter called'), ('STOOD_DOWN', 'Stood down'), ('PASSED_OVER', 'Passed over'), ('ADJOURNED', 'Adjourned'), ('DIRECTIONS_ISSUED', 'Directions issued'), ('RULING_DELIVERED', 'Ruling delivered'), ('COMPLETED', 'Completed'), ('LINK_FAILED', 'Link failed'), ('REGISTRY_CONTACTED', 'Registry contacted'), ('CANCELLED', 'Cancelled'), ('WAITING', 'Waiting (legacy)'), ('LIVE', 'Live (legacy)'), ('PAUSED', 'Paused (legacy)'), ('ENDED', 'Ended (legacy)')], default='SCHEDULED', max_length=20),
        ),
        migrations.CreateModel(
            name='CourtRecordingPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission_status', models.CharField(choices=[('NOT_REQUESTED', 'Not requested'), ('REQUESTED', 'Requested'), ('GRANTED', 'Granted'), ('REFUSED', 'Refused'), ('REVOKED', 'Revoked')], default='NOT_REQUESTED', max_length=20)),
                ('permission_scope', models.CharField(blank=True, default='', max_length=255)),
                ('granted_by', models.CharField(blank=True, default='', max_length=255)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('authority_note', models.TextField(blank=True, default='')),
                ('audio_allowed', models.BooleanField(default=False)),
                ('video_allowed', models.BooleanField(default=False)),
                ('transcription_allowed', models.BooleanField(default=False)),
                ('retention_until', models.DateField(blank=True, null=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_court_permissions', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording_permission', to='courtroom.courtroomsession')),
                ('supporting_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_recording_permissions', to='cases.caseattachment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourtroomLaunchGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launch_grants', to='courtroom.courtroomsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courtroom_launch_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courtroom_launch_grants',
            },
        ),
        migrations.CreateModel(
            name='CourtroomStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, default='', max_length=30)),
                ('new_status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PREPARING', 'Preparing'), ('READY_TO_JOIN', 'Ready to join'), ('WAITING_ROOM', 'Waiting room'), ('COURT_IN_SESSION', 'Court in session'), ('MATTER_NOT_CALLED', 'Matter not called'), ('POSSIBLE_MATTER_CALL', 'Possible matter call'), ('MATTER_CALLED', 'Matter called'), ('STOOD_DOWN', 'Stood down'), ('PASSED_OVER', 'Passed over'), ('ADJOURNED', 'Adjourned'), ('DIRECTIONS_ISSUED', 'Directions issued'), ('RULING_DELIVERED', 'Ruling delivered'), ('COMPLETED', 'Completed'), ('LINK_FAILED', 'Link failed'), ('REGISTRY_CONTACTED', 'Registry contacted'), ('CANCELLED', 'Cancelled'), ('WAITING', 'Waiting (legacy)'), ('LIVE', 'Live (legacy)'), ('PAUSED', 'Paused (legacy)'), ('ENDED', 'Ended (legacy)')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('SYSTEM', 'System'), ('AI_SUGGESTION', 'AI suggestion')], default='MANUAL', max_length=20)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courtroom_status_changes', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='courtroom.courtroomsession')),
            ],
            options={
                'db_table': 'courtroom_status_history',
                'ordering': ['timestamp'],
            },
        ),
        migrations.RunPython(migrate_existing_courtroom_data, reverse_existing_courtroom_data),
    ]
