# Generated by Django 6.0.5 on 2026-07-16 04:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('case_type', models.CharField(choices=[('CIVIL', 'Civil'), ('CRIMINAL', 'Criminal'), ('FAMILY', 'Family'), ('LAND', 'Land'), ('EMPLOYMENT', 'Employment'), ('COMMERCIAL', 'Commercial'), ('SUCCESSION', 'Succession'), ('CONSTITUTIONAL', 'Constitutional'), ('TAX', 'Tax'), ('IMMIGRATION', 'Immigration'), ('JUDICIAL_REVIEW', 'Judicial Review'), ('ELECTION_PETITION', 'Election Petition'), ('TRIBUNAL', 'Tribunal'), ('ARBITRATION', 'Arbitration'), ('MEDIATION', 'Mediation'), ('CONVEYANCING', 'Conveyancing'), ('DEBT_RECOVERY', 'Debt Recovery'), ('TRAFFIC', 'Traffic'), ('CHILDREN', 'Children Matter'), ('SMALL_CLAIM', 'Small Claim')], max_length=40)),
                ('procedure_track', models.CharField(blank=True, choices=[('CIVIL_SUIT', 'Civil Suit'), ('MISC_APPLICATION', 'Miscellaneous Application'), ('PETITION', 'Petition'), ('JUDICIAL_REVIEW', 'Judicial Review'), ('APPEAL', 'Appeal'), ('CRIMINAL_TRIAL', 'Criminal Trial'), ('CRIMINAL_APPEAL', 'Criminal Appeal'), ('SUCCESSION_CAUSE', 'Succession Cause'), ('FAMILY_CAUSE', 'Family Cause'), ('CHILDREN_MATTER', 'Children Matter'), ('EMPLOYMENT_CLAIM', 'Employment Claim'), ('ELC_SUIT', 'Environment and Land Suit'), ('SMALL_CLAIM', 'Small Claim'), ('TRIBUNAL_MATTER', 'Tribunal Matter'), ('ADR', 'Alternative Dispute Resolution'), ('NON_CONTENTIOUS', 'Non-Contentious Matter')], default='', max_length=60)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('PENDING_FILING', 'Pending Filing'), ('FILED', 'Filed in Court'), ('SERVICE_PENDING', 'Service Pending'), ('SERVED', 'Served'), ('AWAITING_RESPONSE', 'Awaiting Response'), ('MENTION', 'Mention'), ('DIRECTIONS', 'Directions'), ('PRE_TRIAL', 'Pre-Trial'), ('MEDIATION', 'Mediation'), ('HEARING', 'Hearing'), ('SUBMISSIONS', 'Submissions'), ('AWAITING_RULING', 'Awaiting Ruling'), ('AWAITING_JUDGMENT', 'Awaiting Judgment'), ('JUDGMENT_DELIVERED', 'Judgment Delivered'), ('DECREE_EXTRACTION', 'Decree Extraction'), ('EXECUTION', 'Execution'), ('APPEAL_WINDOW', 'Appeal Window'), ('NOTICE_OF_APPEAL_FILED', 'Notice of Appeal Filed'), ('ON_APPEAL', 'On Appeal'), ('APPEAL_DECIDED', 'Appeal Decided'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('SETTLED', 'Settled'), ('WITHDRAWN', 'Withdrawn'), ('DISMISSED', 'Dismissed'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=40)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('court_type', models.CharField(choices=[('MAGISTRATE', 'Magistrate Court'), ('HIGH_COURT', 'High Court'), ('COURT_OF_APPEAL', 'Court of Appeal'), ('SUPREME_COURT', 'Supreme Court'), ('ENVIRONMENT_LAND', 'Environment and Land Court'), ('EMPLOYMENT_LABOUR', 'Employment and Labour Court'), ('SMALL_CLAIMS', 'Small Claims Court'), ('KADHI', 'Kadhi Court'), ('COURT_MARTIAL', 'Court Martial'), ('TRIBUNAL', 'Tribunal'), ('ADR', 'Alternative Dispute Resolution'), ('OTHER', 'Other')], max_length=40)),
                ('court_division', models.CharField(blank=True, choices=[('CIVIL', 'Civil Division'), ('CRIMINAL', 'Criminal Division'), ('COMMERCIAL_TAX', 'Commercial and Tax Division'), ('CONSTITUTIONAL_HUMAN_RIGHTS', 'Constitutional and Human Rights Division'), ('FAMILY', 'Family Division'), ('JUDICIAL_REVIEW', 'Judicial Review Division'), ('ANTI_CORRUPTION_ECONOMIC_CRIMES', 'Anti-Corruption and Economic Crimes Division'), ('ELC', 'Environment and Land Court'), ('ELRC', 'Employment and Labour Relations Court'), ('SMALL_CLAIMS', 'Small Claims Court'), ('KADHI', 'Kadhi Court'), ('TRIBUNAL', 'Tribunal'), ('APPELLATE', 'Appellate'), ('GENERAL', 'General Registry'), ('OTHER', 'Other')], default='', max_length=60)),
                ('court_name', models.CharField(blank=True, default='', max_length=255)),
                ('court_station', models.CharField(blank=True, default='', max_length=255)),
                ('registry', models.CharField(blank=True, default='', max_length=255)),
                ('courtroom', models.CharField(blank=True, default='', max_length=100)),
                ('judicial_officer', models.CharField(blank=True, default='', max_length=255)),
                ('court_location', models.CharField(blank=True, default='', max_length=255)),
                ('efiling_reference', models.CharField(blank=True, default='', max_length=120)),
                ('cts_reference', models.CharField(blank=True, default='', max_length=120)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=120)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('next_court_date', models.DateTimeField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, default='', max_length=255)),
                ('plaintiff', models.CharField(blank=True, default='', max_length=255)),
                ('defendant', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'case_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_type', models.CharField(choices=[('PLEADING', 'Pleading'), ('AFFIDAVIT', 'Affidavit'), ('EVIDENCE', 'Evidence'), ('CORRESPONDENCE', 'Correspondence'), ('COURT_ORDER', 'Court Order'), ('RULING', 'Ruling'), ('JUDGMENT', 'Judgment'), ('DECREE', 'Decree'), ('RECEIPT', 'Receipt'), ('AUTHORITY_TO_ACT', 'Authority to Act'), ('CLIENT_IDENTIFICATION', 'Client Identification'), ('OTHER', 'Other')], default='OTHER', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='case_attachments/')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('is_client_visible', models.BooleanField(default=False)),
                ('is_confidential', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'case_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseCourtroom',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('court_station', models.CharField(max_length=255)),
                ('registry', models.CharField(blank=True, default='', max_length=255)),
                ('courtroom', models.CharField(blank=True, default='', max_length=100)),
                ('judicial_officer', models.CharField(blank=True, default='', max_length=255)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'case_courtrooms',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('MENTION', 'Mention'), ('HEARING', 'Hearing'), ('DIRECTIONS', 'Directions'), ('PRE_TRIAL', 'Pre-Trial Conference'), ('MEDIATION', 'Mediation'), ('SUBMISSIONS', 'Submissions'), ('RULING', 'Ruling'), ('JUDGMENT', 'Judgment'), ('TAXATION', 'Taxation'), ('EXECUTION', 'Execution'), ('REGISTRY_ACTION', 'Registry Action'), ('CLIENT_MEETING', 'Client Meeting'), ('OTHER', 'Other')], max_length=40)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ADJOURNED', 'Adjourned'), ('TAKEN_OUT', 'Taken Out'), ('PROCEEDED', 'Proceeded'), ('PART_HEARD', 'Part Heard'), ('CONCLUDED', 'Concluded'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('court_station', models.CharField(blank=True, default='', max_length=255)),
                ('courtroom', models.CharField(blank=True, default='', max_length=100)),
                ('judicial_officer', models.CharField(blank=True, default='', max_length=255)),
                ('cause_list_position', models.CharField(blank=True, default='', max_length=50)),
                ('adjournment_reason', models.TextField(blank=True, default='')),
                ('outcome', models.TextField(blank=True, default='')),
                ('next_action', models.CharField(blank=True, default='', max_length=255)),
                ('next_date', models.DateTimeField(blank=True, null=True)),
                ('is_client_visible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'case_events',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseFiling',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filing_type', models.CharField(choices=[('PLAINT', 'Plaint'), ('DEFENCE', 'Defence'), ('PETITION', 'Petition'), ('NOTICE_OF_MOTION', 'Notice of Motion'), ('CHAMBER_SUMMONS', 'Chamber Summons'), ('APPLICATION', 'Application'), ('AFFIDAVIT', 'Affidavit'), ('REPLYING_AFFIDAVIT', 'Replying Affidavit'), ('FURTHER_AFFIDAVIT', 'Further Affidavit'), ('WITNESS_STATEMENT', 'Witness Statement'), ('LIST_OF_DOCUMENTS', 'List of Documents'), ('SUBMISSIONS', 'Submissions'), ('MEMORANDUM_OF_APPEAL', 'Memorandum of Appeal'), ('RECORD_OF_APPEAL', 'Record of Appeal'), ('NOTICE_OF_APPEAL', 'Notice of Appeal'), ('DEMAND_LETTER', 'Demand Letter'), ('CONSENT', 'Consent'), ('ORDER', 'Court Order'), ('DECREE', 'Decree'), ('RULING', 'Ruling'), ('JUDGMENT', 'Judgment'), ('AFFIDAVIT_OF_SERVICE', 'Affidavit of Service'), ('OTHER', 'Other')], max_length=60)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY_FOR_FILING', 'Ready for Filing'), ('FILED', 'Filed'), ('SERVED', 'Served'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('efiling_reference', models.CharField(blank=True, default='', max_length=120)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=120)),
                ('receipt_number', models.CharField(blank=True, default='', max_length=120)),
                ('is_client_visible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'case_filings',
                'ordering': ['-filed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('INTERNAL', 'Internal Note'), ('CLIENT_UPDATE', 'Client Update'), ('COURT_ATTENDANCE', 'Court Attendance Note'), ('REGISTRY', 'Registry Note'), ('STRATEGY', 'Strategy Note'), ('BILLING', 'Billing Note'), ('OTHER', 'Other')], default='INTERNAL', max_length=30)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField()),
                ('is_client_visible', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'case_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseParty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('party_role', models.CharField(choices=[('PLAINTIFF', 'Plaintiff'), ('DEFENDANT', 'Defendant'), ('PETITIONER', 'Petitioner'), ('RESPONDENT', 'Respondent'), ('APPLICANT', 'Applicant'), ('APPELLANT', 'Appellant'), ('ACCUSED', 'Accused'), ('COMPLAINANT', 'Complainant'), ('VICTIM', 'Victim'), ('CLAIMANT', 'Claimant'), ('OBJECTOR', 'Objector'), ('INTERESTED_PARTY', 'Interested Party'), ('AMICUS_CURIAE', 'Amicus Curiae'), ('BENEFICIARY', 'Beneficiary'), ('EXECUTOR', 'Executor'), ('ADMINISTRATOR', 'Administrator'), ('DECEASED', 'Deceased'), ('LANDLORD', 'Landlord'), ('TENANT', 'Tenant'), ('TAXPAYER', 'Taxpayer'), ('COMMISSIONER', 'Commissioner'), ('ADVOCATE_ON_RECORD', 'Advocate on Record'), ('OTHER', 'Other')], max_length=40)),
                ('party_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANISATION', 'Organisation'), ('GOVERNMENT', 'Government Entity'), ('ESTATE', 'Estate'), ('MINOR', 'Minor'), ('OTHER', 'Other')], default='INDIVIDUAL', max_length=30)),
                ('is_our_client', models.BooleanField(default=False)),
                ('party_order', models.PositiveIntegerField(default=1)),
                ('advocate_on_record', models.CharField(blank=True, default='', max_length=255)),
                ('law_firm', models.CharField(blank=True, default='', max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('national_id', models.CharField(blank=True, default='', max_length=50)),
                ('kra_pin', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'case_parties',
                'ordering': ['party_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('task_type', models.CharField(choices=[('LIMITATION', 'Limitation Deadline'), ('FILING_DEADLINE', 'Filing Deadline'), ('SERVICE_DEADLINE', 'Service Deadline'), ('SUBMISSIONS_DEADLINE', 'Submissions Deadline'), ('APPEAL_DEADLINE', 'Appeal Deadline'), ('COURT_ATTENDANCE', 'Court Attendance'), ('CLIENT_FOLLOW_UP', 'Client Follow-Up'), ('REGISTRY_FOLLOW_UP', 'Registry Follow-Up'), ('DOCUMENT_PREPARATION', 'Document Preparation'), ('BILLING', 'Billing'), ('OTHER', 'Other')], default='OTHER', max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=30)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_client_visible', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'case_tasks',
                'ordering': ['due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseTimeline',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'case_timeline',
                'ordering': ['-created_at'],
            },
        ),
    ]
