# Generated by Django 6.0.5 on 2026-07-16 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_initial'),
        ('clients', '0001_initial'),
        ('firm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='firm.lawfirm'),
        ),
        migrations.AddField(
            model_name='caseactivity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseactivity',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cases.case'),
        ),
        migrations.AddField(
            model_name='caseattachment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.case'),
        ),
        migrations.AddField(
            model_name='caseattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_case_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casecourtroom',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courtroom_history', to='cases.case'),
        ),
        migrations.AddField(
            model_name='casecourtroom',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_courtroom_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case'),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_case_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casefiling',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filings', to='cases.case'),
        ),
        migrations.AddField(
            model_name='casefiling',
            name='filed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_filings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseattachment',
            name='filing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='cases.casefiling'),
        ),
        migrations.AddField(
            model_name='casenote',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cases.case'),
        ),
        migrations.AddField(
            model_name='casenote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseparty',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='cases.case'),
        ),
        migrations.AddField(
            model_name='caseparty',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_party_roles', to='clients.client'),
        ),
        migrations.AddField(
            model_name='casetask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_case_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casetask',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cases.case'),
        ),
        migrations.AddField(
            model_name='casetask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_case_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casetimeline',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='cases.case'),
        ),
        migrations.AddField(
            model_name='casetimeline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_timeline_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['firm', 'status'], name='cases_firm_id_ba54de_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['firm', 'priority'], name='cases_firm_id_cdaf61_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['firm', 'case_type'], name='cases_firm_id_66e436_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['firm', 'procedure_track'], name='cases_firm_id_81ad5e_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['firm', 'court_type'], name='cases_firm_id_ba7317_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['firm', 'next_court_date'], name='cases_firm_id_d60beb_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['client'], name='cases_client__260b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['assigned_lawyer'], name='cases_assigne_e69e63_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['assigned_secretary'], name='cases_assigne_61e740_idx'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('firm', 'case_number'), name='unique_case_number_per_firm'),
        ),
        migrations.AddIndex(
            model_name='casecourtroom',
            index=models.Index(fields=['case', 'court_station'], name='case_courtr_case_id_eb0c48_idx'),
        ),
        migrations.AddIndex(
            model_name='casecourtroom',
            index=models.Index(fields=['judicial_officer'], name='case_courtr_judicia_f76eff_idx'),
        ),
        migrations.AddIndex(
            model_name='caseevent',
            index=models.Index(fields=['case', 'starts_at'], name='case_events_case_id_bb6bde_idx'),
        ),
        migrations.AddIndex(
            model_name='caseevent',
            index=models.Index(fields=['event_type'], name='case_events_event_t_230e06_idx'),
        ),
        migrations.AddIndex(
            model_name='caseevent',
            index=models.Index(fields=['status'], name='case_events_status_c4ec55_idx'),
        ),
        migrations.AddIndex(
            model_name='caseevent',
            index=models.Index(fields=['is_client_visible'], name='case_events_is_clie_c5e66c_idx'),
        ),
        migrations.AddIndex(
            model_name='casefiling',
            index=models.Index(fields=['case', 'filing_type'], name='case_filing_case_id_2c26f5_idx'),
        ),
        migrations.AddIndex(
            model_name='casefiling',
            index=models.Index(fields=['status'], name='case_filing_status_cdb613_idx'),
        ),
        migrations.AddIndex(
            model_name='casefiling',
            index=models.Index(fields=['efiling_reference'], name='case_filing_efiling_57dd5d_idx'),
        ),
        migrations.AddIndex(
            model_name='casefiling',
            index=models.Index(fields=['is_client_visible'], name='case_filing_is_clie_6a1d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='caseattachment',
            index=models.Index(fields=['case', 'attachment_type'], name='case_attach_case_id_103b75_idx'),
        ),
        migrations.AddIndex(
            model_name='caseattachment',
            index=models.Index(fields=['filing'], name='case_attach_filing__e2b16b_idx'),
        ),
        migrations.AddIndex(
            model_name='caseattachment',
            index=models.Index(fields=['is_client_visible'], name='case_attach_is_clie_620f1e_idx'),
        ),
        migrations.AddIndex(
            model_name='casenote',
            index=models.Index(fields=['case', 'note_type'], name='case_notes_case_id_277652_idx'),
        ),
        migrations.AddIndex(
            model_name='casenote',
            index=models.Index(fields=['is_client_visible'], name='case_notes_is_clie_fe0ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='caseparty',
            index=models.Index(fields=['case', 'party_role'], name='case_partie_case_id_93127a_idx'),
        ),
        migrations.AddIndex(
            model_name='caseparty',
            index=models.Index(fields=['client'], name='case_partie_client__7e0827_idx'),
        ),
        migrations.AddIndex(
            model_name='caseparty',
            index=models.Index(fields=['is_our_client'], name='case_partie_is_our__36dd68_idx'),
        ),
        migrations.AddIndex(
            model_name='casetask',
            index=models.Index(fields=['case', 'status'], name='case_tasks_case_id_0e93fe_idx'),
        ),
        migrations.AddIndex(
            model_name='casetask',
            index=models.Index(fields=['assigned_to', 'status'], name='case_tasks_assigne_3432a0_idx'),
        ),
        migrations.AddIndex(
            model_name='casetask',
            index=models.Index(fields=['due_at'], name='case_tasks_due_at_d8c0f0_idx'),
        ),
        migrations.AddIndex(
            model_name='casetask',
            index=models.Index(fields=['task_type'], name='case_tasks_task_ty_fc7faf_idx'),
        ),
    ]
