# Generated by Codex on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseevent",
            name="virtual_courtroom_url",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="caseevent",
            name="virtual_courtroom_label",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="caseevent",
            name="virtual_courtroom_available_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="caseevent",
            name="virtual_courtroom_available_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="caseevent",
            name="is_virtual_courtroom_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="caseevent",
            index=models.Index(
                fields=["is_virtual_courtroom_enabled", "starts_at"],
                name="case_events_is_virt_3d4a2b_idx",
            ),
        ),
    ]
