# Generated by Django 6.0.5 on 2026-07-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_caseevent_virtual_courtroom'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='caseevent',
            new_name='case_events_is_virt_46cf81_idx',
            old_name='case_events_is_virt_3d4a2b_idx',
        ),
    ]
