# Generated by Django 6.0.5 on 2026-07-16 19:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_lifecycle_dimensions(apps, schema_editor):
    Case = apps.get_model("cases", "Case")
    CaseTimeline = apps.get_model("cases", "CaseTimeline")
    CaseLifecycleTransition = apps.get_model("cases", "CaseLifecycleTransition")

    filed_statuses = {
        "FILED",
        "SERVICE_PENDING",
        "SERVED",
        "AWAITING_RESPONSE",
        "MENTION",
        "DIRECTIONS",
        "PRE_TRIAL",
        "HEARING",
        "SUBMISSIONS",
        "AWAITING_RULING",
        "AWAITING_JUDGMENT",
        "JUDGMENT_DELIVERED",
        "DECREE_EXTRACTION",
        "EXECUTION",
        "APPEAL_WINDOW",
        "NOTICE_OF_APPEAL_FILED",
        "ON_APPEAL",
        "APPEAL_DECIDED",
        "CLOSED",
        "ARCHIVED",
    }
    court_stage_by_status = {
        "PENDING": "NOT_FILED",
        "PENDING_FILING": "READY_FOR_FILING",
        "FILED": "FILED",
        "SERVICE_PENDING": "AWAITING_SERVICE",
        "SERVED": "AWAITING_RESPONSE",
        "AWAITING_RESPONSE": "AWAITING_RESPONSE",
        "MENTION": "CASE_MANAGEMENT",
        "DIRECTIONS": "CASE_MANAGEMENT",
        "PRE_TRIAL": "PRE_TRIAL",
        "HEARING": "HEARING_IN_PROGRESS",
        "SUBMISSIONS": "SUBMISSIONS",
        "AWAITING_RULING": "SUBMISSIONS",
        "AWAITING_JUDGMENT": "JUDGMENT_RESERVED",
        "JUDGMENT_DELIVERED": "JUDGMENT_DELIVERED",
        "DECREE_EXTRACTION": "DECREE_EXTRACTION",
        "EXECUTION": "EXECUTION",
        "ON_APPEAL": "APPEAL_OR_REVIEW",
        "APPEAL_DECIDED": "CONCLUDED",
        "CLOSED": "CONCLUDED",
        "ARCHIVED": "CONCLUDED",
    }
    matter_status_by_status = {
        "ON_HOLD": "ON_HOLD",
        "SETTLED": "SETTLEMENT_IN_PROGRESS",
        "WITHDRAWN": "CLOSED",
        "DISMISSED": "CLOSED",
        "CLOSED": "CLOSED",
        "ARCHIVED": "ARCHIVED",
    }

    for case in Case.objects.all():
        has_filing_evidence = bool(
            case.filing_date
            or case.efiling_reference
            or case.cts_reference
            or case.payment_reference
        )
        matter_status = matter_status_by_status.get(case.status, "INSTRUCTIONS_RECEIVED")
        court_stage = court_stage_by_status.get(case.status, "NOT_FILED")
        if has_filing_evidence and court_stage == "NOT_FILED":
            court_stage = "FILED"
        if case.status in filed_statuses and court_stage == "NOT_FILED":
            court_stage = "FILED"

        outcome_status = "PENDING"
        if case.status == "SETTLED":
            outcome_status = "SETTLED"
        elif case.status == "WITHDRAWN":
            outcome_status = "WITHDRAWN"
        elif case.status == "DISMISSED":
            outcome_status = "DISMISSED"

        enforcement_status = "NOT_APPLICABLE"
        if case.status in {"DECREE_EXTRACTION", "EXECUTION"}:
            enforcement_status = "NOT_STARTED"

        appeal_status = "NONE"
        if case.status == "NOTICE_OF_APPEAL_FILED":
            appeal_status = "APPEAL_FILED"
        elif case.status == "ON_APPEAL":
            appeal_status = "APPEAL_PENDING"
        elif case.status == "APPEAL_DECIDED":
            appeal_status = "APPEAL_DETERMINED"

        Case.objects.filter(pk=case.pk).update(
            matter_status=matter_status,
            court_stage=court_stage,
            outcome_status=outcome_status,
            enforcement_status=enforcement_status,
            appeal_status=appeal_status,
        )
        CaseLifecycleTransition.objects.get_or_create(
            case_id=case.pk,
            dimension="MATTER_STATUS",
            to_state=matter_status,
            defaults={
                "from_state": "",
                "effective_at": case.created_at,
                "actor_id": case.created_by_id,
                "reason": "Initial lifecycle state populated during lifecycle migration.",
                "metadata": {"source": "migration_0006", "legacy_status": case.status},
            },
        )
        CaseTimeline.objects.get_or_create(
            case_id=case.pk,
            action="Instructions Received",
            defaults={
                "description": "Initial client instructions were confirmed during lifecycle migration.",
                "created_by_id": case.created_by_id,
            },
        )

def reverse_lifecycle_population(apps, schema_editor):
    CaseLifecycleTransition = apps.get_model("cases", "CaseLifecycleTransition")
    CaseLifecycleTransition.objects.filter(metadata__source="migration_0006").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_rename_case_events_is_virt_3d4a2b_idx_case_events_is_virt_46cf81_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='appeal_status',
            field=models.CharField(choices=[('NONE', 'None'), ('UNDER_CONSIDERATION', 'Under consideration'), ('REVIEW_FILED', 'Review filed'), ('APPEAL_FILED', 'Appeal filed'), ('STAY_REQUESTED', 'Stay requested'), ('STAY_GRANTED', 'Stay granted'), ('STAY_DENIED', 'Stay denied'), ('APPEAL_PENDING', 'Appeal pending'), ('APPEAL_DETERMINED', 'Appeal determined')], db_index=True, default='NONE', max_length=40),
        ),
        migrations.AddField(
            model_name='case',
            name='assessment_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='case',
            name='claim_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='court_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='court_level',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='case',
            name='court_stage',
            field=models.CharField(choices=[('NOT_FILED', 'Not filed'), ('READY_FOR_FILING', 'Ready for filing'), ('FILED', 'Filed'), ('AWAITING_ASSESSMENT_OR_PAYMENT', 'Awaiting assessment or payment'), ('AWAITING_SERVICE', 'Awaiting service'), ('SERVICE_IN_PROGRESS', 'Service in progress'), ('AWAITING_RESPONSE', 'Awaiting response'), ('PLEADINGS_OPEN', 'Pleadings open'), ('PLEADINGS_CLOSED', 'Pleadings closed'), ('CASE_MANAGEMENT', 'Case management'), ('PRE_TRIAL', 'Pre-trial'), ('AWAITING_HEARING', 'Awaiting hearing'), ('HEARING_IN_PROGRESS', 'Hearing in progress'), ('SUBMISSIONS', 'Submissions'), ('JUDGMENT_RESERVED', 'Judgment reserved'), ('JUDGMENT_DELIVERED', 'Judgment delivered'), ('DECREE_EXTRACTION', 'Decree extraction'), ('EXECUTION', 'Execution'), ('APPEAL_OR_REVIEW', 'Appeal or review'), ('CONCLUDED', 'Concluded')], db_index=True, default='NOT_FILED', max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='currency',
            field=models.CharField(blank=True, default='KES', max_length=3),
        ),
        migrations.AddField(
            model_name='case',
            name='enforcement_status',
            field=models.CharField(choices=[('NOT_APPLICABLE', 'Not applicable'), ('NOT_STARTED', 'Not started'), ('DECREE_PENDING', 'Decree pending'), ('DECREE_ISSUED', 'Decree issued'), ('DEMAND_FOR_COMPLIANCE', 'Demand for compliance'), ('PART_PAYMENT', 'Part payment'), ('SATISFIED', 'Satisfied'), ('EXECUTION_IN_PROGRESS', 'Execution in progress'), ('STAYED', 'Stayed'), ('UNSUCCESSFUL', 'Unsuccessful'), ('CLOSED', 'Closed')], db_index=True, default='NOT_APPLICABLE', max_length=40),
        ),
        migrations.AddField(
            model_name='case',
            name='filed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='judicial_officer_rank',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='case',
            name='jurisdiction_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='case',
            name='jurisdiction_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='jurisdiction_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='jurisdiction_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurisdiction_verified_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='matter_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('INSTRUCTIONS_RECEIVED', 'Instructions received'), ('CONFLICT_CHECK_PENDING', 'Conflict check pending'), ('CONFLICT_CLEARED', 'Conflict cleared'), ('CONFLICT_IDENTIFIED', 'Conflict identified'), ('ENGAGEMENT_PENDING', 'Engagement pending'), ('ENGAGEMENT_CONFIRMED', 'Engagement confirmed'), ('MATTER_OPEN', 'Matter open'), ('ON_HOLD', 'On hold'), ('SETTLEMENT_IN_PROGRESS', 'Settlement in progress'), ('CLOSURE_PENDING', 'Closure pending'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived'), ('CANCELLED', 'Cancelled')], db_index=True, default='INSTRUCTIONS_RECEIVED', max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='official_court_case_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='case',
            name='outcome_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('PARTLY_WON', 'Partly won'), ('LOST', 'Lost'), ('SETTLED', 'Settled'), ('WITHDRAWN', 'Withdrawn'), ('STRUCK_OUT', 'Struck out'), ('DISMISSED', 'Dismissed'), ('CONSENT_RECORDED', 'Consent recorded'), ('ABATED', 'Abated'), ('OTHER', 'Other')], db_index=True, default='PENDING', max_length=40),
        ),
        migrations.AddField(
            model_name='case',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_case_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='court',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='court_stage_after',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='court_stage_before',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='event_subtype',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='hearing_mode',
            field=models.CharField(choices=[('VIRTUAL', 'Virtual'), ('PHYSICAL', 'Physical'), ('HYBRID', 'Hybrid'), ('NOT_APPLICABLE', 'Not applicable')], default='VIRTUAL', max_length=30),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='matter_status_after',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='matter_status_before',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='orders_directions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='physical_venue',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='virtual_access_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='virtual_meeting_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='case',
            name='procedure_track',
            field=models.CharField(blank=True, choices=[('CIVIL_SUIT', 'Civil Suit'), ('COMMERCIAL_PETITION', 'Commercial Petition'), ('CONSTITUTIONAL_PETITION', 'Constitutional Petition'), ('MISC_APPLICATION', 'Miscellaneous Application'), ('PETITION', 'Petition'), ('JUDICIAL_REVIEW', 'Judicial Review'), ('APPEAL', 'Appeal'), ('CRIMINAL_CASE', 'Criminal Case'), ('CRIMINAL_TRIAL', 'Criminal Trial'), ('CRIMINAL_APPEAL', 'Criminal Appeal'), ('SUCCESSION_CAUSE', 'Succession Cause'), ('FAMILY_CAUSE', 'Family Cause'), ('CHILDREN_MATTER', 'Children Matter'), ('EMPLOYMENT_CLAIM', 'Employment Claim'), ('ELC_SUIT', 'Environment and Land Suit'), ('SMALL_CLAIM', 'Small Claim'), ('TRIBUNAL_MATTER', 'Tribunal Matter'), ('ARBITRATION', 'Arbitration'), ('MEDIATION', 'Mediation'), ('ADR', 'Alternative Dispute Resolution'), ('NON_CONTENTIOUS', 'Non-Contentious Matter')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='event_type',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('FILING', 'Filing'), ('SERVICE', 'Service'), ('MENTION', 'Mention'), ('CASE_MANAGEMENT', 'Case Management'), ('HEARING', 'Hearing'), ('DIRECTIONS', 'Directions'), ('PRE_TRIAL', 'Pre-Trial Conference'), ('SETTLEMENT', 'Settlement'), ('ADR', 'Alternative Dispute Resolution'), ('MEDIATION', 'Mediation'), ('SUBMISSIONS', 'Submissions'), ('RULING', 'Ruling'), ('JUDGMENT', 'Judgment'), ('APPEAL', 'Appeal'), ('REVIEW', 'Review'), ('ADMINISTRATIVE', 'Administrative'), ('TAXATION', 'Taxation'), ('EXECUTION', 'Execution'), ('REGISTRY_ACTION', 'Registry Action'), ('CLIENT_MEETING', 'Client Meeting'), ('OTHER', 'Other')], max_length=40),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('ADJOURNED', 'Adjourned'), ('VACATED', 'Vacated'), ('MISSED', 'Missed'), ('TAKEN_OUT', 'Taken Out'), ('PROCEEDED', 'Proceeded'), ('PART_HEARD', 'Part Heard'), ('CONCLUDED', 'Concluded'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=30),
        ),
        migrations.CreateModel(
            name='CaseLifecycleTransition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension', models.CharField(choices=[('MATTER_STATUS', 'Matter status'), ('COURT_STAGE', 'Court stage'), ('OUTCOME_STATUS', 'Outcome status'), ('ENFORCEMENT_STATUS', 'Enforcement status'), ('APPEAL_STATUS', 'Appeal or review status')], max_length=40)),
                ('from_state', models.CharField(blank=True, default='', max_length=60)),
                ('to_state', models.CharField(max_length=60)),
                ('effective_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_correction', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_lifecycle_transitions', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_transitions', to='cases.case')),
                ('correction_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='cases.caselifecycletransition')),
                ('source_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lifecycle_transitions', to='cases.caseevent')),
            ],
            options={
                'db_table': 'case_lifecycle_transitions',
                'ordering': ['effective_at', 'recorded_at'],
                'indexes': [models.Index(fields=['case', 'dimension', 'effective_at'], name='case_lifecy_case_id_0ab17b_idx'), models.Index(fields=['dimension', 'to_state'], name='case_lifecy_dimensi_2b6f3a_idx')],
            },
        ),
        migrations.RunPython(populate_lifecycle_dimensions, reverse_lifecycle_population),
    ]
