# Generated by Django 6.0.5 on 2026-07-16 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_appeal_status_case_assessment_reference_and_more'),
        ('firm', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('PENDING_FILING', 'Pending Filing'), ('FILED', 'Filed in Court'), ('SERVICE_PENDING', 'Service Pending'), ('SERVED', 'Served'), ('AWAITING_RESPONSE', 'Awaiting Response'), ('MENTION', 'Mention'), ('DIRECTIONS', 'Directions'), ('PRE_TRIAL', 'Pre-Trial'), ('MEDIATION', 'Mediation'), ('HEARING', 'Hearing'), ('SUBMISSIONS', 'Submissions'), ('AWAITING_RULING', 'Awaiting Ruling'), ('AWAITING_JUDGMENT', 'Awaiting Judgment'), ('JUDGMENT_DELIVERED', 'Judgment Delivered'), ('DECREE_EXTRACTION', 'Decree Extraction'), ('EXECUTION', 'Execution'), ('APPEAL_WINDOW', 'Appeal Window'), ('NOTICE_OF_APPEAL_FILED', 'Notice of Appeal Filed'), ('ON_APPEAL', 'On Appeal'), ('APPEAL_DECIDED', 'Appeal Decided'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('SETTLED', 'Settled'), ('WITHDRAWN', 'Withdrawn'), ('DISMISSED', 'Dismissed'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='PENDING', help_text='Deprecated compatibility field. Use matter_status, court_stage, outcome_status, enforcement_status and appeal_status for lifecycle logic.', max_length=40),
        ),
        migrations.CreateModel(
            name='CaseConflictCheck',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('PENDING', 'Pending'), ('CLEAR', 'Clear'), ('POTENTIAL_CONFLICT', 'Potential conflict'), ('CONFLICT_CONFIRMED', 'Conflict confirmed'), ('WAIVER_PENDING', 'Waiver pending'), ('WAIVED', 'Waived'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=40)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('search_scope', models.CharField(blank=True, default='', max_length=255)),
                ('searched_names', models.JSONField(blank=True, default=list)),
                ('searched_entities', models.JSONField(blank=True, default=list)),
                ('result_summary', models.TextField(blank=True, default='')),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('waiver_required', models.BooleanField(default=False)),
                ('waiver_obtained', models.BooleanField(default=False)),
                ('waiver_details', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_conflict_checks', to=settings.AUTH_USER_MODEL)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_check', to='cases.case')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_conflict_checks', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_conflict_checks', to='firm.lawfirm')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_conflict_checks', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_conflict_checks', to=settings.AUTH_USER_MODEL)),
                ('supporting_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflict_checks', to='cases.caseattachment')),
            ],
            options={
                'db_table': 'case_conflict_checks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='case_confli_status_0fece4_idx'), models.Index(fields=['reference_number'], name='case_confli_referen_ebcf9e_idx')],
                'constraints': [models.UniqueConstraint(fields=('case',), name='unique_conflict_check_per_case'), models.UniqueConstraint(fields=('firm', 'reference_number'), name='unique_conflict_reference_per_firm')],
            },
        ),
    ]
