# Generated by Django 6.0.5 on 2026-07-17 08:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_case_status_caseconflictcheck'),
        ('clients', '0004_alter_companyclient_options_and_more'),
        ('firm', '0002_initial'),
        ('staff', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(condition=models.Q(('official_court_case_number', ''), _negated=True), fields=('firm', 'official_court_case_number'), name='unique_official_court_case_number_per_firm'),
        ),
    ]
