# Generated by Django 6.0.5 on 2026-07-18 08:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_universal_matter_data(apps, schema_editor):
    Case = apps.get_model("cases", "Case")
    CaseParty = apps.get_model("cases", "CaseParty")
    CourtProceeding = apps.get_model("cases", "CourtProceeding")
    MonetaryRelief = apps.get_model("cases", "MonetaryRelief")
    ConflictRecordAtRegistration = apps.get_model("cases", "ConflictRecordAtRegistration")

    practice_area_by_case_type = {
        "LAND": "LAND_ENVIRONMENT",
        "EMPLOYMENT": "EMPLOYMENT_LABOUR",
        "SUCCESSION": "SUCCESSION_PROBATE",
        "CRIMINAL": "CRIMINAL_LITIGATION",
        "CONSTITUTIONAL": "CONSTITUTIONAL_HUMAN_RIGHTS",
        "JUDICIAL_REVIEW": "JUDICIAL_REVIEW",
        "TAX": "TAX",
        "ARBITRATION": "ARBITRATION_MEDIATION",
        "MEDIATION": "ARBITRATION_MEDIATION",
        "TRIBUNAL": "TRIBUNAL_PROCEEDINGS",
        "DEBT_RECOVERY": "DEBT_RECOVERY",
        "CONVEYANCING": "CONVEYANCING",
        "COMMERCIAL": "CIVIL_COMMERCIAL_LITIGATION",
        "CIVIL": "CIVIL_COMMERCIAL_LITIGATION",
    }

    for case in Case.objects.all().iterator():
        has_court_reference = bool(case.official_court_case_number or case.filing_date or case.efiling_reference)
        if case.case_type == "TRIBUNAL" or case.procedure_track == "TRIBUNAL_MATTER":
            case.forum = "TRIBUNAL"
            case.entry_route = "EXISTING_TRIBUNAL_MATTER"
            case.court_stage = "NOT_APPLICABLE"
        elif case.case_type == "ARBITRATION" or case.procedure_track == "ARBITRATION":
            case.forum = "ARBITRATION"
            case.entry_route = "EXISTING_ARBITRATION"
            case.court_stage = "NOT_APPLICABLE"
        elif case.case_type in {"CONVEYANCING"} or case.procedure_track == "NON_CONTENTIOUS":
            case.forum = "NO_FORMAL_FORUM"
            case.entry_route = "NON_CONTENTIOUS_MATTER"
            case.court_stage = "NOT_APPLICABLE"
        else:
            case.forum = "COURT"
            case.entry_route = "EXISTING_FILED_COURT_CASE" if has_court_reference else "NEW_INSTRUCTION"

        case.practice_area = practice_area_by_case_type.get(case.case_type, "LEGACY")
        case.matter_nature = (
            "NON_CONTENTIOUS"
            if case.forum == "NO_FORMAL_FORUM"
            else "ALTERNATIVE_DISPUTE_RESOLUTION"
            if case.forum in {"ARBITRATION", "MEDIATION"}
            else "CONTENTIOUS"
        )
        case.procedure_type = case.procedure_track or ""
        if case.entry_route == "EXISTING_FILED_COURT_CASE" and case.court_stage == "NOT_FILED" and has_court_reference:
            case.court_stage = "FILED"
        case.conflict_status = "REQUIRES_VERIFICATION"
        case.save(
            update_fields=[
                "entry_route",
                "forum",
                "practice_area",
                "matter_nature",
                "procedure_type",
                "court_stage",
                "conflict_status",
            ]
        )

        if case.forum == "COURT" and not CourtProceeding.objects.filter(matter=case).exists():
            CourtProceeding.objects.create(
                matter=case,
                official_court_case_number=case.official_court_case_number or "",
                filing_date=case.filing_date,
                court_type=case.court_type or "",
                court_level=case.court_level or "",
                court_name=case.court_name or "",
                court_station=case.court_station or "",
                registry=case.registry or "",
                division=case.court_division or "",
                courtroom=case.courtroom or "",
                judicial_officer=case.judicial_officer or "",
                court_location=case.court_location or "",
                efiling_reference=case.efiling_reference or "",
                payment_reference=case.payment_reference or "",
                cts_reference=case.cts_reference or "",
                court_stage=case.court_stage or "",
                jurisdiction_verification_status="VERIFIED" if case.jurisdiction_verified else "PENDING",
                jurisdiction_notes=case.jurisdiction_notes or "",
            )

        if case.claim_amount is not None and not MonetaryRelief.objects.filter(matter=case).exists():
            MonetaryRelief.objects.create(
                matter=case,
                relief_type="QUANTIFIED",
                currency=case.currency or "KES",
                principal_amount=case.claim_amount,
            )

        if not ConflictRecordAtRegistration.objects.filter(matter=case).exists():
            ConflictRecordAtRegistration.objects.create(
                matter=case,
                status="REQUIRES_VERIFICATION",
                recorded_by=case.created_by,
                recorded_at=timezone.now(),
            )

        for party in CaseParty.objects.filter(case=case):
            if party.is_our_client:
                party.is_adverse = False
            elif party.party_role in {"DEFENDANT", "RESPONDENT", "OBJECTOR", "PROSECUTION"}:
                party.is_adverse = True
            if not party.individual_name and party.party_type in {"INDIVIDUAL", "MINOR"}:
                party.individual_name = party.name
            if not party.organization_name and party.party_type not in {"INDIVIDUAL", "MINOR"}:
                party.organization_name = party.name
            party.save(update_fields=["is_adverse", "individual_name", "organization_name"])


def noop_reverse(apps, schema_editor):
    # Staged migration: new related records are preserved for audit and compatibility.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_case_unique_official_court_case_number_per_firm'),
        ('clients', '0004_alter_companyclient_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='conflict_status',
            field=models.CharField(blank=True, default='REQUIRES_VERIFICATION', max_length=40),
        ),
        migrations.AddField(
            model_name='case',
            name='date_instructions_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='entry_route',
            field=models.CharField(choices=[('NEW_INSTRUCTION', 'New instruction - not yet filed'), ('EXISTING_FILED_COURT_CASE', 'Existing filed court case'), ('EXISTING_TRIBUNAL_MATTER', 'Existing tribunal matter'), ('EXISTING_ARBITRATION', 'Existing arbitration'), ('NON_CONTENTIOUS_MATTER', 'Non-contentious or advisory matter')], db_index=True, default='EXISTING_FILED_COURT_CASE', max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='forum',
            field=models.CharField(choices=[('NO_FORMAL_FORUM', 'No formal forum'), ('COURT', 'Court'), ('TRIBUNAL', 'Tribunal'), ('ARBITRATION', 'Arbitration'), ('MEDIATION', 'Mediation'), ('ADMINISTRATIVE_BODY', 'Administrative body')], db_index=True, default='COURT', max_length=40),
        ),
        migrations.AddField(
            model_name='case',
            name='internal_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='limitation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='matter_nature',
            field=models.CharField(choices=[('CONTENTIOUS', 'Contentious'), ('NON_CONTENTIOUS', 'Non-contentious'), ('ADVISORY', 'Advisory'), ('TRANSACTIONAL', 'Transactional'), ('REGULATORY', 'Regulatory'), ('DEBT_RECOVERY', 'Debt recovery'), ('ALTERNATIVE_DISPUTE_RESOLUTION', 'Alternative dispute resolution')], db_index=True, default='CONTENTIOUS', max_length=60),
        ),
        migrations.AddField(
            model_name='case',
            name='practice_area',
            field=models.CharField(choices=[('CIVIL_COMMERCIAL_LITIGATION', 'Civil and Commercial Litigation'), ('LAND_ENVIRONMENT', 'Land and Environment'), ('EMPLOYMENT_LABOUR', 'Employment and Labour'), ('FAMILY_LAW', 'Family Law'), ('SUCCESSION_PROBATE', 'Succession and Probate'), ('CRIMINAL_LITIGATION', 'Criminal Litigation'), ('CONSTITUTIONAL_HUMAN_RIGHTS', 'Constitutional and Human Rights'), ('JUDICIAL_REVIEW', 'Judicial Review'), ('INSURANCE', 'Insurance'), ('TAX', 'Tax'), ('INSOLVENCY', 'Insolvency'), ('INTELLECTUAL_PROPERTY', 'Intellectual Property'), ('PUBLIC_PROCUREMENT', 'Public Procurement'), ('CONVEYANCING', 'Conveyancing'), ('CORPORATE_COMMERCIAL', 'Corporate and Commercial'), ('ARBITRATION_MEDIATION', 'Arbitration and Mediation'), ('TRIBUNAL_PROCEEDINGS', 'Tribunal Proceedings'), ('DEBT_RECOVERY', 'Debt Recovery'), ('REGULATORY_COMPLIANCE', 'Regulatory and Compliance'), ('ADVISORY', 'Advisory'), ('LEGACY', 'Legacy / requires review')], db_index=True, default='LEGACY', max_length=80),
        ),
        migrations.AddField(
            model_name='case',
            name='procedure_type',
            field=models.CharField(blank=True, choices=[('CIVIL_SUIT', 'Civil Suit'), ('COMMERCIAL_PETITION', 'Commercial Petition'), ('CONSTITUTIONAL_PETITION', 'Constitutional Petition'), ('MISC_APPLICATION', 'Miscellaneous Application'), ('PETITION', 'Petition'), ('JUDICIAL_REVIEW', 'Judicial Review'), ('APPEAL', 'Appeal'), ('CRIMINAL_CASE', 'Criminal Case'), ('CRIMINAL_TRIAL', 'Criminal Trial'), ('CRIMINAL_APPEAL', 'Criminal Appeal'), ('SUCCESSION_CAUSE', 'Succession Cause'), ('FAMILY_CAUSE', 'Family Cause'), ('CHILDREN_MATTER', 'Children Matter'), ('EMPLOYMENT_CLAIM', 'Employment Claim'), ('ELC_SUIT', 'Environment and Land Suit'), ('SMALL_CLAIM', 'Small Claim'), ('TRIBUNAL_MATTER', 'Tribunal Matter'), ('ARBITRATION', 'Arbitration'), ('MEDIATION', 'Mediation'), ('ADR', 'Alternative Dispute Resolution'), ('NON_CONTENTIOUS', 'Non-Contentious Matter')], db_index=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='case',
            name='urgency_level',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='case',
            name='urgency_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='caseparty',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='caseparty',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='caseparty',
            name='individual_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='caseparty',
            name='is_adverse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caseparty',
            name='linked_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_party_roles', to='clients.clientcontact'),
        ),
        migrations.AddField(
            model_name='caseparty',
            name='organization_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='caseparty',
            name='representation_status',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='case',
            name='court_stage',
            field=models.CharField(choices=[('NOT_APPLICABLE', 'Not applicable'), ('NOT_FILED', 'Not filed'), ('READY_FOR_FILING', 'Ready for filing'), ('FILED', 'Filed'), ('AWAITING_ASSESSMENT_OR_PAYMENT', 'Awaiting assessment or payment'), ('AWAITING_SERVICE', 'Awaiting service'), ('SERVICE_IN_PROGRESS', 'Service in progress'), ('AWAITING_RESPONSE', 'Awaiting response'), ('PLEADINGS_OPEN', 'Pleadings open'), ('PLEADINGS_CLOSED', 'Pleadings closed'), ('CASE_MANAGEMENT', 'Case management'), ('PRE_TRIAL', 'Pre-trial'), ('AWAITING_HEARING', 'Awaiting hearing'), ('HEARING_IN_PROGRESS', 'Hearing in progress'), ('SUBMISSIONS', 'Submissions'), ('JUDGMENT_RESERVED', 'Judgment reserved'), ('JUDGMENT_DELIVERED', 'Judgment delivered'), ('DECREE_EXTRACTION', 'Decree extraction'), ('EXECUTION', 'Execution'), ('APPEAL_OR_REVIEW', 'Appeal or review'), ('CONCLUDED', 'Concluded')], db_index=True, default='NOT_FILED', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.CharField(blank=True, choices=[('MAGISTRATE', 'Magistrate Court'), ('HIGH_COURT', 'High Court'), ('COURT_OF_APPEAL', 'Court of Appeal'), ('SUPREME_COURT', 'Supreme Court'), ('ENVIRONMENT_LAND', 'Environment and Land Court'), ('EMPLOYMENT_LABOUR', 'Employment and Labour Court'), ('SMALL_CLAIMS', 'Small Claims Court'), ('KADHI', 'Kadhi Court'), ('COURT_MARTIAL', 'Court Martial'), ('TRIBUNAL', 'Tribunal'), ('ADR', 'Alternative Dispute Resolution'), ('OTHER', 'Other')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='case',
            name='matter_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('INSTRUCTIONS_RECEIVED', 'Instructions received'), ('CONFLICT_CHECK_PENDING', 'Conflict check pending'), ('CONFLICT_CLEARED', 'Conflict cleared'), ('CONFLICT_IDENTIFIED', 'Conflict identified'), ('ENGAGEMENT_PENDING', 'Engagement pending'), ('ENGAGEMENT_CONFIRMED', 'Engagement confirmed'), ('MATTER_OPEN', 'Matter open'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On hold'), ('SETTLEMENT_IN_PROGRESS', 'Settlement in progress'), ('CLOSURE_PENDING', 'Closure pending'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived'), ('CANCELLED', 'Cancelled')], db_index=True, default='INSTRUCTIONS_RECEIVED', max_length=50),
        ),
        migrations.AlterField(
            model_name='caseparty',
            name='party_role',
            field=models.CharField(choices=[('PLAINTIFF', 'Plaintiff'), ('DEFENDANT', 'Defendant'), ('PETITIONER', 'Petitioner'), ('RESPONDENT', 'Respondent'), ('APPLICANT', 'Applicant'), ('APPELLANT', 'Appellant'), ('ACCUSED', 'Accused'), ('COMPLAINANT', 'Complainant'), ('VICTIM', 'Victim'), ('CLAIMANT', 'Claimant'), ('OBJECTOR', 'Objector'), ('INTERESTED_PARTY', 'Interested Party'), ('THIRD_PARTY', 'Third Party'), ('EX_PARTE_APPLICANT', 'Ex Parte Applicant'), ('AMICUS_CURIAE', 'Amicus Curiae'), ('BENEFICIARY', 'Beneficiary'), ('EXECUTOR', 'Executor'), ('ADMINISTRATOR', 'Administrator'), ('PROTESTOR', 'Protestor'), ('DECEASED', 'Deceased'), ('DEPENDANT', 'Dependant'), ('PROSECUTION', 'Prosecution'), ('LANDLORD', 'Landlord'), ('TENANT', 'Tenant'), ('TAXPAYER', 'Taxpayer'), ('COMMISSIONER', 'Commissioner'), ('ADVOCATE_ON_RECORD', 'Advocate on Record'), ('OTHER', 'Other')], max_length=40),
        ),
        migrations.AlterField(
            model_name='caseparty',
            name='party_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company'), ('ORGANISATION', 'Organisation'), ('GOVERNMENT', 'Government Entity'), ('GOVERNMENT_ENTITY', 'Government Entity'), ('ESTATE', 'Estate'), ('TRUST', 'Trust'), ('ASSOCIATION', 'Association'), ('MINOR', 'Minor'), ('OTHER', 'Other')], default='INDIVIDUAL', max_length=30),
        ),
        migrations.CreateModel(
            name='ArbitrationProceeding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arbitration_reference', models.CharField(blank=True, default='', max_length=120)),
                ('arbitration_agreement', models.TextField(blank=True, default='')),
                ('institution', models.CharField(blank=True, default='', max_length=255)),
                ('seat', models.CharField(blank=True, default='', max_length=120)),
                ('rules', models.CharField(blank=True, default='', max_length=255)),
                ('arbitrator', models.CharField(blank=True, default='', max_length=255)),
                ('commencement_date', models.DateField(blank=True, null=True)),
                ('next_date', models.DateTimeField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, default='', max_length=255)),
                ('matter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arbitration_proceeding', to='cases.case')),
            ],
            options={
                'db_table': 'case_arbitration_proceedings',
            },
        ),
        migrations.CreateModel(
            name='ConflictRecordAtRegistration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOT_YET_RECORDED', 'Not yet recorded'), ('PREVIOUSLY_CLEARED', 'Previously cleared'), ('PREVIOUSLY_WAIVED', 'Previously waived'), ('REQUIRES_VERIFICATION', 'Requires verification')], default='REQUIRES_VERIFICATION', max_length=40)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('result_summary', models.TextField(blank=True, default='')),
                ('reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('matter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_record', to='cases.case')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_conflict_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'case_conflict_records_at_registration',
            },
        ),
        migrations.CreateModel(
            name='CriminalMatterDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accused_person', models.CharField(blank=True, default='', max_length=255)),
                ('charge', models.CharField(blank=True, default='', max_length=255)),
                ('statutory_provision', models.CharField(blank=True, default='', max_length=255)),
                ('plea', models.CharField(blank=True, default='', max_length=120)),
                ('arrest_date', models.DateField(blank=True, null=True)),
                ('police_station', models.CharField(blank=True, default='', max_length=255)),
                ('ob_number', models.CharField(blank=True, default='', max_length=120)),
                ('bond_bail_status', models.CharField(blank=True, default='', max_length=120)),
                ('bond_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('custody_status', models.CharField(blank=True, default='', max_length=120)),
                ('prosecution_agency', models.CharField(blank=True, default='', max_length=255)),
                ('matter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_details', to='cases.case')),
            ],
            options={
                'db_table': 'case_criminal_details',
            },
        ),
        migrations.CreateModel(
            name='EmploymentMatterDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer', models.CharField(blank=True, default='', max_length=255)),
                ('employee', models.CharField(blank=True, default='', max_length=255)),
                ('employment_start_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('employment_status', models.CharField(blank=True, default='', max_length=80)),
                ('nature_of_complaint', models.TextField(blank=True, default='')),
                ('dismissal_type', models.CharField(blank=True, default='', max_length=120)),
                ('disciplinary_process', models.TextField(blank=True, default='')),
                ('labour_officer_reference', models.CharField(blank=True, default='', max_length=120)),
                ('matter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_details', to='cases.case')),
            ],
            options={
                'db_table': 'case_employment_details',
            },
        ),
        migrations.CreateModel(
            name='InsuranceMatterDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insurer', models.CharField(blank=True, default='', max_length=255)),
                ('policy_number', models.CharField(blank=True, default='', max_length=120)),
                ('policy_type', models.CharField(blank=True, default='', max_length=120)),
                ('insured_party', models.CharField(blank=True, default='', max_length=255)),
                ('claim_number', models.CharField(blank=True, default='', max_length=120)),
                ('date_of_loss', models.DateField(blank=True, null=True)),
                ('cause_of_loss', models.TextField(blank=True, default='')),
                ('amount_claimed', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_admitted', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('outstanding_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('policy_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('repudiation_date', models.DateField(blank=True, null=True)),
                ('repudiation_reason', models.TextField(blank=True, default='')),
                ('matter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_details', to='cases.case')),
            ],
            options={
                'db_table': 'case_insurance_details',
            },
        ),
        migrations.CreateModel(
            name='LandMatterDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_description', models.TextField(blank=True, default='')),
                ('title_number', models.CharField(blank=True, default='', max_length=120)),
                ('parcel_number', models.CharField(blank=True, default='', max_length=120)),
                ('land_reference_number', models.CharField(blank=True, default='', max_length=120)),
                ('county', models.CharField(blank=True, default='', max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('registered_owner', models.CharField(blank=True, default='', max_length=255)),
                ('estimated_property_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('nature_of_land_interest', models.CharField(blank=True, default='', max_length=120)),
                ('possession_status', models.CharField(blank=True, default='', max_length=120)),
                ('boundary_dispute', models.BooleanField(default=False)),
                ('environment_issue', models.TextField(blank=True, default='')),
                ('orders_sought', models.TextField(blank=True, default='')),
                ('matter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='land_details', to='cases.case')),
            ],
            options={
                'db_table': 'case_land_details',
            },
        ),
        migrations.CreateModel(
            name='MonetaryRelief',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relief_type', models.CharField(choices=[('QUANTIFIED', 'Yes - quantified'), ('PARTLY_QUANTIFIED', 'Yes - partly quantified'), ('TO_BE_ASSESSED', 'Yes - amount to be assessed'), ('NO_MONETARY_RELIEF', 'No monetary relief'), ('VALUE_ONLY', 'Value only, not a claim')], default='NO_MONETARY_RELIEF', max_length=40)),
                ('currency', models.CharField(blank=True, default='KES', max_length=3)),
                ('principal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('special_damages', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('general_damages_status', models.CharField(blank=True, default='', max_length=80)),
                ('general_damages_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('interest_claimed', models.BooleanField(default=False)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('interest_basis', models.CharField(blank=True, default='', max_length=255)),
                ('costs_claimed', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_already_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('outstanding_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estimated_matter_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_to_be_assessed', models.BooleanField(default=False)),
                ('property_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('mesne_profits', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rent_arrears', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('damages', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('gross_estate_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('net_estate_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('disputed_asset_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_claimed', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_admitted', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('policy_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('general_damages', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('salary_arrears', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notice_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('leave_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('service_or_severance_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('compensation_months', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('other_contractual_benefits', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('future_medical_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('loss_of_earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('loss_of_earning_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('matter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monetary_relief', to='cases.case')),
            ],
            options={
                'db_table': 'case_monetary_relief',
            },
        ),
        migrations.CreateModel(
            name='NonContentiousMatterDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instruction_type', models.CharField(blank=True, default='', max_length=120)),
                ('deliverable', models.CharField(blank=True, default='', max_length=255)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('counterparty', models.CharField(blank=True, default='', max_length=255)),
                ('transaction_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('scope_of_work', models.TextField(blank=True, default='')),
                ('matter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='non_contentious_details', to='cases.case')),
            ],
            options={
                'db_table': 'case_non_contentious_details',
            },
        ),
        migrations.CreateModel(
            name='SuccessionMatterDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deceased_full_name', models.CharField(blank=True, default='', max_length=255)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('place_of_death', models.CharField(blank=True, default='', max_length=255)),
                ('testate_status', models.CharField(blank=True, default='', max_length=40)),
                ('will_date', models.DateField(blank=True, null=True)),
                ('estimated_gross_estate_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('known_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estimated_net_estate_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('disputed_asset_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('grant_type', models.CharField(blank=True, default='', max_length=120)),
                ('proposed_administrator', models.CharField(blank=True, default='', max_length=255)),
                ('matter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='succession_details', to='cases.case')),
            ],
            options={
                'db_table': 'case_succession_details',
            },
        ),
        migrations.CreateModel(
            name='TribunalProceeding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tribunal_name', models.CharField(max_length=255)),
                ('tribunal_reference', models.CharField(blank=True, default='', max_length=120)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('registry_or_location', models.CharField(blank=True, default='', max_length=255)),
                ('panel_or_adjudicator', models.CharField(blank=True, default='', max_length=255)),
                ('next_date', models.DateTimeField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, default='', max_length=255)),
                ('matter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tribunal_proceeding', to='cases.case')),
            ],
            options={
                'db_table': 'case_tribunal_proceedings',
            },
        ),
        migrations.CreateModel(
            name='CourtProceeding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('official_court_case_number', models.CharField(blank=True, default='', max_length=120)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('court_type', models.CharField(blank=True, default='', max_length=40)),
                ('court_level', models.CharField(blank=True, default='', max_length=80)),
                ('court_name', models.CharField(blank=True, default='', max_length=255)),
                ('court_station', models.CharField(blank=True, default='', max_length=255)),
                ('registry', models.CharField(blank=True, default='', max_length=255)),
                ('division', models.CharField(blank=True, default='', max_length=60)),
                ('courtroom', models.CharField(blank=True, default='', max_length=100)),
                ('judicial_officer', models.CharField(blank=True, default='', max_length=255)),
                ('court_location', models.CharField(blank=True, default='', max_length=255)),
                ('efiling_reference', models.CharField(blank=True, default='', max_length=120)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=120)),
                ('cts_reference', models.CharField(blank=True, default='', max_length=120)),
                ('court_stage', models.CharField(blank=True, default='', max_length=50)),
                ('jurisdiction_verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('WARNING_OVERRIDDEN', 'Warning overridden'), ('REQUIRES_REVIEW', 'Requires review')], default='PENDING', max_length=40)),
                ('jurisdiction_notes', models.TextField(blank=True, default='')),
                ('matter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='court_proceeding', to='cases.case')),
            ],
            options={
                'db_table': 'case_court_proceedings',
                'indexes': [models.Index(fields=['court_type'], name='case_court__court_t_a8c3d1_idx'), models.Index(fields=['official_court_case_number'], name='case_court__officia_bc0838_idx')],
            },
        ),
        migrations.RunPython(backfill_universal_matter_data, noop_reverse),
    ]
