# Generated by Django 6.0.5 on 2026-07-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_case_conflict_status_case_date_instructions_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='accepted_instruction_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='case',
            name='court_type',
            field=models.CharField(blank=True, choices=[('MAGISTRATE', 'Magistrate Court'), ('HIGH_COURT', 'High Court'), ('COURT_OF_APPEAL', 'Court of Appeal'), ('SUPREME_COURT', 'Supreme Court'), ('ENVIRONMENT_LAND', 'Environment and Land Court'), ('EMPLOYMENT_LABOUR', 'Employment and Labour Court'), ('SMALL_CLAIMS', 'Small Claims Court'), ('KADHI', 'Kadhi Court'), ('COURT_MARTIAL', 'Court Martial'), ('ADR', 'Alternative Dispute Resolution'), ('OTHER', 'Other')], default='', max_length=40),
        ),
    ]
