# Generated by Django 6.0.5 on 2026-07-24 00:43

from django.db import migrations, models


def backfill_existing_filed_matter_state(apps, schema_editor):
    Case = apps.get_model('cases', 'Case')
    for case in Case.objects.filter(entry_route='EXISTING_FILED_COURT_CASE', matter_status='ACTIVE'):
        case.matter_status = 'MATTER_OPEN'
        case.save(update_fields=['matter_status', 'updated_at'])


def reverse_backfill_existing_filed_matter_state(apps, schema_editor):
    Case = apps.get_model('cases', 'Case')
    for case in Case.objects.filter(entry_route='EXISTING_FILED_COURT_CASE', matter_status='MATTER_OPEN'):
        case.matter_status = 'ACTIVE'
        case.save(update_fields=['matter_status', 'updated_at'])


def sync_court_proceeding_compatibility_fields(apps, schema_editor):
    Case = apps.get_model('cases', 'Case')
    CourtProceeding = apps.get_model('cases', 'CourtProceeding')
    for proceeding in CourtProceeding.objects.select_related('matter').all():
        case = proceeding.matter
        updates = []
        for field in ['assessment_reference', 'court_fee_amount', 'payment_date']:
            case_value = getattr(case, field, None)
            proceeding_value = getattr(proceeding, field, None)
            value = proceeding_value or case_value
            if value not in (None, '') and proceeding_value != value:
                setattr(proceeding, field, value)
                updates.append(field)
        if updates:
            proceeding.save(update_fields=[*updates, 'updated_at'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_separate_legacy_internal_matter_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefiling',
            name='assessment_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='casefiling',
            name='court_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='casefiling',
            name='official_court_case_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='casefiling',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casefiling',
            name='source',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='courtproceeding',
            name='assessment_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='courtproceeding',
            name='court_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='courtproceeding',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_existing_filed_matter_state, reverse_backfill_existing_filed_matter_state),
        migrations.RunPython(sync_court_proceeding_compatibility_fields, noop_reverse),
        migrations.AlterField(
            model_name='casefiling',
            name='filing_type',
            field=models.CharField(choices=[('PLAINT', 'Plaint'), ('DEFENCE', 'Defence'), ('PETITION', 'Petition'), ('NOTICE_OF_MOTION', 'Notice of Motion'), ('CHAMBER_SUMMONS', 'Chamber Summons'), ('APPLICATION', 'Application'), ('AFFIDAVIT', 'Affidavit'), ('REPLYING_AFFIDAVIT', 'Replying Affidavit'), ('FURTHER_AFFIDAVIT', 'Further Affidavit'), ('WITNESS_STATEMENT', 'Witness Statement'), ('LIST_OF_DOCUMENTS', 'List of Documents'), ('SUBMISSIONS', 'Submissions'), ('MEMORANDUM_OF_APPEAL', 'Memorandum of Appeal'), ('RECORD_OF_APPEAL', 'Record of Appeal'), ('NOTICE_OF_APPEAL', 'Notice of Appeal'), ('DEMAND_LETTER', 'Demand Letter'), ('CONSENT', 'Consent'), ('ORDER', 'Court Order'), ('DECREE', 'Decree'), ('RULING', 'Ruling'), ('JUDGMENT', 'Judgment'), ('AFFIDAVIT_OF_SERVICE', 'Affidavit of Service'), ('ORIGINATING_CLAIM', 'Originating claim'), ('OTHER', 'Other')], max_length=60),
        ),
    ]
