# Generated by Django 6.0.5 on 2026-07-29 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_workflow_history(apps, schema_editor):
    Case = apps.get_model("cases", "Case")
    CaseEvent = apps.get_model("cases", "CaseEvent")
    JurisdictionAssessment = apps.get_model("cases", "JurisdictionAssessment")
    JudiciaryCTSSnapshot = apps.get_model("cases", "JudiciaryCTSSnapshot")

    for case in Case.objects.all().iterator():
        stage = "PRE_FILING"
        if case.official_court_case_number:
            stage = "FILED_REGISTERED"
        if case.court_stage == "AWAITING_HEARING":
            stage = "AWAITING_HEARING"
        elif case.court_stage == "HEARING_IN_PROGRESS":
            stage = "PART_HEARD"
        elif case.court_stage == "SUBMISSIONS":
            stage = "AWAITING_SUBMISSIONS"
        elif case.court_stage == "JUDGMENT_RESERVED":
            stage = "AWAITING_JUDGMENT"
        elif case.court_stage == "JUDGMENT_DELIVERED":
            stage = "JUDGMENT_DELIVERED"
        elif case.court_stage == "EXECUTION":
            stage = "EXECUTION"
        elif case.court_stage == "APPEAL_OR_REVIEW":
            stage = "ON_APPEAL"
        elif case.court_stage == "CONCLUDED":
            stage = "CLOSED"
        Case.objects.filter(pk=case.pk).update(lifecycle_stage=stage)

        if case.jurisdiction_verified or case.jurisdiction_notes:
            source = (
                "EXISTING_COURT_RECORD"
                if case.entry_route == "EXISTING_FILED_COURT_CASE"
                else "PRE_FILING_ASSESSMENT"
            )
            status = (
                "CARRIED_OVER_FROM_EXISTING_CASE"
                if source == "EXISTING_COURT_RECORD"
                else "VERIFIED"
            )
            JurisdictionAssessment.objects.create(
                case_id=case.pk,
                source=source,
                status=status,
                proposed_court=case.court_name,
                proposed_station=case.court_station,
                claim_value=case.claim_amount,
                assessment=case.jurisdiction_notes,
                recorded_by_id=case.jurisdiction_verified_by_id,
                confirmed_by_id=case.jurisdiction_verified_by_id,
            )
        if case.official_court_case_number and case.cts_reference:
            JudiciaryCTSSnapshot.objects.create(
                case_id=case.pk,
                official_case_number=case.official_court_case_number,
                cts_reference=case.cts_reference,
                efiling_reference=case.efiling_reference,
                court=case.court_name,
                court_station=case.court_station,
                source="Legacy Sheria Master record",
                notes="Migrated from the legacy CTS reference field.",
                checked_by_id=case.jurisdiction_verified_by_id,
                checked_at=case.jurisdiction_verified_at or timezone.now(),
            )

    for case_id in CaseEvent.objects.values_list("case_id", flat=True).distinct():
        for sequence, event in enumerate(
            CaseEvent.objects.filter(case_id=case_id).order_by("starts_at", "created_at", "id"),
            start=1,
        ):
            CaseEvent.objects.filter(pk=event.pk).update(sequence_number=sequence)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_control_employment_matter_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudiciaryCTSSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('official_case_number', models.CharField(max_length=120)),
                ('cts_reference', models.CharField(blank=True, default='', max_length=120)),
                ('efiling_reference', models.CharField(blank=True, default='', max_length=120)),
                ('court', models.CharField(blank=True, default='', max_length=255)),
                ('court_station', models.CharField(blank=True, default='', max_length=255)),
                ('judiciary_status', models.CharField(blank=True, default='', max_length=255)),
                ('latest_official_court_date', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('checked_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'case_judiciary_cts_snapshots',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='JurisdictionAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('PRE_FILING_ASSESSMENT', 'Pre-filing assessment'), ('EXISTING_COURT_RECORD', 'Existing court record'), ('JURISDICTION_REVIEW', 'Jurisdiction review')], max_length=40)),
                ('status', models.CharField(choices=[('UNDER_REVIEW', 'Under review'), ('VERIFIED', 'Verified'), ('CARRIED_OVER_FROM_EXISTING_CASE', 'Carried over from existing filed case'), ('CHALLENGED_BY_PARTY', 'Challenged by a party'), ('RAISED_BY_COURT', 'Raised by the court'), ('TRANSFER_PENDING', 'Transfer pending'), ('TRANSFERRED', 'Transferred'), ('INCORRECT', 'Found to be incorrect')], max_length=50)),
                ('trigger', models.TextField(blank=True, default='')),
                ('date_raised', models.DateTimeField(blank=True, null=True)),
                ('raised_by', models.CharField(blank=True, default='', max_length=255)),
                ('proposed_court', models.CharField(blank=True, default='', max_length=255)),
                ('proposed_station', models.CharField(blank=True, default='', max_length=255)),
                ('subject_matter_basis', models.TextField(blank=True, default='')),
                ('pecuniary_basis', models.TextField(blank=True, default='')),
                ('territorial_basis', models.TextField(blank=True, default='')),
                ('claim_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('legal_basis', models.TextField(blank=True, default='')),
                ('assessment', models.TextField(blank=True, default='')),
                ('court_directions_or_ruling', models.TextField(blank=True, default='')),
                ('previous_court', models.CharField(blank=True, default='', max_length=255)),
                ('new_court', models.CharField(blank=True, default='', max_length=255)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('information_source', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'case_jurisdiction_assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='lifecycle_stage',
            field=models.CharField(choices=[('PRE_FILING', 'Pre-filing'), ('FILING_PENDING', 'Filing pending'), ('FILED_REGISTERED', 'Filed / registered'), ('AWAITING_DIRECTIONS', 'Awaiting directions'), ('AWAITING_MENTION', 'Awaiting mention'), ('AWAITING_APPLICATION_HEARING', 'Awaiting application hearing'), ('AWAITING_HEARING', 'Awaiting hearing'), ('PART_HEARD', 'Part-heard'), ('AWAITING_SUBMISSIONS', 'Awaiting submissions'), ('AWAITING_RULING', 'Awaiting ruling'), ('AWAITING_JUDGMENT', 'Awaiting judgment'), ('JUDGMENT_DELIVERED', 'Judgment delivered'), ('EXECUTION', 'Execution'), ('ON_APPEAL', 'On appeal'), ('STAYED', 'Stayed'), ('SETTLED', 'Settled'), ('WITHDRAWN', 'Withdrawn'), ('DISMISSED', 'Dismissed'), ('CLOSED', 'Closed')], db_index=True, default='PRE_FILING', help_text='Sheria Master internal stage, derived from filing and proceedings.', max_length=50),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='attendance',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='court_direction_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='outcome_code',
            field=models.CharField(blank=True, choices=[('PROCEEDED', 'Proceeded'), ('ADJOURNED', 'Adjourned'), ('PART_HEARD', 'Part-heard'), ('DIRECTIONS_ISSUED', 'Directions issued'), ('DATE_ISSUED', 'Next date issued'), ('RULING_DELIVERED', 'Ruling delivered'), ('JUDGMENT_DELIVERED', 'Judgment delivered'), ('CONSENT_RECORDED', 'Consent recorded'), ('SETTLED', 'Settled'), ('WITHDRAWN', 'Withdrawn'), ('DISMISSED', 'Dismissed'), ('TAKEN_OUT', 'Taken out'), ('VACATED', 'Vacated'), ('DID_NOT_PROCEED', 'Did not proceed'), ('OTHER', 'Other')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='previous_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_next_events', to='cases.caseevent'),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='proceeded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_case_proceedings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='sequence_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='supporting_documents',
            field=models.ManyToManyField(blank=True, related_name='supported_proceedings', to='cases.caseattachment'),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_case_proceedings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='event_type',
            field=models.CharField(choices=[('INTERNAL', 'Internal matter activity'), ('FILING', 'Filing'), ('REGISTRATION', 'Registry registration'), ('REGISTRY_ACTION', 'Registry action'), ('SERVICE', 'Service'), ('PLEA', 'Plea'), ('DIRECTIONS', 'Directions'), ('CASE_MANAGEMENT', 'Case-management conference'), ('PRE_TRIAL', 'Pre-trial conference'), ('MENTION', 'Mention'), ('FURTHER_MENTION', 'Further mention'), ('COMPLIANCE_MENTION', 'Compliance mention'), ('APPLICATION_HEARING', 'Application hearing'), ('PRELIMINARY_OBJECTION', 'Preliminary objection'), ('HEARING', 'Hearing'), ('FURTHER_HEARING', 'Further hearing'), ('DEFENCE_HEARING', 'Defence hearing'), ('SUBMISSIONS', 'Submissions'), ('RULING', 'Ruling'), ('JUDGMENT', 'Judgment'), ('SENTENCING', 'Sentencing'), ('MITIGATION', 'Mitigation'), ('PROBATION_REPORT', 'Probation report'), ('TAXATION', 'Taxation'), ('ADR', 'Alternative dispute resolution'), ('MEDIATION', 'Mediation'), ('SETTLEMENT', 'Settlement or consent'), ('DECREE', 'Decree'), ('EXECUTION', 'Execution'), ('REVIEW', 'Review'), ('APPEAL', 'Appeal'), ('WITHDRAWAL', 'Withdrawal'), ('DISMISSAL', 'Dismissal'), ('CLOSURE', 'Closure'), ('ADMINISTRATIVE', 'Administrative activity'), ('CLIENT_MEETING', 'Client meeting'), ('OTHER_COURT_DIRECTED', 'Other court-directed event'), ('OTHER', 'Other')], max_length=40),
        ),
        migrations.AddField(
            model_name='judiciaryctssnapshot',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cts_snapshots', to='cases.case'),
        ),
        migrations.AddField(
            model_name='judiciaryctssnapshot',
            name='checked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_cts_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judiciaryctssnapshot',
            name='supporting_documents',
            field=models.ManyToManyField(blank=True, related_name='cts_snapshots', to='cases.caseattachment'),
        ),
        migrations.AddField(
            model_name='jurisdictionassessment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurisdiction_history', to='cases.case'),
        ),
        migrations.AddField(
            model_name='jurisdictionassessment',
            name='confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_jurisdiction_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jurisdictionassessment',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_jurisdiction_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jurisdictionassessment',
            name='supporting_documents',
            field=models.ManyToManyField(blank=True, related_name='jurisdiction_assessments', to='cases.caseattachment'),
        ),
        migrations.RunPython(backfill_workflow_history, noop_reverse),
        migrations.AddConstraint(
            model_name='caseevent',
            constraint=models.UniqueConstraint(fields=('case', 'sequence_number'), name='unique_case_event_sequence'),
        ),
    ]
