# Generated by Django 6.0.5 on 2026-08-01 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def assign_legacy_matter_document_references(apps, schema_editor):
    Case = apps.get_model("cases", "Case")
    Attachment = apps.get_model("cases", "CaseAttachment")
    Sequence = apps.get_model("cases", "CaseAttachmentReferenceSequence")
    for case in Case.objects.all().iterator():
        number = 1
        for attachment in Attachment.objects.filter(case_id=case.pk).order_by("created_at", "id"):
            if not attachment.document_reference:
                attachment.document_reference = f"{case.case_number}/D{number:03d}"
                attachment.save(update_fields=["document_reference"])
            number += 1
        Sequence.objects.update_or_create(case_id=case.pk, defaults={"next_number": number})


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_caseevent_track'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAttachmentReferenceSequence',
            fields=[
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attachment_reference_sequence', serialize=False, to='cases.case')),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'case_attachment_reference_sequences',
            },
        ),
        migrations.CreateModel(
            name='CaseAttachmentVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='case_attachment_versions/')),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('file_hash', models.CharField(blank=True, default='', max_length=128)),
                ('change_notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'case_attachment_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='caseattachment',
            name='document_reference',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddConstraint(
            model_name='caseattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('document_reference', ''), _negated=True), fields=('case', 'document_reference'), name='unique_matter_attachment_reference'),
        ),
        migrations.AddField(
            model_name='caseattachmentversion',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='cases.caseattachment'),
        ),
        migrations.AddField(
            model_name='caseattachmentversion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_case_attachment_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='caseattachmentversion',
            constraint=models.UniqueConstraint(fields=('attachment', 'version_number'), name='unique_case_attachment_version'),
        ),
        migrations.RunPython(assign_legacy_matter_document_references, noop_reverse),
    ]
