# Generated by Django 5.2.16 on 2026-08-01 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_caseevent_track'),
        ('clients', '0017_clientdocument_custody_notes_and_more'),
        ('firm', '0002_initial'),
        ('staff', '0003_alter_lawyerpermissiongrant_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedMatter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short descriptive title for the proposed matter.', max_length=255)),
                ('proposed_instructions', models.TextField(help_text='The proposed instructions from the prospective client.')),
                ('factual_summary', models.TextField(blank=True, default='', help_text='Summary of the relevant facts as understood at proposal stage.')),
                ('desired_outcome', models.TextField(blank=True, default='', help_text='The outcome the prospective client hopes to achieve.')),
                ('urgency_level', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('urgency_details', models.TextField(blank=True, default='', help_text='Free-text explanation of why the matter is urgent (if applicable).')),
                ('known_adverse_party', models.CharField(blank=True, default='', help_text='Name of the known adverse / opposing party, if any.', max_length=255)),
                ('no_adverse_party_known', models.BooleanField(default=False, help_text='Tick when no adverse party is currently known.')),
                ('limitation_date', models.DateField(blank=True, help_text='Statutory limitation or key deadline date.', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CONFLICT_CHECK_INITIATED', 'Conflict check initiated'), ('CONFLICT_CLEARED', 'Conflict cleared'), ('CONFLICT_IDENTIFIED', 'Conflict identified'), ('CONVERTED_TO_MATTER', 'Converted to matter'), ('WITHDRAWN', 'Withdrawn'), ('ABANDONED', 'Abandoned')], db_index=True, default='DRAFT', max_length=40)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_reason', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_matters', to='clients.client')),
                ('converted_to_case', models.OneToOneField(blank=True, help_text='The Case created when this proposed matter is converted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_proposed_matter', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proposed_matters', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_matters', to='firm.lawfirm')),
                ('responsible_advocate', models.ForeignKey(blank=True, help_text='The advocate who will handle the matter if it proceeds.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_matters', to='staff.lawyer')),
            ],
            options={
                'db_table': 'proposed_matters',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['firm', 'status'], name='proposed_ma_firm_id_20ba46_idx'), models.Index(fields=['firm', 'urgency_level'], name='proposed_ma_firm_id_a7a30a_idx'), models.Index(fields=['client'], name='proposed_ma_client__1785a2_idx'), models.Index(fields=['responsible_advocate'], name='proposed_ma_respons_c8189a_idx')],
            },
        ),
    ]
