# Generated by Django 6.0.5 on 2026-08-02 15:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_pending_physical_files(apps, schema_editor):
    Case = apps.get_model("cases", "Case")
    MatterPhysicalFile = apps.get_model("cases", "MatterPhysicalFile")
    MatterPhysicalFileMovement = apps.get_model("cases", "MatterPhysicalFileMovement")
    CaseAttachment = apps.get_model("cases", "CaseAttachment")
    for matter in Case.objects.all().iterator():
        physical_file, created = MatterPhysicalFile.objects.get_or_create(
            matter_id=matter.id,
            defaults={
                "firm_id": matter.firm_id,
                "reference": matter.case_number,
                "status": "REQUESTED",
                "custody_label": "Awaiting preparation",
                "notes": "Pending record created for an existing matter; no physical folder assignment was inferred.",
            },
        )
        CaseAttachment.objects.filter(case_id=matter.id, physical_file__isnull=True).update(physical_file=physical_file)
        if created and matter.created_by_id:
            MatterPhysicalFileMovement.objects.create(
                physical_file=physical_file,
                action="REQUESTED",
                previous_status="",
                new_status="REQUESTED",
                previous_location="",
                new_location="",
                reason="Physical matter-file preparation requested for existing matter; location not yet confirmed.",
                recorded_by_id=matter.created_by_id,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_caseattachment_physical_register_fields'),
        ('clients', '0028_physical_matter_file_workflow'),
        ('firm', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caseattachment',
            name='item_location_detail',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='caseattachment',
            name='origin',
            field=models.CharField(choices=[('CLIENT_SUPPLIED', 'Client-supplied Matter Evidence'), ('FIRM_GENERATED', 'Firm-generated Work Product'), ('THIRD_PARTY_RECEIVED', 'Third-party Received')], default='FIRM_GENERATED', max_length=30),
        ),
        migrations.AddField(
            model_name='caseattachment',
            name='physical_section',
            field=models.CharField(choices=[('INSTRUCTIONS', 'Instructions'), ('ATTENDANCE_NOTES', 'Attendance Notes'), ('CORRESPONDENCE', 'Correspondence'), ('DEMAND_PRE_ACTION', 'Demand and Pre-action'), ('EVIDENCE', 'Evidence'), ('PLEADINGS_COURT', 'Pleadings and Court Documents'), ('COURT_STAMPED', 'Court-stamped Documents'), ('RESEARCH', 'Research'), ('SETTLEMENT', 'Settlement'), ('ACCOUNTS', 'Accounts and Disbursements'), ('CLOSING', 'Closing'), ('OTHER', 'Other')], default='OTHER', max_length=40),
        ),
        migrations.CreateModel(
            name='MatterPhysicalFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('AWAITING_PREPARATION', 'Awaiting Preparation'), ('ACTIVE', 'Active'), ('CHECKED_OUT', 'Checked Out'), ('TEMPORARILY_TRANSFERRED', 'Temporarily Transferred'), ('CLOSURE_PENDING', 'Closure Pending'), ('ARCHIVED', 'Archived'), ('MISSING', 'Missing'), ('DESTROYED', 'Destroyed')], default='REQUESTED', max_length=32)),
                ('storage_zone', models.CharField(blank=True, default='', max_length=100)),
                ('cabinet', models.CharField(blank=True, default='', max_length=100)),
                ('shelf_or_drawer', models.CharField(blank=True, default='', max_length=100)),
                ('location_detail', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('custody_label', models.CharField(blank=True, default='Records room', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_matter_physical_files', to=settings.AUTH_USER_MODEL)),
                ('current_custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custodied_matter_physical_files', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matter_physical_files', to='firm.lawfirm')),
                ('matter', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='physical_file', to='cases.case')),
            ],
            options={
                'db_table': 'matter_physical_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='caseattachment',
            name='physical_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='cases.matterphysicalfile'),
        ),
        migrations.CreateModel(
            name='MatterPhysicalFileMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('REQUESTED', 'Preparation Requested'), ('ASSIGNED', 'Assigned'), ('RELOCATED', 'Relocated'), ('CHECKED_OUT', 'Checked Out'), ('RETURNED', 'Returned'), ('TRANSFERRED', 'Transferred'), ('MARKED_MISSING', 'Marked Missing'), ('FOUND', 'Found'), ('SENT_FOR_ARCHIVING', 'Sent for Archiving'), ('ARCHIVED', 'Archived')], max_length=30)),
                ('previous_status', models.CharField(blank=True, default='', max_length=32)),
                ('new_status', models.CharField(max_length=32)),
                ('previous_location', models.CharField(blank=True, default='', max_length=500)),
                ('new_location', models.CharField(blank=True, default='', max_length=500)),
                ('reason', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('issued_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_matter_files', to=settings.AUTH_USER_MODEL)),
                ('physical_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='cases.matterphysicalfile')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_matter_file_movements', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_matter_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matter_physical_file_movements',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='MatterDocumentTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_reference', models.CharField(blank=True, default='', max_length=80)),
                ('new_reference', models.CharField(max_length=80)),
                ('previous_location', models.CharField(blank=True, default='', max_length=500)),
                ('new_location', models.CharField(max_length=500)),
                ('source_register', models.CharField(max_length=50)),
                ('destination_register', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_acknowledgement', models.CharField(blank=True, default='', max_length=255)),
                ('destination_attachment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='custody_transfer', to='cases.caseattachment')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matter_transfers', to='clients.clientdocument')),
                ('transferred_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matter_document_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matter_document_transfers',
                'ordering': ['-transferred_at'],
                'indexes': [models.Index(fields=['source_document'], name='matter_docu_source__2e6bff_idx'), models.Index(fields=['transferred_at'], name='matter_docu_transfe_d59c0a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='matterphysicalfile',
            index=models.Index(fields=['firm', 'status'], name='matter_phys_firm_id_ca1169_idx'),
        ),
        migrations.AddIndex(
            model_name='matterphysicalfile',
            index=models.Index(fields=['firm', 'reference'], name='matter_phys_firm_id_92cb28_idx'),
        ),
        migrations.AddIndex(
            model_name='matterphysicalfile',
            index=models.Index(fields=['current_custodian'], name='matter_phys_current_b02e06_idx'),
        ),
        migrations.AddConstraint(
            model_name='matterphysicalfile',
            constraint=models.UniqueConstraint(fields=('firm', 'reference'), name='unique_matter_physical_file_reference_per_firm'),
        ),
        migrations.AddIndex(
            model_name='matterphysicalfilemovement',
            index=models.Index(fields=['physical_file', 'recorded_at'], name='matter_phys_physica_30171d_idx'),
        ),
        migrations.AddIndex(
            model_name='matterphysicalfilemovement',
            index=models.Index(fields=['action'], name='matter_phys_action_6373d3_idx'),
        ),
        migrations.RunPython(create_pending_physical_files, migrations.RunPython.noop),
    ]
