# Generated by Django 6.0.5 on 2026-08-03 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_physical_matter_file_workflow'),
        ('staff', '0003_alter_lawyerpermissiongrant_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseevent',
            name='compliance_obligations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='costs_outcome',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='is_material_to_outlook',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='party_favoured',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='responsible_advocate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_event_outcomes', to='staff.lawyer'),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='source_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_event_outcomes', to='cases.caseattachment'),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='UNVERIFIED', max_length=20),
        ),
    ]
