# Generated by Django 6.0.5 on 2026-08-04 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_matterarchive_destructionlog_archiveaccesslog_and_more'),
        ('firm', '0003_firmsetting_allow_engagement_waiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatterDeadline',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deadline_type', models.CharField(choices=[('LIMITATION', 'Limitation'), ('COURT', 'Court date'), ('FILING', 'Filing'), ('SERVICE', 'Service'), ('RESPONSE', 'Response'), ('HEARING', 'Hearing'), ('MENTION', 'Mention'), ('SUBMISSIONS', 'Submissions'), ('COMPLETION', 'Completion'), ('UNDERTAKING', 'Undertaking'), ('RENEWAL', 'Renewal'), ('APPEAL_REVIEW', 'Appeal / review'), ('RETENTION_REVIEW', 'Retention review'), ('CLIENT_FOLLOW_UP', 'Client follow-up')], max_length=32)),
                ('due_at', models.DateTimeField()),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=60)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=16)),
                ('source', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reminder_schedule', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_deadlines', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_deadlines', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matter_deadlines', to='firm.lawfirm')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deadlines', to='cases.case')),
                ('responsible_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_deadlines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matter_deadlines',
            },
        ),
        migrations.CreateModel(
            name='DeadlineChangeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_due_at', models.DateTimeField()),
                ('new_due_at', models.DateTimeField()),
                ('reason', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deadline_changes', to=settings.AUTH_USER_MODEL)),
                ('deadline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_history', to='cases.matterdeadline')),
            ],
            options={
                'db_table': 'matter_deadline_change_history',
            },
        ),
        migrations.AddIndex(
            model_name='matterdeadline',
            index=models.Index(fields=['firm', 'status', 'due_at'], name='matter_dead_firm_id_f643dc_idx'),
        ),
    ]
