# Generated by Django 6.0.5 on 2026-08-04 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_matterdeadline_deadlinechangehistory_and_more'),
        ('clients', '0031_clientcompliancereview_clientcompliancehistory_and_more'),
        ('firm', '0003_firmsetting_allow_engagement_waiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedClosingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('CLOSING_LETTER', 'Closing letter'), ('FINAL_CLIENT_STATEMENT', 'Final client statement')], max_length=32)),
                ('version', models.PositiveIntegerField()),
                ('content_snapshot', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('client_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_closing_records', to='clients.clientdocument')),
                ('closure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='cases.matterclosure')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_closing_documents', to='firm.lawfirm')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_closing_documents', to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_closing_documents', to='cases.case')),
            ],
            options={
                'db_table': 'generated_closing_documents',
                'constraints': [models.UniqueConstraint(fields=('closure', 'document_type', 'version'), name='unique_closing_document_version')],
            },
        ),
    ]
