# Generated by Django 6.0.5 on 2026-08-04 13:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_generatedclosingdocument'),
        ('clients', '0032_clientdocument_content_destroyed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatterWorkstreamStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('stage', models.CharField(max_length=80)),
                ('stage_data', models.JSONField(default=dict)),
                ('checklist', models.JSONField(default=dict)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_reason', models.TextField(blank=True, default='')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_workstream_stages', to=settings.AUTH_USER_MODEL)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entered_workstream_stages', to=settings.AUTH_USER_MODEL)),
                ('supporting_documents', models.ManyToManyField(blank=True, related_name='workstream_stage_records', to='clients.clientdocument')),
                ('workstream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_records', to='cases.matterworkstream')),
            ],
            options={
                'db_table': 'matter_workstream_stages',
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('workstream', 'sequence'), name='unique_workstream_stage_sequence')],
            },
        ),
    ]
