# Generated by Django 6.0.5 on 2026-08-04 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_matterworkstreamstage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(max_length=16)),
                ('new_status', models.CharField(max_length=16)),
                ('reason', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deadline_status_changes', to=settings.AUTH_USER_MODEL)),
                ('deadline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='cases.matterdeadline')),
            ],
            options={
                'db_table': 'matter_deadline_status_history',
            },
        ),
    ]
