# Generated by Django 6.0.5 on 2026-08-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0026_deadlinestatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedclosingdocument',
            name='document_type',
            field=models.CharField(choices=[('CLOSING_LETTER', 'Closing letter'), ('FINAL_CLIENT_STATEMENT', 'Final client statement'), ('DOCUMENT_RETURN_ACKNOWLEDGEMENT', 'Document-return acknowledgement'), ('CLIENT_MONEY_STATEMENT', 'Client-money statement'), ('COMPLETION_STATEMENT', 'Completion statement'), ('DOCUMENT_RECEIPT', 'Document receipt'), ('ARCHIVE_NOTICE', 'Archive notice')], max_length=32),
        ),
    ]
