# Generated by Django 6.0.3 on 2026-08-23 03:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0028_legalassessment_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('court_type', models.CharField(choices=[('SUPREME_COURT', 'Supreme Court'), ('COURT_OF_APPEAL', 'Court of Appeal'), ('HIGH_COURT', 'High Court'), ('ELC', 'Environment and Land Court'), ('ELRC', 'Employment and Labour Relations Court'), ('MAGISTRATES_COURT', "Magistrates' Court"), ('KADHIS_COURT', "Kadhis' Court"), ('SMALL_CLAIMS_COURT', 'Small Claims Court'), ('COURTS_MARTIAL', 'Courts Martial'), ('TRIBUNAL', 'Tribunal')], db_index=True, max_length=32)),
                ('level', models.PositiveSmallIntegerField(help_text='Hierarchy level where 1 is the apex court; specialist/subordinate bodies use later levels.')),
                ('county', models.CharField(db_index=True, max_length=100)),
                ('station', models.CharField(db_index=True, max_length=160)),
                ('address', models.TextField(blank=True, default='')),
                ('jurisdiction', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TEMPORARILY_CLOSED', 'Temporarily closed')], db_index=True, default='ACTIVE', max_length=24)),
            ],
            options={
                'db_table': 'kenyan_courts',
                'ordering': ['level', 'county', 'station', 'name'],
                'indexes': [models.Index(fields=['court_type', 'status'], name='kenyan_cour_court_t_311b94_idx'), models.Index(fields=['county', 'status'], name='kenyan_cour_county_bf7bc8_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'county', 'station'), name='unique_kenyan_court_station'), models.CheckConstraint(condition=models.Q(('level__gte', 1)), name='court_level_positive')],
            },
        ),
    ]
