# Generated by Django 6.0.5 on 2026-09-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0029_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefiling',
            name='response_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casefiling',
            name='filing_type',
            field=models.CharField(choices=[('PLAINT', 'Plaint'), ('SUMMONS', 'Summons to enter appearance'), ('MEMORANDUM_OF_APPEARANCE', 'Memorandum of appearance'), ('DEFENCE', 'Defence'), ('REPLY_TO_DEFENCE', 'Reply to defence'), ('REQUEST_FOR_JUDGMENT', 'Request for judgment'), ('PETITION', 'Petition'), ('NOTICE_OF_MOTION', 'Notice of Motion'), ('CHAMBER_SUMMONS', 'Chamber Summons'), ('APPLICATION', 'Application'), ('AFFIDAVIT', 'Affidavit'), ('REPLYING_AFFIDAVIT', 'Replying Affidavit'), ('FURTHER_AFFIDAVIT', 'Further Affidavit'), ('WITNESS_STATEMENT', 'Witness Statement'), ('LIST_OF_DOCUMENTS', 'List of Documents'), ('SUBMISSIONS', 'Submissions'), ('MEMORANDUM_OF_APPEAL', 'Memorandum of Appeal'), ('RECORD_OF_APPEAL', 'Record of Appeal'), ('NOTICE_OF_APPEAL', 'Notice of Appeal'), ('DEMAND_LETTER', 'Demand Letter'), ('CONSENT', 'Consent'), ('ORDER', 'Court Order'), ('DECREE', 'Decree'), ('BILL_OF_COSTS', 'Bill of costs'), ('CERTIFICATE_OF_COSTS', 'Certificate of costs'), ('WARRANT_OF_ATTACHMENT', 'Warrant of attachment and sale'), ('RULING', 'Ruling'), ('JUDGMENT', 'Judgment'), ('AFFIDAVIT_OF_SERVICE', 'Affidavit of Service'), ('ORIGINATING_CLAIM', 'Originating claim'), ('OTHER', 'Other')], max_length=60),
        ),
    ]
