# Generated by Django 6.0.5 on 2026-09-27 22:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firm', '0003_firmsetting_allow_engagement_waiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='KES per month, excluding VAT.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('annual_price', models.DecimalField(decimal_places=2, help_text='KES per year, excluding VAT.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_advocates', models.PositiveIntegerField(blank=True, null=True)),
                ('max_support_staff', models.PositiveIntegerField(blank=True, null=True)),
                ('max_active_matters', models.PositiveIntegerField(blank=True, null=True)),
                ('max_branches', models.PositiveIntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=True, help_text='Shown on the pricing page and sign-up.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='FirmSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('TRIALING', 'Trial'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='TRIALING', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=10)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='Blank on an active subscription means it does not lapse (complimentary or legacy).', null=True)),
                ('grace_period_days', models.PositiveIntegerField(default=7)),
                ('notes', models.TextField(blank=True)),
                ('firm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='firm.lawfirm')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
            ],
            options={
                'db_table': 'firm_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], max_length=10)),
                ('status', models.CharField(choices=[('ISSUED', 'Awaiting payment'), ('PAYMENT_SUBMITTED', 'Payment submitted, awaiting confirmation'), ('PAID', 'Paid'), ('VOID', 'Void')], default='ISSUED', max_length=20)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proration_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_excl_vat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=20)),
                ('payer_phone', models.CharField(blank=True, max_length=20)),
                ('payment_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('etims_invoice_number', models.CharField(blank=True, help_text='KRA eTIMS control/invoice number, recorded by platform finance.', max_length=50)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_subscription_payments', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_invoices', to='firm.lawfirm')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_subscription_invoices', to=settings.AUTH_USER_MODEL)),
                ('payment_submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_subscription_payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='subscriptions.plan')),
            ],
            options={
                'db_table': 'subscription_invoices',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('mpesa_receipt', ''), _negated=True), fields=('mpesa_receipt',), name='unique_subscription_mpesa_receipt')],
            },
        ),
    ]
