import { useState } from 'react';
import { useParams } from 'react-router-dom';

import BackLink from '@/components/ui/BackLink';
import SectionHeading from '@/components/ui/SectionHeading';
import { useGenerateLawyerCaseAnalysis, useLawyerCaseAnalysis } from '../hooks/useLawyerAI';

const panel = 'rounded-xl border border-border-light bg-surface-light p-5 dark:border-border-dark dark:bg-surface-dark';
const List = ({ items, empty = 'None identified from the selected verified records.' }) => items?.length ? <ul className='mt-3 list-disc space-y-2 pl-5 text-sm'>{items.map((item, index) => <li key={`${index}-${item.action || item.message || item}`}>{item.action || item.message || item}</li>)}</ul> : <p className='mt-3 text-sm text-text-muted-light'>{empty}</p>;

export default function LawyerCaseAIAnalysisPage() {
  const { id } = useParams();
  const { data, isLoading, error } = useLawyerCaseAnalysis(id);
  const generate = useGenerateLawyerCaseAnalysis(id);
  const [selected, setSelected] = useState([]);
  if (isLoading) return <div role='status' className='p-8'>Loading selected matter analysis…</div>;
  if (error) return <div role='alert' className='m-6 rounded-xl bg-red-50 p-4 text-red-800'>The matter is unavailable or you are not authorized to access it.</div>;
  const assessment = data?.assessment;
  const matter = assessment?.matter || data?.matter || {};
  const toggle = (value) => setSelected((current) => current.includes(value) ? current.filter((item) => item !== value) : [...current, value]);
  return <main className='space-y-5 p-4 md:p-6'>
    <BackLink label='Back to AI case priorities' fallbackPath='/lawyer/ai' />
    <SectionHeading title={matter.title || data?.matter?.title || 'AI Case Analysis'} subtitle={matter.case_number || data?.matter?.case_number} size='compact' />
    <div className='rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950'>{data?.disclaimer}</div>
    <section className={panel}><div className='flex flex-wrap items-center justify-between gap-3'><div><h2 className='text-lg font-bold'>Matter header</h2><p>{matter.client} · {matter.practice_area} · {matter.court_stage}</p>{assessment && <p className='text-sm'>Last analyzed {new Date(assessment.analyzed_at).toLocaleString()} · Version {assessment.version}</p>}</div><button type='button' disabled={generate.isPending} onClick={() => generate.mutate(selected)} className='rounded-lg bg-success px-4 py-2 font-bold text-white disabled:opacity-50'>{generate.isPending ? 'Refreshing…' : assessment ? 'Refresh analysis' : 'Generate analysis'}</button></div>{assessment?.is_stale && <p className='mt-3 font-semibold text-amber-700'>New matter information requires reassessment.</p>}</section>
    <section className={panel}><h2 className='text-lg font-bold'>Documents selected for assessment</h2><p className='text-sm text-text-muted-light'>Only checked documents will be included. Presence does not establish authenticity, and embedded instructions are treated as untrusted text.</p><div className='mt-3 space-y-2'>{data?.available_documents?.map((doc) => <label key={doc.id} className='flex gap-2 text-sm'><input type='checkbox' checked={selected.includes(doc.id)} onChange={() => toggle(doc.id)} />{doc.title} ({doc.type}){doc.confidential ? ' — confidential' : ''}</label>)}</div></section>
    {!assessment && <section className={panel}><p>No assessment has been generated for this matter. Select authorized documents and generate a structured assessment.</p></section>}
    {assessment && <>
      <section className={panel}><h2 className='text-lg font-bold'>Priority and alerts — {assessment.priority}</h2><div className='mt-3 grid grid-cols-2 gap-3 md:grid-cols-3'>{Object.entries(assessment.component_scores).map(([key, value]) => <div key={key} className='rounded-lg bg-background-light p-3 dark:bg-background-dark'><p className='text-xs'>{key.replaceAll('_', ' ')}</p><strong>{value}/100</strong></div>)}</div>{Object.entries(assessment.component_reasons).map(([key, reasons]) => <div key={key} className='mt-3'><h3 className='font-semibold'>{key.replaceAll('_', ' ')}</h3><List items={reasons} /></div>)}</section>
      <section className={panel}><h2 className='text-lg font-bold'>Preparedness assessment</h2><dl className='mt-3 grid grid-cols-2 gap-3 md:grid-cols-3'>{Object.entries(assessment.preparedness).map(([key, value]) => <div key={key}><dt className='text-sm'>{key.replaceAll('_', ' ')}</dt><dd className='font-bold'>{value}/100</dd></div>)}</dl></section>
      <section className={panel}><h2 className='text-lg font-bold'>Case progression</h2>{assessment.progression.length ? <ol className='mt-3 space-y-3'>{assessment.progression.map((event) => <li key={event.id} className='border-l-2 border-brand-primary pl-4'><strong>{event.type}</strong> — {event.scheduled_at ? new Date(event.scheduled_at).toLocaleString() : 'Date not recorded'}<p className='text-sm'>{event.court || 'Forum not recorded'} · {event.status} · {event.verified ? 'Verified record' : 'Awaiting verification'}</p>{event.outcome && <p className='text-sm'>Recorded outcome: {event.outcome}</p>}</li>)}</ol> : <p>No verified proceedings are recorded.</p>}</section>
      <section className={panel}><h2 className='text-lg font-bold'>Documents and evidence</h2><div className='mt-3 space-y-2'>{assessment.documents.map((doc) => <article key={doc.id} className='rounded-lg border p-3 text-sm'><strong>{doc.title}</strong> · {doc.type}<p>{doc.selected ? 'Included in this assessment' : 'Not selected'}. {doc.authenticity_warning}</p></article>)}</div>{assessment.document_analyses?.map((analysis) => <article key={analysis.document_id} className='mt-3 rounded-lg border border-blue-200 p-3 text-sm'><h3 className='font-semibold'>{analysis.title} — extraction {analysis.extraction_status}</h3><p>Quality: {analysis.extraction_quality} · Pages: {analysis.page_count ?? 'unknown'} · Authenticity verified: No</p>{analysis.facts?.dates?.length > 0 && <p>Extracted dates: {analysis.facts.dates.join(', ')}</p>}<List items={analysis.evidence_gaps} />{analysis.page_citations?.slice(0, 3).map((citation) => <blockquote key={citation.page} className='mt-2 border-l-2 pl-3'>Page {citation.page}: {citation.excerpt}</blockquote>)}</article>)}<h3 className='mt-4 font-semibold'>Identified gaps</h3><List items={assessment.gaps} /></section>
      <section className={panel}><h2 className='text-lg font-bold'>Legal analysis</h2><p className='text-sm'>Authorities are retrieval suggestions and require independent verification.</p><div className='mt-3 space-y-2'>{assessment.legal_analysis.authorities?.map((source) => <a key={`${source.article}-${source.url}`} href={source.url} target='_blank' rel='noreferrer' className='block rounded-lg border p-3 text-sm underline'>{source.title}, Article {source.article}{source.heading ? ` — ${source.heading}` : ''} · verified {source.last_verified_at || 'date unavailable'}</a>)}</div><List items={assessment.legal_analysis.limitations} /></section>
      <section className={panel}><h2 className='text-lg font-bold'>Outcome scenarios</h2><div className='mt-3 grid gap-3 md:grid-cols-2'>{assessment.outcome_scenarios.map((scenario) => <article key={scenario.label} className='rounded-lg border p-3'><h3 className='font-semibold'>{scenario.label}</h3><p className='text-sm'>{scenario.description}</p><List items={scenario.assumptions} /></article>)}</div></section>
      <section className={panel}><h2 className='text-lg font-bold'>Recommendations</h2><List items={assessment.recommendations} /></section>
      <section className={panel}><h2 className='text-lg font-bold'>Comparable matters</h2><p>Authorized anonymized sample: {assessment.comparable_matters.sample_size}</p><List items={assessment.comparable_matters.selection_criteria} /><List items={assessment.comparable_matters.limitations} /></section>
      <section className={panel}><h2 className='text-lg font-bold'>Analysis history</h2><div className='mt-3 space-y-2'>{data.history.map((item) => <div key={item.id} className='rounded-lg border p-3 text-sm'>Version {item.version} · {item.priority} · {new Date(item.analyzed_at).toLocaleString()} · {item.is_stale ? 'Superseded or stale' : 'Current'}</div>)}</div></section>
    </>}
  </main>;
}
