# Generated by Django 6.0.5 on 2026-09-15 12:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0039_preliminaryreview_preliminaryphysicalfile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('MINIMUM_INFORMATION', 'Minimum information'), ('AUTHORISED_CREATION', 'Authorised creation')], max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiry_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrative_tasks', to='clients.walkinenquiry')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('enquiry',), name='one_pending_enquiry_task')],
            },
        ),
    ]
