from django.urls import path

from apps.cases.views import (
    CaseConflictCheckActionView,
    CaseConflictCheckView,
    CaseDetailView,
    CaseEventListCreateView,
    CaseJurisdictionVerificationView,
    CaseListCreateView,
    CaseLifecycleTransitionView,
    CaseReassignLawyerView,
    CaseReassignSecretaryView,
    CaseStatusView,
    CaseTaskListCreateView,
    MatterPhysicalFileView,
    VirtualCourtroomLinkUpdateView,
    VirtualCourtroomTodayView,
    AllowedNextEventsView,
    RecordProceedingOutcomeView,
)
from apps.cases.views.matter_governance_view import (
    ClosingDocumentGenerateView, DestructionView, LegalHoldView, MatterArchiveView,
    MatterClosureActionView, MatterClosureView, RetentionReviewView,
)
from apps.cases.views.matter_operations_view import (
    DeadlineChangeView, DeadlineResolveView, LegalAssessmentView, MatterDeadlineView, MatterWorkstreamView,
    WorkstreamStageCompleteView,
)

urlpatterns = [
    path("", CaseListCreateView.as_view(), name="case-list"),
    path("open/", CaseListCreateView.as_view(), name="case-create"),
    path("courtroom/today/", VirtualCourtroomTodayView.as_view(), name="virtual-courtroom-today"),
    path("events/<uuid:event_id>/courtroom-link/", VirtualCourtroomLinkUpdateView.as_view(), name="virtual-courtroom-link-update"),
    path("<uuid:case_id>/", CaseDetailView.as_view(), name="case-detail"),
    path("<uuid:case_id>/events/", CaseEventListCreateView.as_view(), name="case-event-list-create"),
    path("<uuid:case_id>/tasks/", CaseTaskListCreateView.as_view(), name="case-task-list-create"),
    path("<uuid:case_id>/physical-file/", MatterPhysicalFileView.as_view(), name="matter-physical-file"),
    path("<uuid:case_id>/allowed-next-events/", AllowedNextEventsView.as_view(), name="allowed-next-events"),
    path("<uuid:case_id>/events/<uuid:event_id>/record-outcome/", RecordProceedingOutcomeView.as_view(), name="record-proceeding-outcome"),
    path("<uuid:case_id>/transitions/", CaseLifecycleTransitionView.as_view(), name="case-lifecycle-transition"),
    path("<uuid:case_id>/conflict-check/", CaseConflictCheckView.as_view(), name="case-conflict-check"),
    path("<uuid:case_id>/conflict-check/actions/", CaseConflictCheckActionView.as_view(), name="case-conflict-check-action"),
    path("<uuid:case_id>/jurisdiction/actions/", CaseJurisdictionVerificationView.as_view(), name="case-jurisdiction-action"),
    path("<uuid:case_id>/status/", CaseStatusView.as_view(), name="case-status"),
    path("<uuid:case_id>/reassign-lawyer/", CaseReassignLawyerView.as_view(), name="case-reassign-lawyer"),
    path("<uuid:case_id>/reassign-secretary/", CaseReassignSecretaryView.as_view(), name="case-reassign-secretary"),
    path("<uuid:case_id>/closure/", MatterClosureView.as_view(), name="matter-closure"),
    path("<uuid:case_id>/closure/<uuid:closure_id>/documents/", ClosingDocumentGenerateView.as_view(), name="closing-document-generate"),
    path("<uuid:case_id>/closure/<uuid:closure_id>/<str:action>/", MatterClosureActionView.as_view(), name="matter-closure-action"),
    path("<uuid:case_id>/archive/", MatterArchiveView.as_view(), name="matter-archive"),
    path("archives/<uuid:archive_id>/retention-reviews/", RetentionReviewView.as_view(), name="retention-review"),
    path("archives/<uuid:archive_id>/destruction/", DestructionView.as_view(), name="archive-destruction"),
    path("archives/<uuid:archive_id>/legal-hold/", LegalHoldView.as_view(), name="archive-legal-hold"),
    path("<uuid:case_id>/legal-assessments/", LegalAssessmentView.as_view(), name="matter-legal-assessments"),
    path("<uuid:case_id>/workstream/", MatterWorkstreamView.as_view(), name="matter-workstream"),
    path("<uuid:case_id>/workstream/current-stage/complete/", WorkstreamStageCompleteView.as_view(), name="matter-workstream-stage-complete"),
    path("<uuid:case_id>/deadlines/", MatterDeadlineView.as_view(), name="matter-deadlines"),
    path("deadlines/<uuid:deadline_id>/change/", DeadlineChangeView.as_view(), name="matter-deadline-change"),
    path("deadlines/<uuid:deadline_id>/resolve/", DeadlineResolveView.as_view(), name="matter-deadline-resolve"),
]
