# Generated by Django 6.0.5 on 2026-07-16 04:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('CASE_ASSIGNMENT', 'Case Assignment'), ('CASE_REASSIGNMENT', 'Case Reassignment'), ('CASE_STATUS_UPDATE', 'Case Status Update'), ('GENERAL', 'General')], default='GENERAL', max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, default='', max_length=255)),
                ('event_key', models.CharField(blank=True, default='', max_length=160)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
