# Generated by Django 6.0.5 on 2026-07-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CASE_ASSIGNMENT', 'Case Assignment'), ('CASE_REASSIGNMENT', 'Case Reassignment'), ('CASE_STATUS_UPDATE', 'Case Status Update'), ('CHAT_MESSAGE', 'Chat Message'), ('GENERAL', 'General')], default='GENERAL', max_length=40),
        ),
    ]
