# Generated by Codex on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("CASE_ASSIGNMENT", "Case Assignment"),
                    ("CASE_REASSIGNMENT", "Case Reassignment"),
                    ("CASE_STATUS_UPDATE", "Case Status Update"),
                    ("COURTROOM_LINK", "Courtroom Link"),
                    ("CHAT_MESSAGE", "Chat Message"),
                    ("GENERAL", "General"),
                ],
                default="GENERAL",
                max_length=40,
            ),
        ),
    ]
