# Generated by Django 6.0.5 on 2026-08-02 00:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('suggested_question', models.CharField(blank=True, max_length=240)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Knowledge base categories',
                'db_table': 'knowledge_base_categories',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseArticle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('jurisdiction', models.CharField(default='Kenya', max_length=120)),
                ('source_name', models.CharField(max_length=240)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('source_reference', models.CharField(blank=True, max_length=300)),
                ('last_verified_at', models.DateField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated search terms.')),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='ai.knowledgebasecategory')),
            ],
            options={
                'db_table': 'knowledge_base_articles',
                'ordering': ('category__display_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseQuestionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('retrieval_score', models.FloatField(default=0)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('answered', 'Answered'), ('no_source', 'No verified source'), ('provider_unavailable', 'Provider unavailable'), ('error', 'Error')], max_length=40)),
                ('request_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_agent_family', models.CharField(blank=True, max_length=80)),
                ('retrieved_articles', models.ManyToManyField(blank=True, related_name='question_logs', to='ai.knowledgebasearticle')),
            ],
            options={
                'db_table': 'knowledge_base_question_logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='knowledgebasearticle',
            index=models.Index(fields=['is_published', 'category'], name='kb_article_public_idx'),
        ),
    ]
