# Generated by Django 6.0.5 on 2026-08-02 01:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_seed_knowledge_base'),
        ('cases', '0017_caseattachmentreferencesequence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalProvision',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_type', models.CharField(choices=[('preamble', 'Preamble'), ('article', 'Article'), ('schedule', 'Schedule')], max_length=20)),
                ('stable_key', models.CharField(max_length=100)),
                ('chapter', models.CharField(blank=True, max_length=240)),
                ('part', models.CharField(blank=True, max_length=240)),
                ('article_number', models.CharField(blank=True, max_length=30)),
                ('heading', models.CharField(blank=True, max_length=300)),
                ('clauses', models.JSONField(blank=True, default=list)),
                ('text', models.TextField()),
                ('checksum', models.CharField(max_length=64)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'legal_provisions',
                'ordering': ('display_order',),
            },
        ),
        migrations.CreateModel(
            name='LegalSourceDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('jurisdiction', models.CharField(default='Kenya', max_length=120)),
                ('source_type', models.CharField(choices=[('constitution', 'Constitution'), ('statute', 'Statute'), ('regulation', 'Regulation'), ('decision', 'Judicial decision')], max_length=30)),
                ('official_url', models.URLField(max_length=500)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('version_date', models.DateField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateField(blank=True, null=True)),
                ('source_checksum', models.CharField(max_length=64)),
                ('is_official_primary_source', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'legal_source_documents',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='AICaseAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20)),
                ('component_scores', models.JSONField(default=dict)),
                ('component_reasons', models.JSONField(default=dict)),
                ('alerts', models.JSONField(default=list)),
                ('gaps', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('preparedness', models.JSONField(default=dict)),
                ('legal_analysis', models.JSONField(default=dict)),
                ('outcome_scenarios', models.JSONField(default=list)),
                ('comparable_matters', models.JSONField(default=dict)),
                ('case_snapshot', models.JSONField(default=dict)),
                ('proceeding_snapshot', models.JSONField(default=list)),
                ('document_snapshot', models.JSONField(default=list)),
                ('confidence', models.CharField(default='LOW', max_length=20)),
                ('limitations', models.JSONField(default=list)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(default='case-assessment-v1', max_length=40)),
                ('scoring_version', models.CharField(default='priority-v1', max_length=40)),
                ('source_version', models.CharField(blank=True, max_length=64)),
                ('analyzed_at', models.DateTimeField()),
                ('source_state_at', models.DateTimeField()),
                ('is_stale', models.BooleanField(default=False)),
                ('status', models.CharField(default='COMPLETED', max_length=30)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assessments', to='cases.case')),
                ('included_documents', models.ManyToManyField(blank=True, related_name='ai_assessments', to='cases.caseattachment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_ai_case_assessments', to=settings.AUTH_USER_MODEL)),
                ('retrieved_provisions', models.ManyToManyField(blank=True, related_name='case_assessments', to='ai.legalprovision')),
            ],
            options={
                'db_table': 'ai_case_assessments',
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='AIAssessmentAudit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=60)),
                ('document_ids', models.JSONField(blank=True, default=list)),
                ('source_ids', models.JSONField(blank=True, default=list)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('result_status', models.CharField(max_length=30)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_assessment_audits', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_audit_entries', to='cases.case')),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='ai.aicaseassessment')),
            ],
            options={
                'db_table': 'ai_assessment_audits',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='legalprovision',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='ai.legalsourcedocument'),
        ),
        migrations.AddIndex(
            model_name='aicaseassessment',
            index=models.Index(fields=['case', 'is_stale', 'analyzed_at'], name='ai_case_current_idx'),
        ),
        migrations.AddConstraint(
            model_name='aicaseassessment',
            constraint=models.UniqueConstraint(fields=('case', 'version'), name='unique_case_assessment_version'),
        ),
        migrations.AddIndex(
            model_name='legalprovision',
            index=models.Index(fields=['is_published', 'article_number'], name='legal_provision_public_idx'),
        ),
        migrations.AddConstraint(
            model_name='legalprovision',
            constraint=models.UniqueConstraint(fields=('document', 'stable_key'), name='unique_legal_provision_key'),
        ),
    ]
