# Generated by Django 6.0.5 on 2026-08-02 01:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_legalprovision_legalsourcedocument_aicaseassessment_and_more'),
        ('cases', '0017_caseattachmentreferencesequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDocumentAnalysis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extraction_status', models.CharField(max_length=30)),
                ('detected_type', models.CharField(blank=True, max_length=100)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('extraction_quality', models.CharField(default='UNKNOWN', max_length=20)),
                ('extracted_facts', models.JSONField(default=dict)),
                ('inconsistencies', models.JSONField(default=list)),
                ('evidence_gaps', models.JSONField(default=list)),
                ('page_citations', models.JSONField(default=list)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('authenticity_verified', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_analyses', to='ai.aicaseassessment')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_document_analyses', to='cases.caseattachment')),
            ],
            options={
                'db_table': 'ai_document_analyses',
                'constraints': [models.UniqueConstraint(fields=('assessment', 'document'), name='unique_assessment_document_analysis')],
            },
        ),
    ]
