# Generated by Django 6.0.5 on 2026-08-02 01:49

from django.db import migrations, models


def set_homepage_contexts(apps, schema_editor):
    Category = apps.get_model("ai", "KnowledgeBaseCategory")
    Category.objects.filter(slug="firm-services").update(
        page_sections=["home", "about", "practice_areas", "consultation", "contact"]
    )
    Category.objects.exclude(slug="firm-services").update(page_sections=["home"])


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_aidocumentanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasecategory',
            name='page_sections',
            field=models.JSONField(blank=True, default=list, help_text='Controlled homepage contexts where this category may be suggested.'),
        ),
        migrations.RunPython(set_homepage_contexts, migrations.RunPython.noop),
    ]
