# Generated by Django 6.0.5 on 2026-08-02 01:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_knowledgebasecategory_page_sections'),
        ('cases', '0017_caseattachmentreferencesequence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aicaseassessment',
            name='change_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aicaseassessment',
            name='knowledge_index_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='aicaseassessment',
            name='model_version',
            field=models.CharField(default='configured-model-v1', max_length=50),
        ),
        migrations.AddField(
            model_name='aicaseassessment',
            name='priority_version',
            field=models.CharField(default='priority-v1', max_length=50),
        ),
        migrations.AddField(
            model_name='aicaseassessment',
            name='retrieval_version',
            field=models.CharField(default='knowledge-retrieval-v1', max_length=50),
        ),
        migrations.CreateModel(
            name='AIConfigurationVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('MODEL', 'Provider/model'), ('PROMPT', 'System prompt'), ('RETRIEVAL', 'Retrieval configuration'), ('SCORING', 'Preparedness scoring'), ('PRIORITY', 'Priority ranking'), ('DATASET', 'Evaluation dataset')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('configuration', models.JSONField(default=dict)),
                ('evaluation_results', models.JSONField(blank=True, default=dict)),
                ('meets_thresholds', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_configuration_versions',
            },
        ),
        migrations.CreateModel(
            name='AIEvaluationRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_version', models.CharField(max_length=50)),
                ('metrics', models.JSONField(default=dict)),
                ('passed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('configuration_versions', models.ManyToManyField(related_name='evaluation_runs', to='ai.aiconfigurationversion')),
                ('run_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_evaluation_runs',
            },
        ),
        migrations.CreateModel(
            name='AIFindingFeedback',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_key', models.CharField(max_length=160)),
                ('rating', models.CharField(choices=[('USEFUL', 'Useful'), ('INCORRECT', 'Incorrect'), ('INCOMPLETE', 'Incomplete'), ('IRRELEVANT', 'Irrelevant'), ('OUTDATED', 'Outdated')], max_length=20)),
                ('correction', models.TextField(blank=True)),
                ('model_version', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(max_length=50)),
                ('retrieval_sources', models.JSONField(default=list)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending review'), ('EVALUATION', 'Approved for evaluation'), ('REJECTED', 'Rejected'), ('KNOWLEDGE', 'Approved for knowledge correction'), ('TRAINING', 'Approved for future training dataset')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finding_feedback', to='ai.aicaseassessment')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_finding_feedback', to='cases.case')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_feedback_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_feedback_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_finding_feedback',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeIndexEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_kind', models.CharField(max_length=30)),
                ('source_id', models.UUIDField()),
                ('source_version', models.PositiveIntegerField(default=1)),
                ('content_checksum', models.CharField(max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('INDEXED', 'Indexed'), ('WITHDRAWN', 'Withdrawn'), ('FAILED', 'Failed')], max_length=20)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'db_table': 'ai_knowledge_index_entries',
                'indexes': [models.Index(fields=['status', 'source_kind'], name='ai_index_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_kind', 'source_id'), name='unique_ai_index_source')],
            },
        ),
        migrations.CreateModel(
            name='MatterOutcome',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=80)),
                ('concluded_on', models.DateField()),
                ('forum', models.CharField(blank=True, max_length=180)),
                ('stage', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('orders', models.JSONField(blank=True, default=list)),
                ('claims', models.JSONField(blank=True, default=list)),
                ('important_factors', models.JSONField(blank=True, default=list)),
                ('material_evidence', models.JSONField(blank=True, default=list)),
                ('procedural_lessons', models.JSONField(blank=True, default=list)),
                ('appeal_filed', models.BooleanField(default=False)),
                ('quality_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('EXCLUDED', 'Excluded')], default='UNVERIFIED', max_length=20)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structured_outcome', to='cases.case')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_matter_outcomes',
            },
        ),
        migrations.AddConstraint(
            model_name='aiconfigurationversion',
            constraint=models.UniqueConstraint(fields=('kind', 'version'), name='unique_ai_configuration_version'),
        ),
    ]
