# Generated by Django 6.0.5 on 2026-08-02 02:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_aicaseassessment_change_summary_and_more'),
        ('firm', '0002_initial'),
        ('staff', '0003_alter_lawyerpermissiongrant_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAdvocateProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_published', models.BooleanField(default=False)),
                ('display_name', models.CharField(max_length=180)),
                ('public_bio', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_ai_profile', to='staff.lawyer')),
            ],
            options={
                'db_table': 'ai_public_advocate_profiles',
            },
        ),
        migrations.CreateModel(
            name='PublicFirmKnowledgePolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_published', models.BooleanField(default=False)),
                ('include_description', models.BooleanField(default=True)),
                ('include_practice_areas', models.BooleanField(default=True)),
                ('include_contact', models.BooleanField(default=False)),
                ('include_location', models.BooleanField(default=False)),
                ('include_hours', models.BooleanField(default=False)),
                ('include_branches', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('firm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_knowledge_policy', to='firm.lawfirm')),
            ],
            options={
                'db_table': 'ai_public_firm_knowledge_policies',
            },
        ),
    ]
