# Generated by Django 6.0.5 on 2026-08-03 09:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_publicadvocateprofile_publicfirmknowledgepolicy'),
        ('cases', '0020_physical_matter_file_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matteroutcome',
            name='appeal_review_status',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='matteroutcome',
            name='claim_or_exposure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='matteroutcome',
            name='costs_outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='matteroutcome',
            name='evidence_accepted',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='matteroutcome',
            name='evidence_rejected',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='matteroutcome',
            name='exclusion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='matteroutcome',
            name='final_disposition',
            field=models.CharField(choices=[('WON', 'Won'), ('LOST', 'Lost'), ('PARTLY_SUCCESSFUL', 'Partly successful'), ('SETTLED', 'Settled'), ('WITHDRAWN', 'Withdrawn'), ('DISMISSED', 'Struck out or dismissed'), ('ABANDONED', 'Abandoned'), ('TRANSFERRED', 'Transferred'), ('OTHER', 'Other')], default='OTHER', max_length=40),
        ),
        migrations.AddField(
            model_name='matteroutcome',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_matter_outcomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matteroutcome',
            name='settlement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='matteroutcome',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_matter_outcomes', to='cases.caseattachment'),
        ),
        migrations.AddField(
            model_name='matteroutcome',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AIAssessmentRecommendation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=60)),
                ('action', models.TextField()),
                ('reason', models.TextField(blank=True)),
                ('support', models.JSONField(blank=True, default=list)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('advocate_response', models.TextField(blank=True)),
                ('completion_note', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='cases.case')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_ai_recommendations', to=settings.AUTH_USER_MODEL)),
                ('created_assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structured_recommendations', to='ai.aicaseassessment')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_assessment_recommendations',
                'indexes': [models.Index(fields=['case', 'status', 'priority'], name='ai_rec_case_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIEventImpact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preparedness_delta', models.SmallIntegerField(default=0)),
                ('procedural_risk_delta', models.SmallIntegerField(default=0)),
                ('evidence_readiness_delta', models.SmallIntegerField(default=0)),
                ('legal_preparedness_delta', models.SmallIntegerField(default=0)),
                ('outlook_delta', models.SmallIntegerField(blank=True, null=True)),
                ('confidence_delta', models.SmallIntegerField(default=0)),
                ('direction', models.CharField(choices=[('IMPROVING', 'Improving'), ('STABLE', 'Stable'), ('DETERIORATING', 'Deteriorating'), ('INSUFFICIENT_DATA', 'Insufficient data')], max_length=24)),
                ('positive_factors', models.JSONField(blank=True, default=list)),
                ('negative_factors', models.JSONField(blank=True, default=list)),
                ('unchanged_factors', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField()),
                ('source_records', models.JSONField(default=list)),
                ('limitations', models.JSONField(default=list)),
                ('model_version', models.CharField(max_length=50)),
                ('scoring_version', models.CharField(max_length=50)),
                ('generated_at', models.DateTimeField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_event_impacts', to='cases.case')),
                ('new_assessment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='event_impact', to='ai.aicaseassessment')),
                ('previous_assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impacts_as_previous', to='ai.aicaseassessment')),
                ('triggering_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_impacts', to='cases.caseevent')),
            ],
            options={
                'db_table': 'ai_event_impacts',
                'constraints': [models.UniqueConstraint(fields=('triggering_event', 'previous_assessment'), name='unique_verified_event_impact')],
            },
        ),
    ]
