# Generated by Django 6.0.5 on 2026-08-03 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def assign_projected_firm_articles(apps, schema_editor):
    LawFirm = apps.get_model('firm', 'LawFirm')
    KnowledgeBaseArticle = apps.get_model('ai', 'KnowledgeBaseArticle')
    for firm in LawFirm.objects.all().iterator():
        slug = f"verified-public-firm-profile-{slugify(str(firm.id))}"
        KnowledgeBaseArticle.objects.filter(slug=slug).update(firm_id=firm.id)


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_matteroutcome_appeal_review_status_and_more'),
        ('firm', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='firm',
            field=models.ForeignKey(blank=True, help_text='Owning tenant for firm-specific public knowledge; null only for approved general legal information.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_knowledge_articles', to='firm.lawfirm'),
        ),
        migrations.AddField(
            model_name='knowledgebasequestionlog',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_ai_question_logs', to='firm.lawfirm'),
        ),
        migrations.RunPython(assign_projected_firm_articles, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='knowledgebasearticle',
            index=models.Index(fields=['firm', 'is_published'], name='kb_article_firm_public_idx'),
        ),
    ]
