# Generated by Django 6.0.5 on 2026-08-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_knowledgebasearticle_firm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicfirmknowledgepolicy',
            name='include_owner',
            field=models.BooleanField(default=False),
        ),
    ]
