# Generated by Django 6.0.5 on 2026-08-03 10:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def publish_existing_explicit_profiles(apps, schema_editor):
    Article = apps.get_model('ai', 'KnowledgeBaseArticle')
    Policy = apps.get_model('ai', 'PublicFirmKnowledgePolicy')
    now = timezone.now()
    for article in Article.objects.filter(firm__isnull=False, is_published=True):
        policy = Policy.objects.filter(firm_id=article.firm_id, is_published=True, approved_by__isnull=False).first()
        if not policy:
            article.is_published = False
            article.save(update_fields=('is_published',))
            continue
        article.visibility = 'public'
        article.approval_status = 'published'
        article.approved_by_id = policy.approved_by_id
        article.approved_at = policy.approved_at or now
        article.published_at = policy.approved_at or now
        article.source_type = 'firm_profile'
        article.public_category = 'firm_overview'
        article.save(update_fields=(
            'visibility', 'approval_status', 'approved_by', 'approved_at',
            'published_at', 'source_type', 'public_category',
        ))


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_publicfirmknowledgepolicy_include_owner'),
        ('firm', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicKnowledgeAudit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=30)),
                ('version', models.PositiveIntegerField()),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'public_knowledge_audits',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending approval'), ('approved', 'Approved'), ('published', 'Published'), ('withdrawn', 'Withdrawn'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='public_category',
            field=models.CharField(choices=[('firm_overview', 'Firm overview'), ('history', 'History'), ('practice_area', 'Practice area'), ('legal_service', 'Legal service'), ('advocate_biography', 'Public advocate biography'), ('office_location', 'Office location'), ('contact_information', 'Contact information'), ('working_hours', 'Working hours'), ('consultation', 'Consultation procedure'), ('appointment', 'Appointment information'), ('public_fees', 'Public fees information'), ('faq', 'Frequently asked questions'), ('careers', 'Careers'), ('announcement', 'Public announcement'), ('published_article', 'Published article'), ('complaints', 'Complaints procedure'), ('privacy_terms', 'Privacy and terms'), ('other', 'Other approved public information')], default='other', max_length=40),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='source_type',
            field=models.CharField(choices=[('firm_profile', 'Firm profile'), ('practice_area', 'Practice area'), ('public_page', 'Public website page'), ('public_policy', 'Public policy'), ('other', 'Other approved public information')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='withdrawn_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles_withdrawn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='knowledgebasearticle',
            index=models.Index(fields=['firm', 'visibility', 'approval_status', 'published_at'], name='kb_public_eligible_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebasearticle',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='kb_article_version_positive'),
        ),
        migrations.AddField(
            model_name='publicknowledgeaudit',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_knowledge_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicknowledgeaudit',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_audits', to='ai.knowledgebasearticle'),
        ),
        migrations.AddField(
            model_name='publicknowledgeaudit',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_knowledge_audits', to='firm.lawfirm'),
        ),
        migrations.AddIndex(
            model_name='publicknowledgeaudit',
            index=models.Index(fields=['firm', 'action', 'created_at'], name='public_kb_audit_idx'),
        ),
        migrations.RunPython(publish_existing_explicit_profiles, migrations.RunPython.noop),
    ]
