# Generated by Django 6.0.5 on 2026-09-23 06:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0011_secure_public_knowledge_publication'),
        ('cases', '0030_filing_register_kenyan_civil_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtPreparationBrief',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audience', models.CharField(choices=[('ADVOCATE', 'Advocate'), ('CLIENT', 'Client')], max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('readiness', models.PositiveSmallIntegerField(default=0)),
                ('checks', models.JSONField(blank=True, default=list)),
                ('guidance', models.JSONField(blank=True, default=dict)),
                ('tailored', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(default='structured', max_length=40)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('prompt_version', models.CharField(default='court-preparation-v1', max_length=40)),
                ('source_state_at', models.DateTimeField()),
                ('generated_at', models.DateTimeField()),
                ('is_current', models.BooleanField(default=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_briefs', to='cases.case')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_briefs', to='cases.caseevent')),
            ],
            options={
                'db_table': 'ai_court_preparation_briefs',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['event', 'audience', 'is_current'], name='ai_court_pr_event_i_723463_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'audience', 'version'), name='unique_court_preparation_brief_version')],
            },
        ),
    ]
