# Generated by Django 6.0.5 on 2026-09-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_court_preparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalprovision',
            name='unit_type',
            field=models.CharField(choices=[('preamble', 'Preamble'), ('article', 'Article'), ('schedule', 'Schedule'), ('section', 'Section')], max_length=20),
        ),
    ]
