# Generated by Django 6.0.5 on 2026-09-29 06:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0013_legal_provision_section_unit'),
        ('firm', '0004_firm_registration_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audience', models.CharField(choices=[('CLIENT', 'Client'), ('ADVOCATE', 'Advocate'), ('FIRM', 'Firm owner'), ('PLATFORM', 'Platform administrator')], max_length=20)),
                ('outcome', models.CharField(choices=[('ANSWERED', 'Answered by the AI model'), ('RECORDS_ONLY', 'Answered from records (no AI service)'), ('ERROR', 'AI service failed; answered from records')], max_length=20)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('matters_in_context', models.PositiveIntegerField(default=0)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_usage', to='firm.lawfirm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['firm', 'audience', 'created_at'], name='ai_assistan_firm_id_ef2d43_idx')],
            },
        ),
    ]
