import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useParams } from 'react-router-dom';
import axiosInstance from '@/core/api/axios';
import BackLink from '@/components/ui/BackLink';
import SectionHeading from '@/components/ui/SectionHeading';

const panel = 'rounded-xl border border-border-light bg-surface-light p-5 dark:border-border-dark dark:bg-surface-dark';
const Items = ({ values }) => values?.length ? <ul className='mt-2 list-disc space-y-1 pl-5 text-sm'>{values.map((x, i) => <li key={`${i}-${x.action || x.message || x}`}>{x.action || x.message || x}</li>)}</ul> : <p className='mt-2 text-sm text-text-muted-light'>None identified in the authorized records.</p>;

export default function AdminCaseAIAnalysisPage() {
  const { id } = useParams(); const queryClient = useQueryClient(); const [selected, setSelected] = useState([]);
  const query = useQuery({ queryKey: ['firm-ai-matter', id], queryFn: async () => (await axiosInstance.get(`/admin/ai/matters/${id}/`)).data });
  const generate = useMutation({ mutationFn: async () => (await axiosInstance.post(`/admin/ai/matters/${id}/assessments/`, { document_ids: selected })).data, onSuccess: () => queryClient.invalidateQueries({ queryKey: ['firm-ai-matter', id] }) });
  if (query.isLoading) return <p role='status' className='p-8'>Loading matter intelligence workspace…</p>;
  if (query.error) return <div role='alert' className='m-6 rounded-xl bg-red-50 p-4 text-red-800'>{query.error.response?.status === 403 ? 'Firm-wide AI oversight permission is required.' : 'This matter is unavailable.'}</div>;
  const data = query.data; const a = data.assessment; const matter = a?.matter || data.matter;
  return <main className='space-y-5 p-4 md:p-6'><BackLink label='Back to Firm AI Matter Intelligence' fallbackPath='/admin/ai/matters'/><SectionHeading title={matter.title} subtitle={`${matter.case_number || ''}${matter.official_case_number ? ` · ${matter.official_case_number}` : ''}`} size='compact'/><div role='note' className='rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950'>{data.disclaimer}</div>
    <section className={panel}><div className='flex flex-wrap justify-between gap-3'><div><h2 className='text-lg font-bold'>Matter header</h2><p>{matter.client} · {matter.assigned_advocate || 'Unassigned'} · {matter.practice_area} · {matter.court_stage}</p>{a && <p className='text-sm'>Assessment version {a.version} · {new Date(a.analyzed_at).toLocaleString('en-KE', { timeZone: 'Africa/Nairobi' })} · {a.is_stale ? 'Requires reassessment' : 'Current'}</p>}</div><button disabled={generate.isPending} onClick={() => generate.mutate()} className='rounded-lg bg-success px-4 py-2 font-bold text-white disabled:opacity-50'>{generate.isPending ? 'Assessing…' : a ? 'Reassess matter' : 'Generate assessment'}</button></div></section>
    <section className={panel}><h2 className='text-lg font-bold'>Explicit document selection</h2><p className='text-sm'>Only selected, authorized documents are analyzed. Confidential material remains confidential; presence does not prove authenticity.</p>{data.available_documents.map(doc => <label key={doc.id} className='mt-2 flex gap-2 text-sm'><input type='checkbox' checked={selected.includes(doc.id)} onChange={() => setSelected(v => v.includes(doc.id) ? v.filter(x => x !== doc.id) : [...v, doc.id])}/>{doc.title} · {doc.type}{doc.confidential ? ' · Confidential' : ''}</label>)}</section>
    {!a && <section className={panel}>No assessment exists. Deterministic preparedness and risk scoring remains available without an external AI provider.</section>}
    {a && <><section className={panel}><h2 className='text-lg font-bold'>Executive assessment · {a.priority} priority</h2><div className='mt-3 grid grid-cols-2 gap-3 md:grid-cols-4'>{Object.entries(a.component_scores).map(([key,value]) => <div key={key} className='rounded-lg bg-black/5 p-3'><span className='block text-xs'>{key.replaceAll('_',' ')}</span><strong>{value}/100</strong></div>)}</div>{Object.entries(a.component_reasons).map(([key,value]) => <div key={key} className='mt-3'><h3 className='font-semibold'>{key.replaceAll('_',' ')}</h3><Items values={value}/></div>)}</section>
    <section className={panel}><h2 className='text-lg font-bold'>Critical alerts and gaps</h2><Items values={a.alerts}/><Items values={a.gaps}/></section>
    <section className={panel}><h2 className='text-lg font-bold'>Recommendations</h2>{a.recommendations.map(r => <article key={r.id} className='mt-3 rounded-lg border p-3 text-sm'><strong>{r.priority} · {r.category} · {r.status}</strong><p>{r.action}</p><p>{r.reason}</p>{r.due_date && <p>Due {r.due_date}</p>}</article>)}</section>
    <section className={panel}><h2 className='text-lg font-bold'>Proceedings and event intelligence</h2>{a.progression.map(e => <article key={e.id} className='mt-3 border-l-2 border-brand-primary pl-3'><strong>{e.type} · {e.status}</strong><p className='text-sm'>{e.scheduled_at ? new Date(e.scheduled_at).toLocaleString('en-KE') : 'No date'} · {e.court || 'Forum not recorded'} · {e.verified ? 'Advocate verified' : 'Unverified—excluded from formal outlook'}</p>{e.outcome && <p>{e.outcome}</p>}</article>)}</section>
    <section className={panel}><h2 className='text-lg font-bold'>Documents and evidence</h2>{a.documents.map(d => <p key={d.id} className='mt-2 text-sm'><strong>{d.title}</strong> · {d.selected ? 'Selected' : 'Not selected'} · {d.authenticity_warning}</p>)}<Items values={a.gaps}/></section>
    <section className={panel}><h2 className='text-lg font-bold'>Legal analysis</h2><p className='text-sm'>Authorities are official-source research suggestions until independently verified by an advocate.</p>{a.legal_analysis.authorities?.map(s => <a key={`${s.url}-${s.article}`} href={s.url} target='_blank' rel='noreferrer' className='mt-2 block rounded border p-3 underline'>{s.title}, Article {s.article} · verified {s.last_verified_at || 'date unavailable'}</a>)}<Items values={a.legal_analysis.limitations}/></section>
    <section className={panel}><h2 className='text-lg font-bold'>Outcome scenarios</h2>{a.outcome_scenarios.map(s => <article key={s.label} className='mt-3 rounded border p-3'><strong>{s.label}</strong><p>{s.description}</p><Items values={s.assumptions}/></article>)}<p className='mt-4 font-semibold'>AI-assisted assessed outlook: Insufficient verified data for an outcome range. Confidence: {a.confidence}.</p></section>
    <section className={panel}><h2 className='text-lg font-bold'>Comparable matters</h2><p>Authorized anonymized sample size: {a.comparable_matters.sample_size}</p><Items values={a.comparable_matters.selection_criteria}/><Items values={a.comparable_matters.limitations}/></section>
    <section className={panel}><h2 className='text-lg font-bold'>Immutable assessment history</h2>{data.history.map(h => <p key={h.id} className='mt-2 rounded border p-3'>Version {h.version} · {h.priority} · {new Date(h.analyzed_at).toLocaleString('en-KE')} · {h.is_stale ? 'Stale or superseded' : 'Current'} · {h.model_version} / {h.scoring_version}</p>)}</section></>}
  </main>;
}
