from django.urls import path

from apps.clients.views.admin import (
    ClientAdminAssignView,
    ClientAdminDashboardView,
    ClientAdminDeleteView,
    ClientAdminDetailView,
    ClientAdminLawyersView,
    ClientAdminListView,
    ClientAdminRemoveLawyerView,
    ClientAdminStatisticsView,
    ClientAdminStatusView,
    CompanyAdminCreateClientView,
    CooperativeAdminCreateClientView,
    EducationalInstitutionAdminCreateClientView,
    EstateAdminCreateClientView,
    GovernmentAdminCreateClientView,
    IndividualAdminCreateClientView,
    NGOAdminCreateClientView,
    PartnershipAdminCreateClientView,
    ReligiousOrganizationAdminCreateClientView,
    AssociationAdminCreateClientView,
    SaccoAdminCreateClientView,
    TrustAdminCreateClientView,
    CanonicalCooperativeAdminCreateClientView,
    CanonicalEstateAdminCreateClientView,
    CanonicalPartnershipAdminCreateClientView,
    CanonicalTrustAdminCreateClientView,
    InternationalOrganizationAdminCreateClientView,
    LegalEntityAdminCreateClientView,
    LimitedLiabilityPartnershipAdminCreateClientView,
    NonProfitOrganizationAdminCreateClientView,
    PublicEntityAdminCreateClientView,
    SocietyAssociationAdminCreateClientView,
    SoleProprietorshipAdminCreateClientView,
)

urlpatterns = [
    path("", ClientAdminListView.as_view(), name="admin-client-list"),
    path("individuals/create/", IndividualAdminCreateClientView.as_view(), name="admin-individual-client-create"),
    path("companies/create/", CompanyAdminCreateClientView.as_view(), name="admin-company-client-create"),
    path("legal-entities/create/", LegalEntityAdminCreateClientView.as_view(), name="admin-legal-entity-client-create"),
    path("sole-proprietorships/create/", SoleProprietorshipAdminCreateClientView.as_view(), name="admin-sole-proprietorship-client-create"),
    path("llps/create/", LimitedLiabilityPartnershipAdminCreateClientView.as_view(), name="admin-llp-client-create"),
    path("societies-associations/create/", SocietyAssociationAdminCreateClientView.as_view(), name="admin-society-association-client-create"),
    path("nonprofits/create/", NonProfitOrganizationAdminCreateClientView.as_view(), name="admin-nonprofit-client-create"),
    path("public-entities/create/", PublicEntityAdminCreateClientView.as_view(), name="admin-public-entity-client-create"),
    path("international-organizations/create/", InternationalOrganizationAdminCreateClientView.as_view(), name="admin-international-organization-client-create"),

    # Compatibility paths preserved while the UI migrates to legal-capacity names.
    path("canonical/cooperatives/create/", CanonicalCooperativeAdminCreateClientView.as_view(), name="admin-canonical-cooperative-client-create"),
    path("canonical/partnerships/create/", CanonicalPartnershipAdminCreateClientView.as_view(), name="admin-canonical-partnership-client-create"),
    path("canonical/trusts/create/", CanonicalTrustAdminCreateClientView.as_view(), name="admin-canonical-trust-client-create"),
    path("canonical/estates/create/", CanonicalEstateAdminCreateClientView.as_view(), name="admin-canonical-estate-client-create"),
    path("saccos/create/", SaccoAdminCreateClientView.as_view(), name="admin-sacco-client-create"),
    path("cooperatives/create/", CooperativeAdminCreateClientView.as_view(), name="admin-cooperative-client-create"),
    path("partnerships/create/", PartnershipAdminCreateClientView.as_view(), name="admin-partnership-client-create"),
    path("ngos/create/", NGOAdminCreateClientView.as_view(), name="admin-ngo-client-create"),
    path("associations/create/", AssociationAdminCreateClientView.as_view(), name="admin-association-client-create"),
    path("religious-organizations/create/", ReligiousOrganizationAdminCreateClientView.as_view(), name="admin-religious-organization-client-create"),
    path("trusts/create/", TrustAdminCreateClientView.as_view(), name="admin-trust-client-create"),
    path("estates/create/", EstateAdminCreateClientView.as_view(), name="admin-estate-client-create"),
    path("government/create/", GovernmentAdminCreateClientView.as_view(), name="admin-government-client-create"),
    path("educational-institutions/create/", EducationalInstitutionAdminCreateClientView.as_view(), name="admin-educational-institution-client-create"),
    path("dashboard/", ClientAdminDashboardView.as_view(), name="admin-client-dashboard"),
    path("statistics/", ClientAdminStatisticsView.as_view(), name="admin-client-statistics"),
    path("<uuid:client_id>/", ClientAdminDetailView.as_view(), name="admin-client-detail"),
    path("<uuid:client_id>/activate/", ClientAdminStatusView.as_view(), name="admin-client-activate"),
    path("<uuid:client_id>/deactivate/", ClientAdminStatusView.as_view(), name="admin-client-deactivate"),
    path("<uuid:client_id>/change-status/", ClientAdminStatusView.as_view(), name="admin-client-change-status"),
    path("<uuid:client_id>/lawyers/", ClientAdminLawyersView.as_view(), name="admin-client-lawyers"),
    path("<uuid:client_id>/assign-lawyer/", ClientAdminAssignView.as_view(), name="admin-client-assign-lawyer"),
    path("<uuid:client_id>/remove-lawyer/<uuid:lawyer_id>/", ClientAdminRemoveLawyerView.as_view(), name="admin-client-remove-lawyer"),
    path("<uuid:client_id>/delete/", ClientAdminDeleteView.as_view(), name="admin-client-delete"),
]
