# Generated by Django 6.0.5 on 2026-07-31 11:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0016_caseevent_track'),
        ('clients', '0016_clientdocument_reference_clientdocument_review_notes_and_more'),
        ('firm', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=50)),
                ('instructions', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Required'), ('UPLOADED', 'Uploaded - awaiting review'), ('ACCEPTED', 'Accepted'), ('REPLACEMENT_REQUIRED', 'Replacement required'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=30)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='cases.case')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='clients.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='firm.lawfirm')),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_document_requests', to=settings.AUTH_USER_MODEL)),
                ('fulfilled_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_requests', to='clients.clientdocument')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_document_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_requests',
                'ordering': ['status', 'due_date', '-created_at'],
                'indexes': [models.Index(fields=['case', 'status'], name='document_re_case_id_dca85a_idx'), models.Index(fields=['client', 'status'], name='document_re_client__aa3dd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatterDocumentReference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('CLIENT_INSTRUCTION', 'Client instruction'), ('EVIDENCE', 'Evidence'), ('CORRESPONDENCE', 'Correspondence'), ('DEMAND_LETTER', 'Demand letter'), ('PLEADING', 'Pleading'), ('COURT_DOCUMENT', 'Court document'), ('OTHER', 'Other')], default='OTHER', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_references', to='cases.case')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matter_references', to='clients.clientdocument')),
                ('referenced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matter_document_references', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matter_document_references',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('case', 'document'), name='unique_document_reference_per_matter')],
            },
        ),
    ]
