# Generated by Django 5.2.16 on 2026-08-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matterdocumentreference',
            name='purpose',
            field=models.CharField(choices=[('CLIENT_INSTRUCTION', 'Client instruction'), ('EVIDENCE', 'Evidence'), ('CORRESPONDENCE', 'Correspondence'), ('DEMAND_LETTER', 'Demand letter'), ('PLEADING', 'Pleading'), ('COURT_DOCUMENT', 'Court document'), ('KYC_DOCUMENT', 'KYC document'), ('OTHER', 'Other')], default='OTHER', max_length=40),
        ),
    ]
