# Generated by Django 6.0.5 on 2026-08-01 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_caseattachmentreferencesequence_and_more'),
        ('clients', '0022_clientdocumentcustodymovement_and_more'),
        ('documents', '0004_alter_documentrequest_status'),
        ('firm', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matterdocumentreference',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DocumentRequirementTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('PROSPECTIVE_KYC', 'Prospective client / KYC'), ('PROPOSED_MATTER', 'Proposed matter'), ('CONFLICT_CHECK', 'Conflict check'), ('FIRM_ACCEPTANCE', 'Firm acceptance'), ('MATTER_OPENING', 'Matter opening'), ('PRE_FILING', 'Pre-filing'), ('FILING', 'Filing'), ('HEARING', 'Hearing'), ('CLOSURE', 'Closure')], max_length=30)),
                ('document_category', models.CharField(blank=True, default='', max_length=40)),
                ('document_subtype', models.CharField(blank=True, default='', max_length=50)),
                ('client_type', models.CharField(blank=True, default='', max_length=50)),
                ('practice_area', models.CharField(blank=True, default='', max_length=100)),
                ('matter_nature', models.CharField(blank=True, default='', max_length=100)),
                ('forum', models.CharField(blank=True, default='', max_length=100)),
                ('procedure', models.CharField(blank=True, default='', max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirement_templates', to='firm.lawfirm')),
            ],
            options={
                'db_table': 'document_requirement_templates',
                'ordering': ['stage', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_client_visible', models.BooleanField(default=False)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='cases.case')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_requirements', to='clients.client')),
                ('proposed_matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='clients.clientmatterconflictcheck')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_document_requirements', to=settings.AUTH_USER_MODEL)),
                ('selected_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='satisfied_requirements', to='clients.clientdocument')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='documents.documentrequirementtemplate')),
            ],
            options={
                'db_table': 'document_requirements',
            },
        ),
        migrations.CreateModel(
            name='PhysicalDocumentReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=60)),
                ('received_from', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField()),
                ('firm_details_snapshot', models.JSONField(default=dict)),
                ('kyc_reference_snapshot', models.CharField(max_length=40)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_receipts', to='clients.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_document_receipts', to='firm.lawfirm')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_document_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'physical_document_receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalDocumentReceiptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_reference_snapshot', models.CharField(max_length=80)),
                ('title_snapshot', models.CharField(max_length=255)),
                ('subtype_snapshot', models.CharField(max_length=50)),
                ('copy_type_snapshot', models.CharField(max_length=30)),
                ('page_count_snapshot', models.PositiveIntegerField()),
                ('condition_snapshot', models.TextField(blank=True, default='')),
                ('return_required_snapshot', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='clients.clientdocument')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='documents.physicaldocumentreceipt')),
            ],
            options={
                'db_table': 'physical_document_receipt_items',
            },
        ),
        migrations.CreateModel(
            name='ProposedMatterDocumentReference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=255)),
                ('relevance_notes', models.TextField(blank=True, default='')),
                ('required_status', models.CharField(choices=[('REQUIRED', 'Required'), ('OPTIONAL', 'Optional'), ('SUPPORTING', 'Supporting record')], default='SUPPORTING', max_length=20)),
                ('review_status', models.CharField(choices=[('NOT_REVIEWED', 'Not reviewed'), ('SUFFICIENT', 'Sufficient'), ('INSUFFICIENT', 'Insufficient'), ('REPLACEMENT_REQUIRED', 'Replacement required')], default='NOT_REVIEWED', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removal_reason', models.TextField(blank=True, default='')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_matter_references', to='clients.clientdocument')),
                ('proposed_matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_references', to='clients.clientmatterconflictcheck')),
                ('referenced_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_document_references', to=settings.AUTH_USER_MODEL)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='removed_proposed_document_references', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proposed_matter_document_references',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='matterdocumentreference',
            name='originating_proposed_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_matter_references', to='documents.proposedmatterdocumentreference'),
        ),
        migrations.AddConstraint(
            model_name='physicaldocumentreceipt',
            constraint=models.UniqueConstraint(fields=('firm', 'receipt_number'), name='unique_physical_receipt_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='physicaldocumentreceiptitem',
            constraint=models.UniqueConstraint(fields=('receipt', 'document'), name='unique_document_per_receipt'),
        ),
        migrations.AddConstraint(
            model_name='proposedmatterdocumentreference',
            constraint=models.UniqueConstraint(fields=('proposed_matter', 'document'), name='unique_document_reference_per_proposed_matter'),
        ),
    ]
