# Generated by Django 6.0.5 on 2026-08-01 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_matterdocumentreference_is_active_and_more'),
        ('firm', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalDocumentReceiptSequence',
            fields=[
                ('firm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='physical_receipt_sequence', serialize=False, to='firm.lawfirm')),
                ('year', models.PositiveIntegerField()),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'physical_document_receipt_sequences',
            },
        ),
    ]
