# Generated by Django 6.0.5 on 2026-08-01 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_caseattachmentreferencesequence_and_more'),
        ('clients', '0024_clientdocument_is_client_visible'),
        ('documents', '0006_physicaldocumentreceiptsequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='documentrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('proposed_matter__isnull', False)), fields=('template', 'proposed_matter'), name='unique_template_per_proposed_matter'),
        ),
        migrations.AddConstraint(
            model_name='documentrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('case__isnull', False)), fields=('template', 'case'), name='unique_template_per_matter'),
        ),
    ]
