# Generated by Django 6.0.5 on 2026-08-01 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documentrequirement_unique_template_per_proposed_matter_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='proposedmatterdocumentreference',
            name='unique_document_reference_per_proposed_matter',
        ),
        migrations.RemoveField(
            model_name='matterdocumentreference',
            name='originating_proposed_reference',
        ),
        migrations.DeleteModel(
            name='ProposedMatterDocumentReference',
        ),
    ]
