# Generated by Django 6.0.5 on 2026-07-16 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0005_rename_case_events_is_virt_3d4a2b_idx_case_events_is_virt_46cf81_idx'),
        ('clients', '0003_add_specific_organization_client_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventClientAwareness',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOT_NOTIFIED', 'Not Notified'), ('NOTIFIED', 'Notified'), ('CONFIRMED', 'Confirmed'), ('UNREACHABLE', 'Unreachable'), ('DECLINED', 'Declined')], default='NOT_NOTIFIED', max_length=30)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_channel', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_awareness_records', to='clients.client')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_awareness', to='cases.caseevent')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_event_awareness_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_client_awareness',
                'ordering': ['event__starts_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='event_clien_client__8643ac_idx'), models.Index(fields=['status', 'notified_at'], name='event_clien_status_34b55f_idx')],
            },
        ),
    ]
