export const ROLES = {
  PLATFORM_ADMIN: "PLATFORM_ADMIN",
  ADMIN: "ADMIN",
  CLIENT: "CLIENT",

  STAFF: "STAFF",
  LAWYER: "LAWYER",
  SECRETARY: "SECRETARY",
  ACCOUNTANT: "ACCOUNTANT",
  HR: "HR",
  IT: "IT",
};
