# Generated by Django 6.0.5 on 2026-07-16 04:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Branch name (e.g. Nairobi Head Office).', max_length=255)),
                ('code', models.CharField(blank=True, help_text='Optional unique branch code.', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('physical_address', models.TextField(blank=True)),
                ('postal_address', models.CharField(blank=True, max_length=255)),
                ('is_head_office', models.BooleanField(default=False, help_text="Indicates whether this is the firm's main office.")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'db_table': 'firm_branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Department name.', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'firm_departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FirmSetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=100)),
                ('language', models.CharField(default='English', max_length=50)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('work_on_saturday', models.BooleanField(default=False)),
                ('work_on_sunday', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('browser_notifications', models.BooleanField(default=True)),
                ('allow_client_registration', models.BooleanField(default=False)),
                ('allow_client_document_upload', models.BooleanField(default=True)),
                ('allow_client_case_tracking', models.BooleanField(default=True)),
                ('require_password_change', models.BooleanField(default=True)),
                ('enable_two_factor_authentication', models.BooleanField(default=False)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60)),
                ('enable_ai_assistant', models.BooleanField(default=True)),
                ('enable_ai_case_suggestions', models.BooleanField(default=True)),
                ('enable_ai_deadline_reminders', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Firm Setting',
                'verbose_name_plural': 'Firm Settings',
                'db_table': 'firm_settings',
            },
        ),
        migrations.CreateModel(
            name='LawFirm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Registered name of the law firm.', max_length=255, unique=True)),
                ('registration_number', models.CharField(help_text='Official law firm registration number.', max_length=100, unique=True)),
                ('kra_pin', models.CharField(blank=True, help_text='Kenya Revenue Authority PIN.', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('physical_address', models.TextField(blank=True)),
                ('postal_address', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='firms/logos/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Law Firm',
                'verbose_name_plural': 'Law Firms',
                'db_table': 'law_firms',
            },
        ),
        migrations.CreateModel(
            name='LawFirmMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('LAWYER', 'Lawyer'), ('SECRETARY', 'Secretary'), ('IT', 'IT Support'), ('ACCOUNTANT', 'Accountant'), ('HR', 'Human Resource'), ('OFFICIAL_CLIENT', 'Official Client')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'firm_members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the legal practice area.', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Practice Area',
                'verbose_name_plural': 'Practice Areas',
                'db_table': 'practice_areas',
                'ordering': ['name'],
            },
        ),
    ]
