# Generated by Django 6.0.5 on 2026-07-16 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_leader',
            field=models.ForeignKey(blank=True, help_text='Staff member responsible for this branch. Defaults to the firm owner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Optional branch where this department belongs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='firm.branch'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, help_text='Staff member responsible for this department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='owner',
            field=models.OneToOneField(help_text='Managing Partner and owner of the law firm.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_firm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='firmsetting',
            name='firm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='firm.lawfirm'),
        ),
        migrations.AddField(
            model_name='department',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='firm.lawfirm'),
        ),
        migrations.AddField(
            model_name='branch',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='firm.lawfirm'),
        ),
        migrations.AddField(
            model_name='lawfirmmember',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_firm_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lawfirmmember',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='firm.lawfirm'),
        ),
        migrations.AddField(
            model_name='lawfirmmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practicearea',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_areas', to='firm.lawfirm'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('firm', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('firm', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='lawfirmmember',
            unique_together={('firm', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='practicearea',
            unique_together={('firm', 'name')},
        ),
    ]
