# Generated by Django 6.0.5 on 2026-08-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmsetting',
            name='allow_engagement_waiver',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='firmsetting',
            name='require_independent_engagement_waiver_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='firmsetting',
            name='require_retainer_before_matter_opening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firmsetting',
            name='require_signed_engagement_for_matter_opening',
            field=models.BooleanField(default=True),
        ),
    ]
