# Generated by Django 6.0.5 on 2026-09-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0003_firmsetting_allow_engagement_waiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawfirm',
            name='business_structure',
            field=models.CharField(choices=[('SOLE_PRACTITIONER', 'Sole practitioner'), ('PARTNERSHIP', 'Partnership'), ('LLP', 'Limited liability partnership')], db_default='PARTNERSHIP', default='PARTNERSHIP', max_length=30),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='county',
            field=models.CharField(blank=True, db_default='', help_text='County of the head office.', max_length=60),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='town',
            field=models.CharField(blank=True, db_default='', max_length=100),
        ),
    ]
