# Generated by Django 6.0.5 on 2026-08-04 13:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0021_caseevent_compliance_obligations_and_more'),
        ('clients', '0031_clientcompliancereview_clientcompliancehistory_and_more'),
        ('firm', '0003_firmsetting_allow_engagement_waiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('OFFICE', 'Office account'), ('CLIENT', 'Client account')], max_length=16)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('account_reference', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_accounts', to='firm.lawfirm')),
            ],
            options={
                'db_table': 'billing_financial_accounts',
            },
        ),
        migrations.CreateModel(
            name='AccountReconciliation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_end', models.DateField()),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('ledger_balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=16)),
                ('reconciliation_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved')], default='DRAFT', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_reconciliations', to='firm.lawfirm')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='billing.financialaccount')),
            ],
            options={
                'db_table': 'billing_account_reconciliations',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=60)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('professional_fees', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('disbursements_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('ISSUED', 'Issued'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled'), ('CREDITED', 'Credited'), ('LEGACY_REVIEW_REQUIRED', 'Legacy review required')], db_index=True, default='DRAFT', max_length=32)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_invoices', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='firm.lawfirm')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='cases.case')),
                ('supporting_documents', models.ManyToManyField(blank=True, related_name='supported_invoices', to='clients.clientdocument')),
            ],
            options={
                'db_table': 'billing_invoices',
            },
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disbursement_type', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('supplier_payee', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('date_incurred', models.DateField()),
                ('funding_source', models.CharField(choices=[('FIRM', 'Paid by firm'), ('CLIENT_MONEY', 'Paid from client funds')], max_length=16)),
                ('recoverable_from_client', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=16)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_disbursements', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_disbursements', to=settings.AUTH_USER_MODEL)),
                ('evidence_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidenced_disbursements', to='clients.clientdocument')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='firm.lawfirm')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='cases.case')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='billing.invoice')),
            ],
            options={
                'db_table': 'billing_disbursements',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_type', models.CharField(choices=[('PROFESSIONAL_FEE', 'Professional fee'), ('TAX', 'Tax'), ('DISBURSEMENT', 'Disbursement'), ('DISCOUNT', 'Discount'), ('ADJUSTMENT', 'Adjustment')], max_length=24)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='billing.invoice')),
            ],
            options={
                'db_table': 'billing_invoice_lines',
            },
        ),
        migrations.CreateModel(
            name='MatterClientLedger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('cleared_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_ledgers', to='clients.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_ledgers', to='firm.lawfirm')),
                ('matter', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='client_ledger', to='cases.case')),
            ],
            options={
                'db_table': 'billing_matter_client_ledgers',
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('CLIENT_RECEIPT', 'Client-money receipt'), ('CLIENT_PAYMENT', 'Client-money payment'), ('TRANSFER_TO_OFFICE', 'Transfer to office account'), ('OFFICE_RECEIPT', 'Office-money receipt'), ('REVERSAL', 'Reversal'), ('ADJUSTMENT', 'Controlled adjustment')], max_length=24)),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('narrative', models.TextField()),
                ('bank_reference', models.CharField(blank=True, default='', max_length=150)),
                ('basis', models.TextField(blank=True, default='')),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='billing.financialaccount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_transactions', to='clients.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_transactions', to='firm.lawfirm')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_transactions', to='cases.case')),
                ('original_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entries', to='billing.ledgertransaction')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posted_ledger_transactions', to=settings.AUTH_USER_MODEL)),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='billing.matterclientledger')),
            ],
            options={
                'db_table': 'billing_ledger_transactions',
                'ordering': ['posted_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInstruction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('beneficiary_details', models.JSONField(default=dict)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('purpose', models.TextField()),
                ('payment_basis', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING_APPROVAL', max_length=24)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_instructions', to='billing.financialaccount')),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checked_payment_instructions', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_instructions', to='firm.lawfirm')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_instructions', to='billing.matterclientledger')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='made_payment_instructions', to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_instructions', to='cases.case')),
                ('posted_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_instruction', to='billing.ledgertransaction')),
                ('supporting_documents', models.ManyToManyField(blank=True, related_name='supported_payment_instructions', to='clients.clientdocument')),
            ],
            options={
                'db_table': 'billing_payment_instructions',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=60)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank transfer'), ('CHEQUE', 'Cheque'), ('CARD', 'Card'), ('MOBILE_MONEY', 'Mobile money'), ('OTHER', 'Other')], max_length=20)),
                ('bank_transaction_reference', models.CharField(max_length=150)),
                ('reversal_reason', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='billing.financialaccount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='clients.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='firm.lawfirm')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='cases.case')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_receipts', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reverses_receipt', to='billing.receipt')),
                ('supporting_proof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supported_receipts', to='clients.clientdocument')),
            ],
            options={
                'db_table': 'billing_receipts',
            },
        ),
        migrations.CreateModel(
            name='ReceiptAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocation_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('RETAINER', 'Retainer'), ('CLIENT_MONEY', 'Client money'), ('DISBURSEMENT', 'Disbursement')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_allocations', to='billing.invoice')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='billing.receipt')),
            ],
            options={
                'db_table': 'billing_receipt_allocations',
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=255)),
                ('entry_date', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('billable', models.BooleanField(default=True)),
                ('narrative', models.TextField()),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=16)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_time_entries', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='firm.lawfirm')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='billing.invoice')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='cases.case')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_time_entries',
            },
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.UniqueConstraint(fields=('firm', 'account_reference'), name='unique_financial_account_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='accountreconciliation',
            constraint=models.UniqueConstraint(fields=('account', 'period_end'), name='unique_reconciliation_period_per_account'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('firm', 'invoice_number'), name='unique_invoice_number_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='invoice_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='invoice_paid_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='invoice_balance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='disbursement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='disbursement_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='invoice_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='matterclientledger',
            constraint=models.CheckConstraint(condition=models.Q(('cleared_balance__gte', 0)), name='client_ledger_balance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='ledgertransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledger_transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentinstruction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_instruction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('firm', 'receipt_number'), name='unique_receipt_number_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('amount_received__gt', 0)), name='receipt_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='receiptallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='receipt_allocation_positive'),
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='time_entry_duration_positive'),
        ),
    ]
