# Generated by Django 6.0.5 on 2026-08-04 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgertransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_transactions', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_transactions', to='billing.receipt'),
        ),
    ]
