# Generated by Django 6.0.5 on 2026-08-04 14:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_ledgertransaction_invoice_ledgertransaction_receipt'),
        ('cases', '0026_deadlinestatushistory'),
        ('clients', '0033_documentreleaserequest'),
        ('firm', '0003_firmsetting_allow_engagement_waiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_note_number', models.CharField(max_length=60)),
                ('credit_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled')], default='PENDING_APPROVAL', max_length=24)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'billing_credit_notes',
            },
        ),
        migrations.CreateModel(
            name='ReceiptReversal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('reversed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_receipt_reversals',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='credited_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='disbursement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_line', to='billing.disbursement'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='time_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_line', to='billing.timeentry'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('credited_amount__gte', 0)), name='invoice_credited_nonnegative'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_credit_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='clients.client'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_credit_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='firm.lawfirm'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='cases.case'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='supporting_documents',
            field=models.ManyToManyField(blank=True, related_name='supported_credit_notes', to='clients.clientdocument'),
        ),
        migrations.AddField(
            model_name='receiptreversal',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_reversals', to='firm.lawfirm'),
        ),
        migrations.AddField(
            model_name='receiptreversal',
            name='original_receipt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal_record', to='billing.receipt'),
        ),
        migrations.AddField(
            model_name='receiptreversal',
            name='original_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_reversal_sources', to='billing.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='receiptreversal',
            name='reversal_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_reversal_record', to='billing.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='receiptreversal',
            name='reversed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_receipt_reversals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.UniqueConstraint(fields=('firm', 'credit_note_number'), name='unique_credit_note_number_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='credit_note_amount_positive'),
        ),
    ]
