# Generated by Django 6.0.5 on 2026-08-04 14:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_creditnote_receiptreversal_invoice_credited_amount_and_more'),
        ('cases', '0026_deadlinestatushistory'),
        ('clients', '0033_documentreleaserequest'),
        ('firm', '0003_firmsetting_allow_engagement_waiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgertransaction',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_transactions', to='clients.engagementrecord'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retainer_receipts', to='clients.engagementrecord'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='proposed_matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retainer_receipts', to='clients.clientmatterconflictcheck'),
        ),
        migrations.AddField(
            model_name='receiptallocation',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_allocations', to='clients.engagementrecord'),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_transactions', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CLIENT_RECEIPT', 'Client-money receipt'), ('CLIENT_PAYMENT', 'Client-money payment'), ('TRANSFER_TO_OFFICE', 'Transfer to office account'), ('OFFICE_RECEIPT', 'Office-money receipt'), ('REVERSAL', 'Reversal'), ('ADJUSTMENT', 'Controlled adjustment'), ('RETAINER_RECEIPT', 'Pre-matter retainer receipt'), ('RETAINER_ALLOCATION', 'Retainer allocated to opened matter')], max_length=24),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='cases.case'),
        ),
        migrations.CreateModel(
            name='ClientFundsLedger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('cleared_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='unallocated_funds_ledger', to='clients.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unallocated_client_funds_ledgers', to='firm.lawfirm')),
            ],
            options={
                'db_table': 'billing_client_funds_ledgers',
            },
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='client_funds_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='billing.clientfundsledger'),
        ),
        migrations.AddConstraint(
            model_name='clientfundsledger',
            constraint=models.UniqueConstraint(fields=('firm', 'client'), name='unique_unallocated_funds_ledger_per_client'),
        ),
        migrations.AddConstraint(
            model_name='clientfundsledger',
            constraint=models.CheckConstraint(condition=models.Q(('cleared_balance__gte', 0)), name='unallocated_client_funds_nonnegative'),
        ),
    ]
