# Generated by Django 6.0.5 on 2026-08-04 14:35

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_ledgertransaction_engagement_receipt_engagement_and_more'),
        ('cases', '0026_deadlinestatushistory'),
        ('clients', '0033_documentreleaserequest'),
        ('firm', '0003_firmsetting_allow_engagement_waiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__lte', django.db.models.expressions.CombinedExpression(models.F('total_amount'), '-', models.F('credited_amount')))), name='invoice_paid_and_credited_within_total'),
        ),
        migrations.AddConstraint(
            model_name='ledgertransaction',
            constraint=models.CheckConstraint(condition=models.Q(('ledger__isnull', True), ('client_funds_ledger__isnull', True), _connector='OR'), name='transaction_cannot_use_two_client_ledgers'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('engagement__isnull', True), ('matter__isnull', False), ('proposed_matter__isnull', True)), models.Q(('engagement__isnull', False), ('matter__isnull', True), ('proposed_matter__isnull', False)), _connector='OR'), name='receipt_has_matter_or_prematter_context'),
        ),
        migrations.AddConstraint(
            model_name='receiptallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('allocation_type', 'INVOICE'), _negated=True), ('invoice__isnull', False), _connector='OR'), name='invoice_allocation_requires_invoice'),
        ),
        migrations.AddConstraint(
            model_name='receiptallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('allocation_type', 'RETAINER'), _negated=True), ('engagement__isnull', False), _connector='OR'), name='retainer_allocation_requires_engagement'),
        ),
    ]
