# Generated by Django 6.0.5 on 2026-08-04 15:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_invoice_paid_and_credited_within_total_and_more'),
        ('firm', '0003_firmsetting_allow_engagement_waiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_configuration_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('vat_registered', models.BooleanField(default=False)),
                ('vat_registration_number', models.CharField(blank=True, default='', max_length=80)),
                ('vat_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('tax_inclusive', models.BooleanField(default=False)),
                ('withholding_tax_enabled', models.BooleanField(default=False)),
                ('withholding_tax_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('withholding_tax_label', models.CharField(blank=True, default='', max_length=120)),
                ('exempt_or_zero_rated_label', models.CharField(blank=True, default='', max_length=255)),
                ('default_currency', models.CharField(default='KES', max_length=3)),
                ('rounding_policy', models.CharField(default='HALF_UP', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_configurations', to='firm.lawfirm')),
            ],
            options={
                'db_table': 'billing_tax_configurations',
                'ordering': ['-effective_from', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('firm', 'effective_from'), name='unique_tax_configuration_effective_date')],
            },
        ),
    ]
