import React from 'react';
import { Field, SelectField, StepPanel } from './Fields';

const fieldsByType = {
  INDIVIDUAL: [['first_name','First name'],['middle_name','Middle name'],['last_name','Last name'],['preferred_name','Preferred name'],['identification_number','Identification number'],['identification_country','Issuing country'],['identification_expiry_date','Expiry date','date'],['nationality','Nationality'],['citizenship','Citizenship'],['preferred_language','Preferred language']],
  SOLE_PROPRIETORSHIP: [['registered_business_name','Registered business name'],['trading_name','Trading name'],['business_registration_number','Registration number'],['registration_date','Registration date','date'],['proprietor_name','Proprietor legal name'],['proprietor_identifier','Proprietor ID / passport'],['proprietor_kra_pin','Proprietor KRA PIN'],['business_kra_pin','Business KRA PIN'],['business_sector','Nature / sector of business']],
  COMPANY: [['company_name','Exact registered company name'],['trading_name','Trading / business name'],['registration_number','Company registration number'],['incorporation_date','Incorporation date','date'],['country_of_incorporation','Country of incorporation'],['registration_authority','Registration authority'],['registration_document_reference','Registration evidence reference'],['registration_verification_source','Verification source'],['industry','Industry / sector'],['nature_of_business','Nature of business'],['website','Website']],
  PARTNERSHIP: [['partnership_name','Partnership name'],['registration_number','Registration number'],['formation_date','Formation date','date'],['tax_pin','KRA PIN'],['principal_place_of_business','Principal place of business'],['partnership_agreement_reference','Partnership agreement reference'],['business_sector','Nature of business']],
  LIMITED_LIABILITY_PARTNERSHIP: [['registered_name','Registered LLP name'],['llp_registration_number','LLP registration number'],['registration_date','Registration date','date'],['country_of_registration','Country'],['kra_pin','KRA PIN'],['registered_office','Registered office'],['principal_business_address','Principal business address'],['sector','Nature / sector of business']],
  COOPERATIVE: [['registered_name','Registered name'],['registration_number','Registration number'],['registration_date','Registration date','date'],['kra_pin','KRA PIN'],['registered_office','Registered / head office'],['area_of_operation','Area of operation'],['activity_sector','Activity / sector'],['regulator_name','Relevant authority / regulator'],['license_number','Licence / authorization number'],['license_status','Licence status']],
  SOCIETY_OR_ASSOCIATION: [['legal_name','Registered / legal name'],['common_name','Common name'],['registration_number','Registration number'],['registration_authority','Registration authority'],['registration_date','Registration date','date'],['constitution_reference','Constitution reference'],['formation_date','Formation date','date'],['objectives','Objectives'],['sector','Sector'],['principal_office','Principal office'],['litigation_authority_reference','Instruction / litigation authority reference']],
  NON_PROFIT_ORGANIZATION: [['registered_name','Registered PBO name'],['registration_number','PBO registration number'],['legacy_ngo_registration_number','Legacy NGO registration number'],['former_registration_authority','Former registration authority'],['historical_registration_date','Historical NGO registration date','date'],['registration_authority','Registration authority (PBORA where applicable)'],['registration_date','Current PBO status / registration date','date'],['constitution_reference','Constitution reference'],['objectives','Public benefit purposes'],['sector','Sectors'],['operational_scope','Counties / regions of operation'],['headquarters_or_principal_office','Headquarters / principal office'],['governance_structure','Governance structure'],['governing_body_details','Governing body details'],['funding_compliance_notes','Funding / compliance notes']],
  TRUST: [['trust_name','Trust name'],['trust_deed_reference','Trust deed / reference'],['trust_deed_date','Trust deed date','date'],['jurisdiction','Jurisdiction'],['purpose','Purpose'],['principal_address','Principal address'],['registration_number','Registration number'],['settlor_details','Settlor information where required'],['beneficiary_details','Beneficiary class / description where required']],
  ESTATE: [['estate_name','Standardized estate name'],['deceased_full_name','Deceased full legal name'],['deceased_id_number','Deceased ID / passport'],['date_of_death','Date of death','date'],['deceased_last_address','Last known address'],['probate_number','Succession cause number'],['court_reference','Court'],['grant_issue_date','Grant issue date','date'],['grant_confirmation_date','Grant confirmation date','date'],['assets_description','Assets summary'],['liabilities_description','Liabilities summary']],
  PUBLIC_ENTITY: [['official_name','Official legal name'],['enabling_instrument','Enabling Act / Charter / instrument'],['parent_ministry_or_county','Parent ministry / county'],['legal_capacity_notes','Legal capacity notes'],['official_address','Official address'],['department_or_unit','Department / unit'],['official_contact','Official contact'],['legal_department_contact','Legal department contact'],['kra_pin','KRA PIN'],['verification_source_reference','Verification source / reference'],['verification_notes','Verification notes']],
  INTERNATIONAL_ORGANIZATION: [['official_name','Official legal name'],['founding_instrument','Founding treaty / instrument'],['headquarters_country','Headquarters country'],['kenya_recognition_details','Kenya recognition / accreditation'],['privileges_immunities_status','Privileges / immunities status'],['kenya_office_address','Kenyan office'],['verification_notes','Verification source / date']],
};

export default function LegalIdentityStep({ state, metadata, setClient, setProfile }) {
  const type = state.client.client_type; const p = state.legal_profile;
  return <StepPanel title='Legal identity' description='Record the identity shown by the applicable legal or registration instrument.'>
    <div className='grid gap-4 md:grid-cols-2'><Field label='Canonical legal/display name' required value={state.client.full_name} onChange={(v) => setClient({ full_name: v })}/><SelectField label='Access mode' value={state.client.access_type} onChange={(v) => setClient({ access_type: v })} options={metadata.access_types}/><Field label='Primary / portal email' type='email' required={state.client.access_type==='PORTAL_ENABLED'} value={state.client.email} onChange={(v)=>setClient({email:v})}/><Field label='Primary phone' value={state.client.phone_number} onChange={(v)=>setClient({phone_number:v})}/>
    {type === 'INDIVIDUAL' && <><SelectField label='Identification type' required value={p.identification_type} onChange={(v) => setProfile({ identification_type: v, identification_number: '' })} options={['NATIONAL_ID','PASSPORT','ALIEN_ID','REFUGEE_ID','BIRTH_CERTIFICATE','OTHER_GOVERNMENT_ID'].map((v) => ({ value:v, label:v.split('_').map(x=>x[0]+x.slice(1).toLowerCase()).join(' ') }))}/><Field label='Date of birth' type='date' value={state.client.date_of_birth} onChange={(v) => setClient({date_of_birth:v})}/></>}
    {type === 'COOPERATIVE' && <SelectField label='Co-operative subtype' required value={p.subtype} onChange={(v) => setProfile({subtype:v})} options={metadata.cooperative_subtypes}/>} 
    {type === 'PUBLIC_ENTITY' && <SelectField label='Public entity subtype' required value={p.subtype} onChange={(v) => setProfile({subtype:v})} options={metadata.public_entity_subtypes}/>} 
    {type === 'INTERNATIONAL_ORGANIZATION' && <SelectField label='Organization type' required value={p.organization_type} onChange={(v) => setProfile({organization_type:v})} options={metadata.international_organization_types}/>} 
    {type === 'OTHER_REQUIRES_REVIEW' ? <><Field label='Provisional legal description' required value={state.client.provisional_legal_description} onChange={(v)=>setClient({provisional_legal_description:v})}/><Field label='Enabling / registration evidence reference' required value={state.client.classification_evidence_reference} onChange={(v)=>setClient({classification_evidence_reference:v})}/></> : (fieldsByType[type] || []).map(([key,label,kind]) => <Field key={key} label={label} type={kind} value={p[key]} onChange={(v) => setProfile({[key]:v})}/>)}
    </div>
  </StepPanel>;
}
