import React from 'react';
import { Field, SelectField, StepPanel } from './Fields';

export default function RegulatoryProfileStep({ state, metadata, setClient, setEducation }) {
  const education = state.regulatory_profiles.education || {};
  const educationSelected = state.client.sectors.includes('EDUCATION');
  const toggleSector = (sector) => setClient({ sectors: state.client.sectors.includes(sector) ? state.client.sectors.filter((s) => s !== sector) : [...state.client.sectors, sector] });
  return <StepPanel title='Sector / regulatory status' description='Sector overlays do not change the client’s legal classification.'>
    <div className='flex flex-wrap gap-2'>{(metadata.sectors || []).map((s) => <button type='button' key={s.value} onClick={() => toggleSector(s.value)} className={`rounded-full border px-3 py-2 text-sm ${state.client.sectors.includes(s.value) ? 'bg-blue-600 text-white' : ''}`}>{s.label}</button>)}</div>
    {educationSelected && <div className='grid gap-4 border-t pt-5 md:grid-cols-2'>
      <SelectField label='Education regime' required value={education.education_regime} onChange={(v)=>setEducation({education_regime:v})} options={metadata.education_regimes}/><SelectField label='Ownership' required value={education.ownership} onChange={(v)=>setEducation({ownership:v})} options={metadata.education_ownerships}/>
      <Field label='Institution official name' required value={education.institution_official_name} onChange={(v)=>setEducation({institution_official_name:v})}/><Field label='Legal owner / operator name' required={education.ownership==='PRIVATE'} value={education.operator_legal_name} onChange={(v)=>setEducation({operator_legal_name:v})}/>
      <Field label='Registration / accreditation number' value={education.registration_number} onChange={(v)=>setEducation({registration_number:v})}/><Field label='Regulator / education authority' value={education.regulator} onChange={(v)=>setEducation({regulator:v})}/><Field label='County' value={education.county} onChange={(v)=>setEducation({county:v})}/><Field label='Physical location' value={education.physical_location} onChange={(v)=>setEducation({physical_location:v})}/>
      {education.education_regime === 'BASIC_EDUCATION' && <div className='md:col-span-2'><span className='mb-2 block text-sm font-medium'>Education levels *</span><div className='flex flex-wrap gap-2'>{(metadata.basic_education_levels||[]).map((level)=><button type='button' key={level.value} onClick={()=>setEducation({education_levels:(education.education_levels||[]).includes(level.value)?education.education_levels.filter(x=>x!==level.value):[...(education.education_levels||[]),level.value]})} className={`rounded border px-2 py-1 text-sm ${(education.education_levels||[]).includes(level.value)?'bg-blue-600 text-white':''}`}>{level.label}</button>)}</div></div>}
      {education.education_regime === 'UNIVERSITY' && <><SelectField label='CUE category' required value={education.university_category} onChange={(v)=>setEducation({university_category:v})} options={metadata.university_categories}/><Field label='Parent university' required={education.university_category?.includes('CONSTITUENT')} value={education.parent_university} onChange={(v)=>setEducation({parent_university:v})}/><Field label='CUE reference' value={education.cue_reference} onChange={(v)=>setEducation({cue_reference:v})}/><Field label='Charter / LIA reference' value={education.charter_reference||education.interim_authority_reference} onChange={(v)=>setEducation({charter_reference:v})}/></>}
      {education.education_regime === 'TVET' && <><SelectField label='TVET category' required value={education.tvet_category} onChange={(v)=>setEducation({tvet_category:v})} options={metadata.tvet_categories}/><Field label='Licence expiry' type='date' value={education.licence_expiry} onChange={(v)=>setEducation({licence_expiry:v})}/><Field label='Accredited programmes' value={education.accredited_programmes} onChange={(v)=>setEducation({accredited_programmes:v})}/></>}
      <SelectField label='Curriculum framework' value={education.curricula?.[0]?.framework} onChange={(v)=>setEducation({curricula:[{...(education.curricula?.[0]||{}),framework:v}]})} options={metadata.curriculum_frameworks}/>
      {education.curricula?.[0]?.framework === 'INTERNATIONAL_FOREIGN' && <><Field label='Curriculum name' required value={education.curricula[0].curriculum_name} onChange={(v)=>setEducation({curricula:[{...education.curricula[0],curriculum_name:v}]})}/><Field label='Awarding / development body' required value={education.curricula[0].awarding_or_development_body} onChange={(v)=>setEducation({curricula:[{...education.curricula[0],awarding_or_development_body:v}]})}/><Field label='Country / framework' required value={education.curricula[0].country_or_framework} onChange={(v)=>setEducation({curricula:[{...education.curricula[0],country_or_framework:v}]})}/></>}
      <Field label='Registration evidence reference' value={education.registration_document_reference} onChange={(v)=>setEducation({registration_document_reference:v})}/><Field label='Manual verification source' value={education.verification_source} onChange={(v)=>setEducation({verification_source:v})}/>
    </div>}
  </StepPanel>;
}
