# Generated by Django 6.0.5 on 2026-07-16 04:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('audience_type', models.CharField(choices=[('ALL_STAFF', 'All Staff'), ('TARGETED', 'Targeted Staff')], default='ALL_STAFF', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'communication_announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRecipient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'communication_announcement_recipients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('SYSTEM', 'System')], default='TEXT', max_length=20)),
                ('is_system_message', models.BooleanField(default=False)),
                ('is_forwarded', models.BooleanField(default=False)),
                ('forward_direction', models.CharField(blank=True, default='', max_length=30)),
            ],
            options={
                'db_table': 'communication_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thread_type', models.CharField(choices=[('DIRECT_STAFF', 'Admin Staff Direct Chat'), ('CASE_CLIENT', 'Case Client Communication')], max_length=30)),
                ('thread_key', models.CharField(help_text='Stable unique key, for example direct_staff:<firm>:<admin>:<staff> or case_client:<case>.', max_length=255, unique=True)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'communication_chat_threads',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatThreadParticipant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_reply', models.BooleanField(default=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'communication_chat_thread_participants',
                'ordering': ['created_at'],
            },
        ),
    ]
