# Generated by Django 6.0.5 on 2026-07-16 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0003_initial'),
        ('communications', '0001_initial'),
        ('firm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='firm.lawfirm'),
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='communications.announcement'),
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='recipient_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_recipients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_messages', to='communications.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_threads', to='cases.case'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='firm.lawfirm'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.chatthread'),
        ),
        migrations.AddField(
            model_name='chatthreadparticipant',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='communications.chatthread'),
        ),
        migrations.AddField(
            model_name='chatthreadparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_thread_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['firm', 'audience_type'], name='communicati_firm_id_a8425d_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['firm', 'is_active'], name='communicati_firm_id_254e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementrecipient',
            index=models.Index(fields=['recipient_user', 'read_at'], name='communicati_recipie_69ef33_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementrecipient',
            constraint=models.UniqueConstraint(fields=('announcement', 'recipient_user'), name='unique_announcement_recipient'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['firm', 'thread_type'], name='communicati_firm_id_ae246c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['firm', 'is_active'], name='communicati_firm_id_c90cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['case'], name='communicati_case_id_dca1e1_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['last_message_at'], name='communicati_last_me_c90030_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'created_at'], name='communicati_thread__8334d0_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender'], name='communicati_sender__19633f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthreadparticipant',
            index=models.Index(fields=['user', 'can_reply'], name='communicati_user_id_eeae9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatthreadparticipant',
            constraint=models.UniqueConstraint(fields=('thread', 'user'), name='unique_thread_participant'),
        ),
    ]
