# Generated by Django 6.0.5 on 2026-08-04 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_matterdeadline_deadlinechangehistory_and_more'),
        ('clients', '0031_clientcompliancereview_clientcompliancehistory_and_more'),
        ('communications', '0002_initial'),
        ('firm', '0003_firmsetting_allow_engagement_waiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCommunication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('communication_type', models.CharField(max_length=80)),
                ('occurred_at', models.DateTimeField()),
                ('participants', models.JSONField(default=list)),
                ('direction', models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing')], max_length=16)),
                ('channel', models.CharField(choices=[('IN_PERSON', 'In-person meeting'), ('TELEPHONE', 'Telephone'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('CLIENT_PORTAL', 'Client portal'), ('LETTER', 'Letter'), ('VIDEO', 'Video meeting'), ('COURT_ATTENDANCE', 'Court attendance'), ('OTHER', 'Other')], max_length=24)),
                ('subject', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('advice_given', models.TextField(blank=True, default='')),
                ('instructions_received', models.TextField(blank=True, default='')),
                ('instructions_confirmed_in_writing', models.BooleanField(default=False)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_deadline', models.DateTimeField(blank=True, null=True)),
                ('confidentiality_level', models.CharField(default='CONFIDENTIAL', max_length=32)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communications', to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_client_communications', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_communications', to='firm.lawfirm')),
                ('linked_documents', models.ManyToManyField(blank=True, related_name='linked_communications', to='clients.clientdocument')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_communications', to='cases.case')),
                ('responsible_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_client_communications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_communication_records',
            },
        ),
        migrations.CreateModel(
            name='CommunicationAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_values', models.JSONField(default=dict)),
                ('new_values', models.JSONField(default=dict)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_amendments', to=settings.AUTH_USER_MODEL)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='communications.clientcommunication')),
            ],
            options={
                'db_table': 'client_communication_amendments',
            },
        ),
    ]
