import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import Card from '@/components/ui/Card';
import { FormButton, SelectInput, TextArea, TextInput } from '@/components/forms';
import axiosInstance from '@/core/api/axios';
import { formatDateTime } from '@/core/utils/dateFormatter';

export default function PhysicalMatterFileCard({ physicalFile, caseId, canManage = false, canRequest = false }) {
  const queryClient = useQueryClient();
  const [action, setAction] = useState('');
  const [draft, setDraft] = useState({ reason: '', storage_zone: physicalFile?.storage_zone || '', cabinet: physicalFile?.cabinet || '', shelf_or_drawer: physicalFile?.shelf_or_drawer || '', location_detail: physicalFile?.location_detail || '' });
  const custodyAction = useMutation({
    mutationFn: (payload) => axiosInstance.post(`/cases/${caseId}/physical-file/`, payload),
    onSuccess: () => { setAction(''); setDraft((current) => ({ ...current, reason: '' })); queryClient.invalidateQueries(); },
  });
  if (!physicalFile) return null;
  const pending = physicalFile.assignment_pending;
  return <Card className={`p-5 ${pending ? 'border-l-4 border-l-amber-500' : 'border-l-4 border-l-brand-primary'}`}>
    <div className='flex flex-wrap items-start justify-between gap-3'>
      <div><p className='text-xs font-semibold uppercase tracking-[0.16em] text-brand-primary'>Records custody</p><h2 className='mt-1 text-lg font-semibold text-text-primary-light dark:text-text-primary-dark'>Physical Matter File</h2></div>
      <span className={`rounded-full px-3 py-1 text-xs font-semibold ${pending ? 'bg-amber-100 text-amber-900 dark:bg-amber-950 dark:text-amber-200' : 'bg-emerald-100 text-emerald-900 dark:bg-emerald-950 dark:text-emerald-200'}`}>{physicalFile.status_label}</span>
    </div>
    {pending ? <div className='mt-4 rounded-lg bg-amber-50 p-4 text-sm text-amber-900 dark:bg-amber-950/40 dark:text-amber-100'><strong>Physical matter file awaiting preparation</strong><p className='mt-1'>The internal matter has been opened, but authorised records staff have not yet confirmed creation and physical storage of its folder.</p></div> : <div className='mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3'><p><strong>Reference</strong><br />{physicalFile.reference}</p><p><strong>Exact location</strong><br />{physicalFile.location || 'Location not confirmed'}</p><p><strong>Current custody</strong><br />{physicalFile.current_custodian || 'Records room'}</p><p><strong>Assigned by</strong><br />{physicalFile.assigned_by || 'Not recorded'}</p><p><strong>Assigned at</strong><br />{physicalFile.assigned_at ? formatDateTime(physicalFile.assigned_at) : 'Not recorded'}</p><p><strong>Last movement</strong><br />{physicalFile.last_movement ? `${physicalFile.last_movement.action_label} · ${formatDateTime(physicalFile.last_movement.recorded_at)}` : 'None recorded'}</p></div>}
    <details className='mt-4 border-t border-border-light pt-3 dark:border-border-dark'><summary className='cursor-pointer text-sm font-semibold text-brand-primary'>View custody history</summary><div className='mt-3 space-y-2'>{(physicalFile.movements || []).map((item) => <div key={item.id} className='rounded-lg bg-black/[0.03] p-3 text-sm dark:bg-white/[0.04]'><strong>{item.action_label}</strong><p>{item.previous_location || 'No previous location'} → {item.new_location || 'No location assigned'}</p><small>{formatDateTime(item.recorded_at)} · {item.recorded_by}</small></div>)}</div></details>
    {canRequest && !pending && <div className='mt-4 flex justify-end'><FormButton type='button' variant='secondary' loading={custodyAction.isPending} onClick={() => custodyAction.mutate({ operation: 'request_retrieval', reason: 'Responsible advocate requested retrieval of the physical matter file.' })}>Request retrieval</FormButton></div>}
    {canManage && !pending && <div className='mt-4 border-t border-border-light pt-4 dark:border-border-dark'><h3 className='text-sm font-semibold'>Record custody action</h3><div className='mt-3 grid gap-3 md:grid-cols-2'><SelectInput label='Action' name='physical_file_action' value={action} onChange={(event) => setAction(event.target.value)} options={[{ value: 'CHECKED_OUT', label: 'Check out to responsible advocate' }, { value: 'RETURNED', label: 'Return to records room' }, { value: 'RELOCATED', label: 'Relocate' }, { value: 'MARKED_MISSING', label: 'Mark missing' }, { value: 'FOUND', label: 'Record found' }, { value: 'SENT_FOR_ARCHIVING', label: 'Send for archive review' }, { value: 'ARCHIVED', label: 'Confirm archived' }]} />{['RELOCATED','ARCHIVED'].includes(action) && <><TextInput label='Storage zone' value={draft.storage_zone} onChange={(event) => setDraft({ ...draft, storage_zone: event.target.value })} /><TextInput label='Cabinet' value={draft.cabinet} onChange={(event) => setDraft({ ...draft, cabinet: event.target.value })} /><TextInput label='Shelf/drawer' value={draft.shelf_or_drawer} onChange={(event) => setDraft({ ...draft, shelf_or_drawer: event.target.value })} /><TextInput label='Additional location' value={draft.location_detail} onChange={(event) => setDraft({ ...draft, location_detail: event.target.value })} /></>}<TextArea label='Reason' value={draft.reason} onChange={(event) => setDraft({ ...draft, reason: event.target.value })} className='md:col-span-2' required /></div>{custodyAction.error && <p className='mt-2 text-sm text-error'>The custody action could not be recorded.</p>}<div className='mt-3 flex justify-end'><FormButton type='button' disabled={!action || !draft.reason} loading={custodyAction.isPending} onClick={() => custodyAction.mutate({ operation: 'move', action, reason: draft.reason, issued_to: action === 'CHECKED_OUT' ? 'ASSIGNED_LAWYER' : undefined, storage_zone: draft.storage_zone, cabinet: draft.cabinet, shelf_or_drawer: draft.shelf_or_drawer, location_detail: draft.location_detail })}>Record action</FormButton></div></div>}
  </Card>;
}
