# Generated by Django 6.0.5 on 2026-07-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('OFFICIAL_CLIENT', 'Official Client'), ('PROSPECT', 'Prospect')], default='PROSPECT', max_length=30),
        ),
    ]
