# Generated by Django 6.0.5 on 2026-09-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_admins_do_not_require_password_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('OFFICIAL_CLIENT', 'Official Client'), ('PROSPECT', 'Prospect'), ('PLATFORM_ADMIN', 'Platform administrator')], default='PROSPECT', max_length=30),
        ),
    ]
