import { LockKeyhole } from 'lucide-react';

export function FormPage({ children, className = '' }) { return <div className={`mx-auto w-full max-w-[1180px] space-y-6 px-4 py-5 sm:px-6 lg:py-7 ${className}`}>{children}</div>; }
export function FormHeader({ title, description, eyebrow, meta, actions }) { return <header className='flex flex-col gap-4 border-b border-border-light pb-5 dark:border-border-dark md:flex-row md:items-end md:justify-between'><div>{eyebrow && <p className='mb-1 text-xs font-bold uppercase tracking-[0.14em] text-brand-accent'>{eyebrow}</p>}<h1 className='text-2xl font-bold tracking-tight text-text-primary-light dark:text-text-primary-dark'>{title}</h1>{description && <p className='mt-2 max-w-3xl text-sm leading-6 text-text-muted-light dark:text-text-muted-dark'>{description}</p>}{meta && <div className='mt-3'>{meta}</div>}</div>{actions && <div className='shrink-0'>{actions}</div>}</header>; }
export function FormCard({ children, className = '' }) { return <div className={`rounded-xl border border-border-light bg-surface-light p-5 shadow-soft dark:border-border-dark dark:bg-surface-dark sm:p-6 ${className}`}>{children}</div>; }
export function FormSection({ title, description, children, className = '' }) { return <section className={`space-y-5 ${className}`}><header className='border-b border-border-light pb-3 dark:border-border-dark'><h2 className='text-base font-bold text-text-primary-light dark:text-text-primary-dark'>{title}</h2>{description && <p className='mt-1 max-w-3xl text-sm leading-5 text-text-muted-light dark:text-text-muted-dark'>{description}</p>}</header>{children}</section>; }
export function FormGrid({ children, columns = 2, className = '' }) { const grid = columns === 3 ? 'lg:grid-cols-3' : columns === 1 ? 'grid-cols-1' : 'md:grid-cols-2'; return <div className={`grid grid-cols-1 gap-x-5 gap-y-4 ${grid} ${className}`}>{children}</div>; }
export function ReadOnlyField({ label, value, help, className = '' }) { return <div className={`space-y-1.5 ${className}`}><div className='flex items-center justify-between gap-2'><span className='text-sm font-semibold text-text-primary-light dark:text-text-primary-dark'>{label}</span><span className='inline-flex items-center gap-1 text-[11px] font-medium text-text-muted-light dark:text-text-muted-dark'><LockKeyhole size={12} />Read only</span></div><div className='min-h-11 rounded-lg border border-border-light bg-slate-100 px-3.5 py-2.5 text-sm text-text-primary-light dark:border-border-dark dark:bg-slate-900 dark:text-text-primary-dark'>{value || 'Not recorded'}</div>{help && <p className='text-xs text-text-muted-light dark:text-text-muted-dark'>{help}</p>}</div>; }

